### ISSUE TITLE
Explain difference

### ISSUE THREAD

**Issue by Neurotoxin001** [BtbN/FFmpeg-Builds#1]
Can you please explain what difference between these builds?
![image](https://user-images.githubusercontent.com/39812401/93681078-a0622580-fab6-11ea-9025-bccff939bc41.png)

**Comment by BtbN** [comment]
See the variant suffix at the end.
The ones with vulkan support vulkan, the ones with lgpl are lgpl, the gpl ones gpl, and the 4.3 ones are from the 4.3 release branch.

**Comment by ScribbleGhost** [comment]
I understand that each build comes with a different license, and I assume each release therefore contains different content such as codecs? It would be nice to know how each build differ in content. After reading this it is still not clear to me which one I should use. But I might me an idiot 😂

**Comment by BtbN** [comment]
Some encoders, most notably x264 and x265, are GPL-Only. So they are not part of the LGPL builds.
That's pretty much the only notable difference between the two from a pure user perspective.
See the GPL-Library-List in ffmpegs configure script for a detailed list of what's GPL-only.

**Comment by zwcloud** [comment]
> Some encoders, most notably x264 and x265, are GPL-Only. So they are not part of the LGPL builds.
> That's pretty much the only notable difference between the two from a pure user perspective.
> See the GPL-Library-List in ffmpegs configure script for a detailed list of what's GPL-only.

This infomation is essential and should be pointed out in the release info. I got `Unknown encoder 'libx264'` error if downloaded the non-GPL version.

**Comment by zhushenhang** [comment]
> Some encoders, most notably x264 and x265, are GPL-Only. So they are not part of the LGPL builds.
> That's pretty much the only notable difference between the two from a pure user perspective.
> See the GPL-Library-List in ffmpegs configure script for a detailed list of what's GPL-only.

thanks.
I received an error yesterday `Unknown encoder ‘libx265’`.
now I understand.
