### ISSUE TITLE
[Feature request]Enable AVS2, which is better than H265.

### ISSUE THREAD

**Issue by lenny20** [BtbN/FFmpeg-Builds#10]
AVS2 (IEEE 1857, GPL v2) is faster than H265 and AV1, and the patent licensing fees is very simple and affordable.
Thank you, very much!

**Comment by BtbN** [comment]
Does ffmpeg even support that? I never heard of that codec before.

**Comment by GyanD** [comment]
Wrapper for AVS was added a decade ago. AVS2 in 2018, and AVS3 very recently. Fairly popular in China, from what I gather. Mainly meant to work around patent issues with the MPEG family of codecs.

**Comment by BtbN** [comment]
I added d/xavs2 and avs3d, since it's easy enough and it does not seem like a license issue.
