### ISSUE TITLE
.mkv attachements not coped properly

### ISSUE THREAD

**Issue by vlyak** [BtbN/FFmpeg-Builds#101]
bug: in .mkv file format stream attachemet (picture, png) coped, but not set disposition to attached_pic
direct key like "-disposition:v:1 attached_pic" also not worked

**Comment by sudo-nautilus** [comment]
Check [this](https://stackoverflow.com/a/30563612)

**Comment by BtbN** [comment]
Is that an issue specific to these builds? If not, please report it on ffmpeg trac and close this issue.

**Comment by sudo-nautilus** [comment]
Yeah he's right

**Comment by vlyak** [comment]
update issue: if .mkv file file contains a tag or global tag, bug is work. Delete tags from file, and attached pic coped properly.

**Comment by vlyak** [comment]
> 
> 
> Is that an issue specific to these builds? If not, please report it on ffmpeg trac and close this issue.

I'm use only these builds

**Comment by BtbN** [comment]
That's still not an issue specific to the builds. Please report issues with ffmpeg itself on FFmpeg trac or ask for support on ffmpeg-users.
