### ISSUE TITLE
Add OpenH264 when building LGPL

### ISSUE THREAD

**Issue by linville** [BtbN/FFmpeg-Builds#102]
It would be nice to add in the [OpenH264](https://github.com/cisco/openh264) library when building LGPL.

**Comment by BtbN** [comment]
I see no indication of openh264 being incompatible with the GPL. Is there something I'm missing?

**Comment by linville** [comment]
No, you are correct, it's BSD 2-clause and is compatible. I just figured anybody using the GPL build would probably just use x264 (which is purportedly more performant and has more features).

**Comment by BtbN** [comment]
Added in 634a3f68acffef61817621c6ab7713fe6729e2ec
