### ISSUE TITLE
Consider using musl.cc cross toolchain instead of crosstool-ng

### ISSUE THREAD

**Issue by abcfy2** [BtbN/FFmpeg-Builds#105]
I think http://musl.cc/ is a better choice, as `musl` is lightweight and easy to static link, and it's does not require a high version kernel and glibc.

Maybe also will resolve #104  

Thanks.

**Comment by nanake** [comment]
https://github.com/BtbN/FFmpeg-Builds/issues/55#issuecomment-839936548

**Comment by BtbN** [comment]
I've looked into musl in the past. And even got somewhat working builds going.
But the by far biggest showstopper is that when not using the normal glibc dynamic linker, unsurprisingly dynamic linking stops working.
FFmpeg dlopens a ton of its dependencies though. So using musl would come at the cost of no more CUDA, nvenc, nvdec, vaapi, Vulkan, avisynth, ladspa/lv2, and probably a bunch of other stuff I forgot about.

So, musl is not really a realistic option.

**Comment by BtbN** [comment]
Yes, you can build with musl, but everything it dlopens at runtime will plain not work. And that affects a lot of commonly used features, so I'm not willing to give those up.

**Comment by BtbN** [comment]
That's exactly what it would do, yes.
And it would do exactly what I described, breaking dlopen.

**Comment by BtbN** [comment]
Closing here. Using musl unfortunately isn't feasible for usable builds.

**Comment by ValZapod** [comment]
> does not require a high version kernel and glibc.

Why is that good? Kernel and glibc are both very buggy, and lets not start on gcc. Insane bugs and 💩 code, at least they kinda had to have such insane code, especially glibc.
