### ISSUE TITLE
How do I know the versions of the third-party libraries?

### ISSUE THREAD

**Issue by AnnieXuY** [BtbN/FFmpeg-Builds#111]
I downloaded the zip package from "Auto-Build" and the executable ffmpeg links the required three-party libraries. How do I know the versions of these third-party libraries?
Thanks!

**Comment by CanadianJeff** [comment]
could you maybe tell people where you found it in the source code so other people can look?

**Comment by Alice-Thirty** [comment]
maybe https://github.com/BtbN/FFmpeg-Builds/tree/master/scripts.d/
