### ISSUE TITLE
Add libplacebo

### ISSUE THREAD

**Issue by ValZapod** [BtbN/FFmpeg-Builds#114]
This is commit https://github.com/FFmpeg/FFmpeg/commit/51e03409d74f3eb265cd4e562819daffb3645cb0

https://code.videolan.org/videolan/libplacebo

Use master, not latest release of libplacebo.

**Comment by BtbN** [comment]
I tried doing that in the past, and the resulting binaries just plain did not work on Windows, while on Linux the builds failed horribly because statically linked Vulkan just plain isn't a thing on Linux, and already quite a hack in Windows.
Will re-evaluate, but I'm not aware of anything having changed there sadly.

**Comment by ValZapod** [comment]
> I tried doing that in the past, and the resulting binaries just plain did not work on Windows

Did you use v1 of the patch then? Ffmpeg just updated to Vulkan 1.2 just before that commit. So did libplacebo yesterday. Also latest commit from mpv enabling hdr10 metadata is updated for Vulkan and @quitvoid updated everything and it works on windows. https://github.com/mpv-player/mpv/pull/9421

**Comment by BtbN** [comment]
libplacebo itself is what failed to build, not FFmpeg.

**Comment by ValZapod** [comment]
> libplacebo itself is what failed to build, not FFmpeg.

But ffmpeg also requires that now afger all updates from yesterday, no?

**Comment by BtbN** [comment]
No, ffmpeg fully dynamically loads Vulkan now, so does not really need the weird loader that's not a loader anymore.

**Comment by ValZapod** [comment]
> weird loader that's not a loader anymore.

Does not new v2 patch uses Lynne code for new Vulkan? I though they syncronised it somehow.

**Comment by BtbN** [comment]
I have no idea what you mean by "new v2 patch".

**Comment by ValZapod** [comment]
> by "new v2 patch".

I mean v2 patch on patchwork that is this commit FFmpeg/FFmpeg@51e0340

**Comment by ValZapod** [comment]
@Lynne @haasn

**Comment by BtbN** [comment]
I don't think you're understanding the issue.
This is not about FFmpeg.
This is about libplacebo itself linking directly to libvulkan-1.dll, and thus is unable to be properly used in a static build like this.
I've went through quite some effort to make Vulkan work at all in this setting, and it's semi-broken on Windows, and does not work at all on Linux.

**Comment by ValZapod** [comment]
> libplacebo itself linking directly to libvulkan-1.dll,

I understand and IMHO there should be a way to dynamically link it at least from ffmpeg.

**Comment by BtbN** [comment]
FFmpeg already just dlopens it.
But that's completely irrelevant to what libplacebo does.
It needs to be directly linked against libvulkan-1

**Comment by haasn** [comment]
> FFmpeg already just dlopens it. But that's completely irrelevant to what libplacebo does. It needs to be directly linked against libvulkan-1

This is not true, you can disable linking against vulkan by passing `-Dvulkan-link=false` in the libplacebo build configuration.

**Comment by BtbN** [comment]
For that to work FFmpeg needs to pass in its version of get_proc_addr, which I could not find being done anywhere in the code.

**Comment by haasn** [comment]
It's done [here](https://github.com/FFmpeg/FFmpeg/commit/51e03409d74f3eb265cd4e562819daffb3645cb0#diff-40d30e5f8d9d15534f349355101340a782f0aea0512de3cc9bfce8e3e6a7975eR203) in the linked commit.

**Comment by BtbN** [comment]
Ah, so that's why it never mentions "pl_vk_inst" nowhere.
I'm gonna try adding placebo again, but it really did not go well last time (i.e. Windows binaries did not work in regards to Vulkan, and on Linux it explodes horribly)

**Comment by BtbN** [comment]
Latest build has libplacebo added on Both Windows and Linux.
Vulkan support was completely dropped from 4.4 in the process, since it still needs to link the loader.

Will close here once it's been reasonably tested to actually work.

**Comment by ValZapod** [comment]
Please update to 5e8fdf23 that implemented Dolby Vision's MMR reshaping with IPTPQc2 space.

**Comment by ValZapod** [comment]
Dolby Vision now perfectly works after yesterday's commits in mpv! Decoding happens using SW still though, but d3d11 context and decoding to PQ happens correctly when you traget-trc PQ and target-prim BT.2020.
