### ISSUE TITLE
ffplay can't open display

### ISSUE THREAD

**Issue by teocci** [BtbN/FFmpeg-Builds#115]
I've installed the latest version and I got this error:
```sh
ffplay version n4.4.1-2-gcc33e73618-20211115 Copyright (c) 2003-2021 the FFmpeg developers
  built with gcc 11.2.0 (crosstool-NG 1.24.0.479_aa52493)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libvmaf --enable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --disable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-mbedtls --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --disable-vulkan --disable-libglslang --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs=-lgomp --extra-version=20211115
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Could not initialize SDL - No available video device
(Did you set the DISPLAY variable?)
```

Didn't look much into this but I can reproduce with `libsdl2[-X]`

Probably we can try to rebuild `libsdl2` with `USE=X` enabled.

The distro I'm running is:
```sh
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```

**Comment by wabberz** [comment]
I tried this, but it didn't work either. One thing I did note is there are far fewer devices listed.

With `ffmpeg-amd-full` from AUR (Arch):
```bash
$ ffplay -hide_banner -devices                                                                                                                                                                                                           1 
Devices:
 D. = Demuxing supported
 .E = Muxing supported
 --
 DE alsa            ALSA audio output
  E caca            caca (color ASCII art) output device
 DE decklink        Blackmagic DeckLink output
 DE fbdev           Linux framebuffer
 D  iec61883        libiec61883 (new DV1394) A/V input device
 D  jack            JACK Audio Connection Kit
 D  kmsgrab         KMS screen capture
 D  lavfi           Libavfilter virtual input device
 D  libcdio          
 D  libdc1394       dc1394 v.2 A/V grab
 D  openal          OpenAL audio capture device
  E opengl          OpenGL output
 DE oss             OSS (Open Sound System) playback
 DE pulse           Pulse audio output
  E sdl,sdl2        SDL2 output device
 DE sndio           sndio audio playback
 DE video4linux2,v4l2 Video4Linux2 output device
 D  x11grab         X11 screen capture, using XCB
  E xv              XV (XVideo) output device
```

Building this with `linux64 nonfree`:
```bash
$ ./ffplay -hide_banner -devices
Devices:
 D. = Demuxing supported
 .E = Muxing supported
 --
 DE fbdev           Linux framebuffer
 D  kmsgrab         KMS screen capture
 D  lavfi           Libavfilter virtual input device
 DE oss             OSS (Open Sound System) playback
  E sdl,sdl2        SDL2 output device
 DE video4linux2,v4l2 Video4Linux2 output device
 D  x11grab         X11 screen capture, using XCB
  E xv              XV (XVideo) output device
```

**Comment by BtbN** [comment]
Statically linked SDL/X11 might not work well at all.
It's added as pretty much an experiment, and I'm not sure how to fix it.

**Comment by BtbN** [comment]
Yeah, looking some more at it, SDL is entirely incompatible with statically linking X11.
It does not use pkg-config, which would be pretty much a hard requirement to successfully link against all the static libs.

For whatever weird reason, configure does not decide to abort, even if you pass --with-x and --enable-video-x11. Despite failing to enable it.
Even manually injecting the dependent libs fails, because it puts them in front of the libs it adds, so linking still fails.

I'm not seeing myself patch SDL to behave here, so it's probably gonna stay broken.

**Comment by teocci** [comment]
Probably you can try to `--enable-x11-shared`. This will actually make SDL2 link in that dependency at run-time. And not link against X11 `.so` dependencies.

```console
./configure \
        --enable-x11-shared \
        --enable-video-x11 \
```

**Comment by BtbN** [comment]
It's not that easy really.
configure will still try to link against all the various X11 libraries manually, to test if they exist, even if you pass that.
And that fails the exact same way, so it concludes that X11 is not available, and disables it without throwing an error or even a warning.

**Comment by BtbN** [comment]
Ok, I _think_ I finally figured this out.
And with a lot of trickery managed to make it work.
vaapi also might work now, but I'm not able to test that myself.

Please report back if it works with the latest build.

**Comment by teocci** [comment]
can you tell me the commit where did you apply this fix?

**Comment by teocci** [comment]
> Ok, I _think_ I finally figured this out. And with a lot of trickery managed to make it work. vaapi also might work now, but I'm not able to test that myself.
> 
> Please report back if it works with the latest build.

It works, how u did? it is perfect `ffplay` now works~

**Comment by BtbN** [comment]
See https://github.com/BtbN/FFmpeg-Builds/commit/1fcefa4a089d24868ff51fb88ed83112c22afaa3 and https://github.com/BtbN/FFmpeg-Builds/commit/c6b1f3a4392f63689e4252a61f898c7bdd7437cc

Closing this here then, since I've heard from multiple people that it works fine now!

**Comment by ValZapod** [comment]
Thanks for fixing that, I also had this problem on Linux, but did not report it :)
