### ISSUE TITLE
32bit builds release

### ISSUE THREAD

**Issue by emcodem** [BtbN/FFmpeg-Builds#12]
Thanks for doing this efforts!
Could you add 32bit builds for release versions - please?

**Comment by BtbN** [comment]
The builds are already very limited on asset space, and given the very limited usefulness of 32bit builds in 2020, I have no plans on adding any 32bit autobuilds.
You can however run the build-scripts yourself to produce 32bit builds if you for some reason really need them, though keep in mind that a lot of features are missing (no hand-written 32bit assembly, dependencies having dropped 32bit support) and performance will be poor.

**Comment by emcodem** [comment]
Dear BtbN, of course everyone can build ffmpeg whenever they like from source but i was under the impression that you might want to step in and replace zeranoe. Obviously you are not, anyway, thanks for the very quick answer!

**Comment by BtbN** [comment]
See readme of this very script.
You can build a fully static win32 ffmpeg with it, if you are okay with the drawbacks that come with it.
There just are no resources to so, and the very limited use of it does not make it worth sacrificing other variants for it.

**Comment by footballs** [comment]
> Very limited use of it does not make it worth sacrificing other variants for it.
@BtbN are you sure ? There are a lot of 32 bit users.
Please clear me if I am wrong.

**Comment by BtbN** [comment]
Virtually every x86 system and CPU sold in the last almost 20 years supports 64bit instructions.
There were a few weird exceptions, but those systems were so vastly underpowered and low end, that running ffmpeg on it is very questionable in itself.

There are a few odd niche cases where one might still need 32bit, but they are rare and not worth to remove other build variants for.

**Comment by emcodem** [comment]
Hm, i see your arguments are correct BtbN, but i can tell you that alone the fact that more than half of our 2.500 clients here are running on a 32bit OS. I guess the IT provider is able to save some coins that way. 
Theoretically i am with you, 32bit should not exist since a long time but even if the normal Office clients would have been updated, we still would need to deal with all the upcoming new "micro" boards like rockPi and such. 
In the end i feel that 32bit will haunt us for a veeeery long time :(

**Comment by BtbN** [comment]
32bit on non-x86 archs is a whole other story, but the builds are only for x86 Windows so far.
32bit vs. 64bit Windows isn't even a cost argument. It costs not a cent more, and in fact every license is valid for both variants.
If any supplier gave me a 32bit Windows on 64 bit Hardware today, I'd probably return that as defective.

The scripts are set up to build 32 bit builds, it's just not part of the autobuilds. So if you really need a 32bit build, it's easy enough to make yourself.

**Comment by emcodem** [comment]
Well, i said i am with you that it would be a good idea to switch to 64 bit, but thats not in my hands. 
So i suggest lets just see and wait if others request 32bit support. 
And by the way sorry for being not clear enough about Rock Pi, i actually wanted to refer to Rock pi X which is a standard X86 Cpu. The fact that they build such micro systems at the current time does make me wonder if we ever get rid of 32bit at all...
