### ISSUE TITLE
AAC encoding speed halved since 2021-05-31 N102631 (windows build)

### ISSUE THREAD

**Issue by YellowSM** [BtbN/FFmpeg-Builds#122]
On previous build (2021-04-03 N102186) AAC encoding speed is normal. But on the next build (N102631) the speed drops by half.
And this "bug" goes all the way to the latest build  (2021-12-22).

The 4.4 builds haven't this bug. (but there is another bug - incorrect setting of the `forced` attribute with `-disposition` option for mp4 at least)

**Comment by BtbN** [comment]
It's unlikely either of that is caused by these builds.
So you should report to upstream ffmpeg instead.

You should also specify which aac encoder you're using.

**Comment by GyanD** [comment]
The default coder in the native AAC encoder was changed to twoloop from fast in May.

Add `-aac_coder fast`.

**Comment by YellowSM** [comment]
Thank You GyanD!
You helped a lot.

**Comment by ValZapod** [comment]
> You helped a lot.

He fogot to mentioned that fast is complete garbage and that is like not even conparing to Apple encoder. Always use twoloop.

**Comment by ValZapod** [comment]
Please use https://github.com/nu774/qaac after installing Apple Cloud app on windows. It works better though also gapless just like FFmpeg's encoder.
