### ISSUE TITLE
What Are You Using To Build FFMPEG???

### ISSUE THREAD

**Issue by CanadianJeff** [BtbN/FFmpeg-Builds#123]
What OS?
What Build Env?

I'm looking to build at this "EXACT" commit but have everything enabled all demuxers all codecs etc everything....
https://github.com/FFmpeg/FFmpeg/commit/fe95a37144077d1f652088fcb25b2949e4a3da19

trying to use it with Audacity For Windows 64bit

**Comment by BtbN** [comment]
I'm not sure I understand what you're asking? The docker images and Dockerfiles used to build them are all in the images directory of this very repository.
It's based on Ubuntu 21.10, but the base os is mostly irrelevant anyway.

**Comment by CanadianJeff** [comment]
like what dependencies are required to actual build the thing

**Comment by BtbN** [comment]
To use this set of scripts you mean?
bash and docker.

See scripts.d for all the available ffmpeg dependencies.

**Comment by CanadianJeff** [comment]
Am I able to have it build at that exact commit of FFmpeg and somehow `./configure --enable-all` ????

**Comment by BtbN** [comment]
It's very unlikely --enable-all is going to work.
Modifying build.sh to checkout a specific commit before building should be fairly simple. Literally just add git checkout after git clone.

**Comment by CanadianJeff** [comment]
`git checkout fe95a37144077d1f652088fcb25b2949e4a3da19`

**Comment by ValZapod** [comment]
Nothing. Github cloud is building it.

**Comment by CanadianJeff** [comment]
is it maybe possible to see which demuxers your auto builds are missing and not enabled? maybe they are not enabled because they are not gpl / lgpl compliant?

**Comment by BtbN** [comment]
Not easily, but I'd assume it's the vast majority of them.
If you want to find out exactly, you'll have to grep the ffmpeg code for all possible demuxers, and compare it what the ffmpeg binaries here list.

**Comment by CanadianJeff** [comment]
its just funny that your ffmpeg build contains SOL (Sierra SOL) which is for old MS DOS games but not MOD which is used in games like Unreal Tournament 99

kinda curious why you would leave out so many codecs and demuxers in your build is that to save space or as mentioned not gpl / lgpl codecs

VLC media player for example will play MOD files just fine and VLC is a pretty big project

**Comment by BtbN** [comment]
What do you mean, "leave out so many codecs and demuxers"?
This build is close to 100MB binary size, it's the opposite of leaving stuff out.
Anything that's not outrageously huge of a dependency is or can be included if someone requests it.

**Comment by BtbN** [comment]
These builds have support for playing mod files via libopenmpt just fine.
Just confirmed by downloading a random file (https://api.modarchive.org/downloads.php?moduleid=179345#unatco_music.umx) and playing it with ffplay successfully.
So I blame Audacity for that.

**Comment by CanadianJeff** [comment]
I blame Audacity for alot of things......... they dont want to support ffmpeg 59 because its not released yet but thats a whole other can of worms..........

**Comment by CanadianJeff** [comment]
maybe just this specific build does not??????

![cmd_ANRuia6kye.png](https://i.imgur.com/9gg0zsz.png)

**Comment by BtbN** [comment]
That's a really old build, from long before openmpt was added.

**Comment by CanadianJeff** [comment]
ok ya this is a "let me stick my middle finger up Audacity's ........... " (long beep.wav)

**Comment by BtbN** [comment]
I fail to see how that's related to audacity. Just download a more up to date build?

**Comment by CanadianJeff** [comment]
one of your builds??????? did you not see that I tried that and audacity was like....... nope we dont like ffmpeg 59

**Comment by BtbN** [comment]
Download 4.4 then.

**Comment by CanadianJeff** [comment]
feel free to comment on this

https://opensource.stackexchange.com/questions/12505/gplv3-restricting-end-user

**Comment by ValZapod** [comment]
Audacity merged 4.4 ffmpeg support patch recently, i commented on it.

**Comment by BtbN** [comment]
4.4 is lavc soname 58.
5.0/current master is 59.

**Comment by ValZapod** [comment]
5.0 should be supported too...

**Comment by BtbN** [comment]
If 4.4 support was just recently merged, that's highly unlikely.

**Comment by CanadianJeff** [comment]
could I just pay you or someone a bunch of money to basically just build me a copy of ffmpeg with all the codecs and formats available using the commit I talked about in the OP because it is basically the last commit that will work with Audacity

**Comment by BtbN** [comment]
That makes no sense. Audacity claims to support FFmpeg 4.4, and there's downloads for that in the releases of this very repository.

**Comment by CanadianJeff** [comment]
FFmpeg 4.4 is AVformat 58? or 59? sorry thats the part I am lost on

**Comment by BtbN** [comment]
Just download the archive and check, can't tell you at the top of my 
head either.

**Comment by CanadianJeff** [comment]
on FFmpeg's website...........

April 8th, 2021, FFmpeg 4.4 "Rao"

the commit I posted in the OP was Apr 27 2021 a couple days after 4.4

**Comment by CanadianJeff** [comment]
also for the record they have even been testing removing version checks with 0 success

https://github.com/LWinterberg/audacity/actions/runs/1670996747

**Comment by CanadianJeff** [comment]
I tried using LWinterberg's stupid version that tried to remove the version checks and attempted to load in ANY of your builds after Apr 27 2021 and none of them worked
