### ISSUE TITLE
Auto-Build 2022-01-01 21:40 can't crop

### ISSUE THREAD

**Issue by kli2013** [BtbN/FFmpeg-Builds#124]
-c:v libx264 -vf crop=
Auto-Build 2022-01-01 21:40 can't crop

Auto-Build 2021-12-31 12:20 worked

**Comment by BtbN** [comment]
You should report that to upstream ffmpeg.
It's very unlikely that these builds randomly break the crop filter.
Your commandline is also incomplete.
