### ISSUE TITLE
MSYS2 Install Docker

### ISSUE THREAD

**Issue by ITSweets** [BtbN/FFmpeg-Builds#125]
Hello, I would like to ask. How to install docker in MSYS2? I try pacman -Ss docker prompt target not found? Please advise

**Comment by BtbN** [comment]
Download it from the Docker Website and run the installer.
Docker only works on Linux, so for it to work on Windows, you need either WSL2 or it'll install a Linux VM in HyperV during install.

**Comment by ITSweets** [comment]
Thanks for your reply, I have another question. It is how to modify the name of the compiled dll, for example: avcodec-59.dll is changed to libavcodec.dll The names of these dll and lib files are defined in those files?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BtbN/FFmpeg-Builds"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月7日(星期五) 晚上9:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BtbN/FFmpeg-Builds] MSYS2 Install Docker (Issue #125)





 
Download it from the Docker Website and run the installer.
 Docker only works on Linux, so for it to work on Windows, you need either WSL2 or it'll install a Linux VM in HyperV during install.
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by BtbN** [comment]
Not sure what you mean?
The version number is essential, if that number changes, binary compatibility was broken, you can't just change it and expect things to work.

**Comment by ITSweets** [comment]
Well, I mean how to modify the dll name, because the style of dynamic library under linux is named libxxx.so . I wonder if you can help me build one easily. Change all disables to enable in your build configuration, e.g. --disable x265 to --enable x265 . It's just too much wrong to compile it myself, because I'm in China, and accessing git, cloning is super slow, and it fails every time. Very distressed.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BtbN/FFmpeg-Builds"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月8日(星期六) 上午9:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BtbN/FFmpeg-Builds] MSYS2 Install Docker (Issue #125)





 
Not sure what you mean?
 The version number is essential, if that number changes, binary compatibility was broken, you can't just change it and expect things to work.
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by BtbN** [comment]
On Linux, the libraries name is libavcodec.so.59. The number means the exact same thing there.
If you're just looking for the import library to link against, it's in the lib dir of the shared archives.
