### ISSUE TITLE
Unable to load DLL 'avutil.56'

### ISSUE THREAD

**Issue by srht** [BtbN/FFmpeg-Builds#126]
I'm trying to use the library in asp.net web application that runs with .net framework 4.7.2. I set FFmpegLoader.FFmpegPath to the dll files that I downloaded win64 modes from https://github.com/BtbN/FFmpeg-Builds/releases  My application is 64 bit. Then it gives Unable to load DLL 'avutil.56' error. How can I solve this?

**Comment by BtbN** [comment]
avutil 56 is an older release.
If 4.4 is still too recent, you'll need to update your application to support the latest versions ABI.
