### ISSUE TITLE
Win32 builds

### ISSUE THREAD

**Issue by apacker1** [BtbN/FFmpeg-Builds#127]
Hi, I was trying to make a win32 build and I got an error message.  When I do "./build.sh win32 lgpl-shared 4.4", the error message is "docker: Error response from daemon: Head "https://ghcr.io/v2/btbn/ffmpeg-builds/win32-lgpl-shared-4.4/manifests/latest": denied."  I get a similar error message on other win32 variants.  Is the win32 build still supported?  I think I have my environment set up OK because I was able to do a win64 build just fine.  Thanks!

**Comment by BtbN** [comment]
You have to make the image first, since there are no pre-builts for win32.

**Comment by apacker1** [comment]
Doh!  Thanks for the prompt reply - that fixed it.  And thanks a lot for giving us this build process - it's very nice!
