### ISSUE TITLE
Feature request: periodic debug builds

### ISSUE THREAD

**Issue by SkyLined** [BtbN/FFmpeg-Builds#128]
Hey,

I found a crash in ffmpeg and I want to debug it to file a proper bug report. However, I do not have time to create a debug release to properly analyze it. I am hoping you can add a periodic debug release so I can download a reasonably recent version and analyze the crash.

Cheers,

**Comment by BtbN** [comment]
You can produce a debug build yourself, there's an addin for them you can just add to the end of the build/makeimage commands.
Those builds are simply so large that they entirely exhaust the asset space Github grants you, so they cannot be built and released via GHA.
Like, a single zip/tar archive of those easily is 300~400MB, and 10+ of those is very much too much.

**Comment by SkyLined** [comment]
Please note that I mentioned I cannot create a debug build myself for lack of time. I am sure it's a 5 minute job if you've got a setup ready. But I do not have a build environment set up, nor experience setting one up, nor time to learn how and do that. I do not even have a Linux machine available at the moment.

There is no need to keep 10 debug builds; one will suffice. When I said periodic, I meant that it should be rebuild periodically. The new build can replace the old one. , That way anyone can always debug a pretty recent build and create a proper bug report without the speed-bump that is setting up a build environment.

Please reconsider, I would like to contribute bug reports to ffmpeg but without a debug build, I simply cannot report a crash with unknown cause triggered by a 1Gb media file that I cannot share for privacy reasons.

**Comment by BtbN** [comment]
> Please note that I mentioned I cannot create a debug build myself for lack of time. I am sure it's a 5 minute job if you've got a setup ready. But I do not have a build environment set up, nor experience setting one up, nor time to learn how and do that. I do not even have a Linux machine available at the moment.

This repo provides you all the setup you need.
Just need bash and docker, then run makeimage, followed by build, and wait.

> There is no need to keep 10 debug builds; one will suffice. When I said periodic, I meant that it should be rebuild periodically. The new build can replace the old one. , That way anyone can always debug a pretty recent build and create a proper bug report without the speed-bump that is setting up a build environment.

I don't think you understand the issue. It's not about the amount of releases.
It's about the asset storage, which is very limited, and already over 75% used up by a normal build. A debug build simply does not fit.

**Comment by ValZapod** [comment]
> Just need bash and docker, then run makeimage, followed by build, and wait.
> 
> >

You can just fork the repo, like I did.

**Comment by BtbN** [comment]
You will still exhaust the asset space limit, fork or not.

**Comment by ValZapod** [comment]
> You will still exhaust the asset space limit, fork or not.

What I meant you do not need bash or docker or PC at all.

**Comment by BtbN** [comment]
You literally cannot produce a debug build on Github Actions. It's simply too large and will exhaust the 2GB Asset limit easily.
