### ISSUE TITLE
"Latest" Release and release retention policy

### ISSUE THREAD

**Issue by dtugend** [BtbN/FFmpeg-Builds#129]
If I understand right "Latest" release build will get pruned upon each release:
https://github.com/BtbN/FFmpeg-Builds/blob/master/util/prunetags.sh

However it also happens to be the last "Build" of the last month.

Retention Policy says
"The last build of each month is kept for two years."

I see a conflict here.

**Comment by zhongfly** [comment]
https://github.com/BtbN/FFmpeg-Builds/blob/master/util/prunetags.sh#L4
So it only do prune with tags like 'autobuild-2022-01-31-12-27'

**Comment by dtugend** [comment]
ah yes sorry you are right, [the latest tag is updated somewhere else](https://github.com/BtbN/FFmpeg-Builds/blob/master/.github/workflows/build.yml#L182), but still it's confusing when the latest build
but the problem I am worried about is still the same.

**Comment by dtugend** [comment]
The thing is I compared the files of "Latest" latest build and the auto build from that day.
They are different.
From the code it seems like the autobuild will be kept and not the "Latest" latest build of January.

**Comment by dtugend** [comment]
Another thing that's contradicting is it only keeps 12, which is less than 2 years
https://github.com/BtbN/FFmpeg-Builds/blob/c8d2ea0cb6bbdb06cb92cda7f1fc90150688067e/util/prunetags.sh#L7

**Comment by zhongfly** [comment]
> Another thing that's contradicting is it only keeps 12, which is less than 2 years
> 
> https://github.com/BtbN/FFmpeg-Builds/blob/c8d2ea0cb6bbdb06cb92cda7f1fc90150688067e/util/prunetags.sh#L7

BtbN may have forgotten to modify it, it is a typo

**Comment by dtugend** [comment]
I am sorry if it came accross as me complaining, I am thankful for the free voluntary work done by BtbN and others.
I just wanted to point out, it might be an issue for some people that take things written for granted :)

I will try to make a small pull request that addresses both.

**Comment by BtbN** [comment]
> The thing is I compared the files of "Latest" latest build and the auto build from that day. They are different.

They're different archives with the same files in there. If you compare the actual files, they should be the same.
The "latest" tag is a floating tag that always contains the latest release, so that the links stay consistent. It's otherwise uninvolved with the rotation of releases.

And the 12/24 thing is a typo, I'm not entirely sure which one is the intended one anymore.

**Comment by dtugend** [comment]
Thank you for your reply. I replied in the pull request, as said there I almost used the file URLs of the "latest" "last build" instead of the "autobuild" ones, which would break the checksums / downloads in the HLAE_Setup.exe installer that can install ffmpeg at user's request by tomorrow already. But maybe it's just me being stupid :D

Please do as you prefer / please, I don't mind if it's rejected if it's not the way you want :)

**Comment by BtbN** [comment]
I specifically created that floating "latest" release because people of various auto-install-tools complained about the lack of a consistent URL.
Its whole idea is to prevent people posting links in places that then are gone a few weeks/months later.

**Comment by dtugend** [comment]
Yes I understand that's what's needed by many.
I personally put checksums for each release we use (in lack of digital signatures), so the latest one is a bit complicated for that.
I saw you already fixed the rentention. Thank you :-)
