### ISSUE TITLE
Add decklink support

### ISSUE THREAD

**Issue by SoftwareMagicIT** [BtbN/FFmpeg-Builds#13]
Is possible to add decklink support for cards like blackmagic I/O?

**Comment by BtbN** [comment]
The decklink SDK is nonfree, so a build with it cannot be redistributed.

**Comment by AnimMouse** [comment]
My builds [ffmpeg-autobuild](https://github.com/AnimMouse/ffmpeg-autobuild) includes decklink support.

**Comment by SoftwareMagicIT** [comment]
@AnimMouse thank you.
