### ISSUE TITLE
Please ADD Nvidia CUDA hwaccel h264_nvenc

### ISSUE THREAD

**Issue by BestNoob** [BtbN/FFmpeg-Builds#132]
At the moment the codecs/encoder/decoder in ffmpeg support CUDA but not full hardware sided, i think there a lot more benefits by adding this to the package, would be great if you do.

https://docs.nvidia.com/video-technologies/video-codec-sdk/ffmpeg-with-nvidia-gpu/

**Comment by BtbN** [comment]
nvenc and nvdec are fully supported by these builds. Not sure what else you think it missing?

**Comment by BestNoob** [comment]
Hmm i had one movie where the progress was taking 50 minutes .... also quality optimization seems to be better with hwaccel. I really struggled with the command line argues xD

or maybe i did smth wrong with the commandline arguments but the .mp4 video is lagging (doesnt look smooth) and also more pixels than original .VOB files:

ffmpeg -i VTS_01_1.VOB -i VTS_01_2.VOB -i VTS_01_3.VOB -map 0:v:0 -map 0:a:1 -c copy -c:v h264_nvenc output.mp4

**Comment by ValZapod** [comment]
> -c copy

Remove this or use -c:a copy. You cannot use it with reencoding.

**Comment by BtbN** [comment]
> > -c copy
> 
> Remove this or use -c:a copy. You cannot use it with reencoding.

The later and more specific -c:v takes precedence, so that statement is wrong.
