### ISSUE TITLE
Please create a simple GUI for it

### ISSUE THREAD

**Issue by BestNoob** [BtbN/FFmpeg-Builds#133]
I recognized that there often some things removed, edited or changed so older GUI and Programs doesnt work correctly with new ffmpeg versions. In the end all programs also the ones u have to pay for use ffmpeg.

It would be great when you guys create a simple GUI for it that dynamicly list up all aviable commands/paremeters depending to codec and the other options. 

I tried it myself the past 2 days via CMD but i had a lot issues to find good settings.

**Comment by BtbN** [comment]
That's VERY much out of the scope of these build scripts.
If you want a GUI that exposes most libav* features, you should take a look at Handbrake.

**Comment by BtbN** [comment]
You're welcome to write or sponsor one, but it's really not at all something this set of build scripts can in any way cover.
