### ISSUE TITLE
Enable vapoursynth support

### ISSUE THREAD

**Issue by iamtherobin** [BtbN/FFmpeg-Builds#134]
Could you please add vapoursynth support to your builds using --enable-vapoursynth?

https://ffmpeg.org/general.html#VapourSynth

**Comment by BtbN** [comment]
Isn't that the same as avisynth, which is already supported?

**Comment by iamtherobin** [comment]
Vapoursynth is a modern alternative to avisynth and support needs to be enabled with a separate flag. It would be nice to encode my scripts directly without having to pipe all the time to ffmpeg.

**Comment by BtbN** [comment]
Looking at the vapoursynth github repo, I unfortunately see no remotely sane way to package this so it works as a static dependency for these builds.
Like, ffmpeg wants to directly link to it, it does not dynamically load it at runtime like it does with avisynth. So I'd have to link an entire static python interpreter into ffmpeg, and a whole bunch of other stuff.

Sorry, but that's a library which does not at all play nicely with static linking, unless I'm missing some trick they have to link it statically in a sane way.

**Comment by iamtherobin** [comment]
Well, I don't know anything about compiling binaries, but there is a build with vapoursynth here: https://jeremylee.sh/bins/

Perhaps there is some info there that might help?

**Comment by BtbN** [comment]
That seems to be patching in a whole other vapoursynth something, not sure what's up with that:
https://raw.githubusercontent.com/m-ab-s/mabs-patches/master/ffmpeg/0001-Add-Alternative-VapourSynth-demuxer.patch

But I'm following a strict policy of not patching upstream ffmpeg with these builds, so something like that is out of the question.

It also seems to in fact do drag an entire Python-Interpreter along and link it statically into ffmpeg.
That'd inflate the binary size considerably, so I'm still not too keen on doing that.

Another issue seems to be that VapourSynth only supports being built with MSVC on Windows, and in turn also needs an MSVC built Python. Meaning I can't compile them no matter what.

Yeah, sorry, but there is just too many issues with VapourSynth. The only way to ever add support would be if it worked the same AviSynth does, where ffmpeg just needs the headers, and then dynamically loads it at runtime.

**Comment by hydra3333** [comment]
Hello.  

Yes, I regularly cross-compile a static ffmpeg with vapoursynth for windows, under ubuntu, regularly (it was scripted by someone else, so I never look at it).

A quick look says it is a hassle to build and not fully static - with this method it dynamically loads vapoursynth; one has to put the built ffmpeg exe into the same windows folder as the correct versions of the extracted "portable" vapoursynth and the extracted portable python 3 and run ffmpeg.exe from there.

A hassle for the user, but doable and I rely on it.

Can't recall offhand, is that similar to avisynth or is that fully static build into ffmpeg ?

**Comment by BtbN** [comment]
No, the difference is that ffmpeg links directly against vapursynth, but does not with avisynth.
So it'd force every user who wants to use the builds to grab a copy of vapursynth before the binaries will run at all, even if that user has no intention of ever using vapoursynth.

**Comment by hydra3333** [comment]
Ah, I guessed so.
Not a very handy result :)

**Comment by BtbN** [comment]
Unfortunately I don't see this happening, so I'm closing this here.
Feel free to reopen/create a new issue if you think you found a way around the issue.
