### ISSUE TITLE
Nullsoft installers (or MSI) + winget

### ISSUE THREAD

**Issue by DanTheMan827** [BtbN/FFmpeg-Builds#135]
It would be very convenient if this could be packaged inside an installer and automatically submitted to the winget package repository at [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs/)

I've found this post detailing how you can automatically submit to winget https://www.dolthub.com/blog/2021-10-13-how-to-publish-winget-chocolatey-packages-with-github-actions/

**Comment by BtbN** [comment]
I don't really see how this could be sensibly put into an installer.
Windows has no standard paths or anything to put stuff into.

**Comment by garoto** [comment]
Just drop everything into `C:\Windows` and it should be fine.

**Comment by DanTheMan827** [comment]
Just install to program files and update the PATH environment variable

**Comment by BtbN** [comment]
I don't think an installer is a good idea as it gives the wrong idea to users about there being any sort of official location/build/path for ffmpeg.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@DanTheMan827, most users are hesitant or unable to perform those operations, and @BtbN, standard paths for installation definitely exist. These are usually "file:///%SystemDrive%/Program%20Files" and, for user-specific files, %AppData%.

**Comment by DanTheMan827** [comment]
@BEEDELLROKEJULIANLOCKHART @garoto  I wasn't suggesting anything because it was "official", but merely because winget as a package manager just makes it easier for people to re-install software after a format or just keep it up to date.

There's a couple projects with multiple variants in winget maintained by different teams and they're just differentiated by their designation.

BtbN.FFmpeg would be the one for this project if there were installers available, but that wouldn't make it the _official_ ffmpeg, just your build of it.
