### ISSUE TITLE
BtbN release build vs. ffmpeg commit

### ISSUE THREAD

**Issue by jozefchutka** [BtbN/FFmpeg-Builds#140]
Hi,

sometimes I find myself verifying a particular [ffmpeg commit](https://github.com/FFmpeg/FFmpeg/commits/master) has fixed a reported particular ffmpeg issue. I am considering using BtbN builds to check. However, I am having hard times to determine ffmpeg commit from BtbN release. Lets say I have just downloaded [ffmpeg-N-105930-ga71a3d1ed2-win64-lgpl.zip](https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2022-03-14-12-32/ffmpeg-N-105930-ga71a3d1ed2-win64-lgpl.zip)

running it produces following banner:

```
ffmpeg version N-105930-ga71a3d1ed2-20220314 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11.2.0 (crosstool-NG 1.24.0.533_681aaef)
```

but `ga71a3d1ed2` does not seem to match any [ffmpeg commit](https://github.com/FFmpeg/FFmpeg/search?q=ga71a3d1ed2&type=commits). 

Compared to https://www.gyan.dev/ builds, for example:

```
ffmpeg version 2022-01-24-git-0a83ecbf48-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11.2.0 (Rev7, Built by MSYS2 project)
```

[0a83ecbf48 references a commit](https://github.com/FFmpeg/FFmpeg/search?q=0a83ecbf48&type=commits)

Would it be possible to include ffmpeg commit hash info into "latest" builds or is there any option already in place to resolve it somehow?

**Comment by nanake** [comment]
you want to omit the `g`. the `g` means `git`.

it's actually commit a71a3d1ed2.

**Comment by nanake** [comment]
> Compared to https://www.gyan.dev/ builds, for example:

he uses shallow clone that why itsn't prefix with g. https://github.com/FFmpeg/FFmpeg/blob/master/ffbuild/version.sh#L14

**Comment by jozefchutka** [comment]
perfect, thanks @nanake
