### ISSUE TITLE
AMF script fails

### ISSUE THREAD

**Issue by wabberz** [BtbN/FFmpeg-Builds#141]
I'm trying to make the image targeting `linux64` with the `nonfree` variant, everything seems to go fine (as usual, I just did this half a month ago on the same machine), but then it fails with `50-amf.sh`:

```
 => => # + echo 'Retry 7...'
 => => # + [[ 7 -lt 15 ]]
 => => # + timeout 120 git -C amf fetch --depth=1 origin 06b0e29a372b0c491f87ff285ca92be2844dc039
 => => # Retry 7...
 => => # fetch-pack: unexpected disconnect while reading sideband packet
 => => # fatal: fetch-pack: invalid index-pack output
```

I thought this may be a github issue and tried again from scratch after a few hours. Everything goes fine until it hits this script, again. Changing some memory or cache limits for git didn't help either, nor using the latest commit instead of the one hardcoded in the script.

**Comment by BtbN** [comment]
Yeah, that's either an issue on Githubs end, or on your connection to Github/your Dockers network setup.

**Comment by wabberz** [comment]
It's a wired connection with no issues and like I said, all the other scripts run just fine.

**Comment by wabberz** [comment]
Making the timeout in `git-mini-clone.sh` longer "fixed" it. For some reason certain repos only clone at ~1MiB/s, other repos are faster. AMF is consistantly slow.

**Comment by BtbN** [comment]
I'm gonna close this here, since it seems like it was an intermittend issue with github, or your connection.
If it's still an ongoing issue, feel free to reopen.
