### ISSUE TITLE
How to encode video using VVC (H266 encoder) in ffmpeg ver 5.0

### ISSUE THREAD

**Issue by georgesaumen** [BtbN/FFmpeg-Builds#142]
Hello,

As I see, on a newest ver of ffmpeg, I see all codec that ffmpeg support I have see VVC encoder but I dont know how to use it for encoding my videos. I have try this command but it said unknown encoder vvc: ffmpeg -i bogia2021.mp4 -c:v vvc -c:a eac3 -b:v 8000 -b:a 640k demovideo.mp4

Can I know do this encoder VVC has already supported with ffmpeg ? If yes, can you give me a option for how to use or how to add that encoder to ffmpeg for work.

Thanks!

**Comment by ValZapod** [comment]
VVC is not yet supported, there is only bitstream reader patch (https://patchwork.ffmpeg.org/project/ffmpeg/list/?series=3487), which is far from encoder or decoder. Of course, you can just use vvc library and vvcenc, that is compiled by good people.

**Comment by georgesaumen** [comment]
Thanks for ur reply!

I still wait for vvc when is completed to use for encode, because I hear
someone said that this codec is very good and lower file size

Vào Th 3, 22 thg 3, 2022 lúc 18:17 Valerii Zapodovnikov <
***@***.***> đã viết:

**Comment by BtbN** [comment]
It'll also be patent encumbered to the point of uselessness, just the same as HEVC is.
In any case, this is not the right place to ask about that, since these issues are for issues with the builds specifically.
So I'm closing here.
When ffmpeg gains support for some vcc encoding/decoding library, it'll for sure be added.

**Comment by georgesaumen** [comment]
Cool, thanks!

Vào Th 3, 22 thg 3, 2022 lúc 18:31 BtbN ***@***.***> đã viết:
