### ISSUE TITLE
CSS files missing from the documentation

### ISSUE THREAD

**Issue by vlakoff** [BtbN/FFmpeg-Builds#146]
The three CSS files (namely `bootstrap.min.css`, `default.css` and `style.min.css`) are missing from the bundled documentation, thus the pages are completely unstyled.

**Comment by BtbN** [comment]
That is indeed an issue with the docs install Makefile.
Seems like nobody ever "make install"s the html docs.

But it's nothing I can fix with these builds, it needs to be fixed in upstream ffmpeg. I'll look into it, can't be a huge deal to fix.

**Comment by BtbN** [comment]
That won't make ffmpeg Makefiles install those files, no.

**Comment by vlakoff** [comment]
Indeed, it's redundant to make Doxygen copy these files if we still have to specify in a makefile to copy them.

Did you mean that the CSS files should be added to [`/doc/Makefile`](https://github.com/FFmpeg/FFmpeg/blob/master/doc/Makefile), or that this makefile isn't called in the workflow (so the doc is generated manually)?

**Comment by BtbN** [comment]
Patch for this is on the ML, nothing more that can be done here.

**Comment by ValZapod** [comment]
Applied: https://github.com/FFmpeg/FFmpeg/commit/d5687236aba6fd31dd4369c290df9a5b1192e43e
