### ISSUE TITLE
issue in installing ffmpeg with nv-codec-headers on centos 8 machine

### ISSUE THREAD

**Issue by saibha** [BtbN/FFmpeg-Builds#149]
Hi All,

I have CentOS Stream 8  vm which has 50 gb space and i have tried the below steps for installing ffmpeg on the the vm by following steps present in the link
https://developer.nvidia.com/blog/nvidia-ffmpeg-transcoding-guide/
1.Downloaded repository "https://git.ffmpeg.org/ffmpeg.git and cloned with 
git clone https://git.ffmpeg.org/ffmpeg.git"
2.Downaloded the nvidia driver for tesla T4 product and linux 64-bit RHEL 8
file name is "nvidia-driver-local-repo-rhel8-510.47.03-1.0-1.x86_64.rpm"
3.Downloaded the cuda tool kit for centos 8 system by running following commands

(I)wget https://developer.download.nvidia.com/compute/cuda/11.6.2/local_installers/cuda-repo-rhel8-11-6-local-11.6.2_510.47.03-1.x86_64.rpm
(II)sudo rpm -i cuda-repo-rhel8-11-6-local-11.6.2_510.47.03-1.x86_64.rpm
(III)sudo dnf clean all
(IV)sudo dnf -y module install nvidia-driver:latest-dkms
(V)sudo dnf -y install cuda

4.cloned the rep FFmpeg/nv-codec-headers
git clone https://github.com/FFmpeg/nv-codec-headers.git

5.After completion of ffmpeg/nv-codec-headers,i have entered to the nv-codec-headers
cd nv-codec-headers
6.i'm  getting below installation messages when i ran the "make install" command and kindly help me in resolving the issue
[root@localhost nv-codec-headers]# make install
sed 's#@@PREFIX@@#/usr/local#' ffnvcodec.pc.in > ffnvcodec.pc
install -m 0755 -d '/usr/local/include/ffnvcodec'
install -m 0644 include/ffnvcodec/*.h '/usr/local/include/ffnvcodec'
install -m 0755 -d '/usr/local/lib/pkgconfig'
install -m 0644 ffnvcodec.pc '/usr/local/lib/pkgconfig'

**Comment by BtbN** [comment]
The question is out of scope for this repo, since issues here are about these builds, not generic ffmpeg issues.

As far as building ffmpeg is concerned, your steps 2 and 3 are entirely irrelevant. Building FFmpeg by default uses clang to compile .cu code, and otherwise does not interact with the driver or the CUDA sdk at all otherwise.

But what exactly is your issue? I don't see any issue or error in what you pasted.

**Comment by ValZapod** [comment]
With some helpers like this uses clang to compile .cu code, that compresses PTX/streaming assembly further https://github.com/FFmpeg/FFmpeg/commit/072788c46e36a21ca9e8f1e3cc19a1944db5b89c

**Comment by saibha** [comment]
Hi ,

I have CentOS Stream 8 vm and i have cloned the ffmpeg repo by the following command 
https://git.ffmpeg.org/ffmpeg.git 

and I ran the below command and i have got an error  after execution of the command 

./configure --enable-cuda --enable-cuvid --enable-nvdec --enable-nvenc --enable-nonfree --enable-libnpp --extra-cflags=-I/usr/local/cuda/include  --extra-ldflags=-L/usr/local/cuda/lib64 --disable-x86asm

below is the error i have got ,can u please help us in fixing the issue 

ERROR: libnpp not found

[config.log](https://github.com/BtbN/FFmpeg-Builds/files/8526968/config.log)

**Comment by ValZapod** [comment]
> ERROR: libnpp not found

That cannot be used without nonfree and thus without Nvidia SDK on Debian. I recomment disabling enable-nonfree for now and compiling everything from nvidia that is "free" with clang. That is most of it, cuda, nvdec, nvenc, etc. Everything escept libnpp.
