### ISSUE TITLE
The question is out of scope for this repo, since issues here are about these builds, not generic ffmpeg issues.

### ISSUE THREAD

**Issue by saibha** [BtbN/FFmpeg-Builds#150]
The question is out of scope for this repo, since issues here are about these builds, not generic ffmpeg issues.

As far as building ffmpeg is concerned, your steps 2 and 3 are entirely irrelevant. Building FFmpeg by default uses clang to compile .cu code, and otherwise does not interact with the driver or the CUDA sdk at all otherwise.

But what exactly is your issue? I don't see any issue or error in what you pasted.

_Originally posted by @BtbN in https://github.com/BtbN/FFmpeg-Builds/issues/149#issuecomment-1101389854_

**Comment by ValZapod** [comment]
It is illegal according to USA law to beuild wih nonfree.
