### ISSUE TITLE
support svtav1-params in libsvtav1

### ISSUE THREAD

**Issue by aliofwind** [BtbN/FFmpeg-Builds#153]
SVT-AV1 offcial compiled FFmpeg supports this option since libsvtav1 0.9.1
`-svtav1-params     <dictionary> E..V....... Set the SVT-AV1 configuration using a :-separated list of key=value parameters`

**Comment by BtbN** [comment]
Not sure I understand?
I just updated to latest svt-av1 a few days ago, and it's always 
building latest ffmpeg.
So if ffmpeg supports that option, it should be available.

Make sure to download a master build, not some old release. It's 
unlikely such an option would get backported.

**Comment by aliofwind** [comment]
thanks, the latest version supports it, but I need to wait for the next release of ffmpeg

**Comment by BtbN** [comment]
You can just use latest master.
There is no practical reason to limit yourself to an outdated release 
version.

**Comment by aliofwind** [comment]
My work project requires stable components, and I need to provide component versions, so the latest version cannot be used

**Comment by BtbN** [comment]
That makes no sense, you're just missing out on potentially critical 
fixes that way.
The stable branch version you find here are not a specific version 
either, and just the latest version of the respective stable branch, to 
not artificially hold back fixes.

**Comment by aliofwind** [comment]
One of our project's upstream tools doesn't recognize ffmpeg versions that start with non-numbers, unfortunately we don't have the source code for this tool and can't make any changes, we just have to wait.
