### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by BakaJzon** [BtbN/FFmpeg-Builds#159]
Build base image
```
#13 [auth] bakajzon/ffmpeg-builds/base:pull,push token for ghcr.io
#13 DONE 0.0s
#12 exporting to image
#12 pushing layers 0.8s done
#12 ERROR: unexpected status: 403 Forbidden
------
 > exporting to image:
------
error: failed to solve: unexpected status: 403 Forbidden
Error: buildx failed with: error: failed to solve: unexpected status: 403 Forbidden
```

**Comment by BtbN** [comment]
Not really sure what to tell you. Do you not have packages enabled, or the security for the native token tuned too low?
It _should_ work out of the box, and does for a bunch of other forks.

**Comment by sudo-nautilus** [comment]
Try running it again

**Comment by rokibhasansagar** [comment]
In https://github.com/BakaJzon/FFmpeg-Builds/commit/77031ee009305c8baacec58648e5398af123f46f, you reverted from Container registry to the old Docker registry. This is Deprecated by GitHub.
This might be a case of the problem.

Or, it might be that GitHub is Capping your API Calls.

Anyways, make sure to check this: https://github.com/docker/build-push-action/issues/463#issuecomment-924995909

_I did not have to do anything once I forked this repo and made a few changes. It's working everyday from months now without any problem._

**Comment by BakaJzon** [comment]
@rokibhasansagar thanks a lot.It works!
😄
