### ISSUE TITLE
[Feature Request] Compile X265 with HDR10 plus support

### ISSUE THREAD

**Issue by cdgriffith** [BtbN/FFmpeg-Builds#16]
Would it be possible to enable HDR10+ support for x265?

 It requires the "ENABLE_HDR10_PLUS=ON" option to be set for x265 builds. I think just for 10 and 12 bit. ([x265 configure file](https://bitbucket.org/multicoreware/x265_git/src/master/source/CMakeLists.txt)) 

Thanks for the great automated builds!

**Comment by BtbN** [comment]
Do you happen to know if enabling that disables support for "normal" HDR? If not, I don't see any reason not to.
