### ISSUE TITLE
FFmpeg text not showing up

### ISSUE THREAD

**Issue by lNuggy** [BtbN/FFmpeg-Builds#166]
![image](https://user-images.githubusercontent.com/95617427/179424099-4914f6e5-d632-43d7-97bf-f1e3802a7d14.png) Text doesn't show up at all, but when selected and copy pasted it shows the content of the message. Not sure if this is a FFmpeg issue or just me.

https://user-images.githubusercontent.com/95617427/179424199-cbd1c815-fcde-410b-ad7d-2975a4c32918.mp4

**Comment by BtbN** [comment]
That seems like an issue with your terminal or environment.
Not much I can do about this.
Try the new Windows Terminal.
