### ISSUE TITLE
ffmpeg `5.1` is released

### ISSUE THREAD

**Issue by th1nk3r-ing** [BtbN/FFmpeg-Builds#167]
FFmpeg `5.1` "Riemann"  was released on 2022-07-22. 
It is recommended to use `5.1` instead of `5.0` .

**Comment by zhongfly** [comment]
Already https://github.com/BtbN/FFmpeg-Builds/commit/dfdfc2931193c9e21e5b410e91c69e4d1a825b23

**Comment by th1nk3r-ing** [comment]
Thanks~
