### ISSUE TITLE
is AMF Updated on this build?

### ISSUE THREAD

**Issue by nwgat** [BtbN/FFmpeg-Builds#168]
AMD has released new AMF source code lately that improves quality
https://github.com/GPUOpen-LibrariesAndSDKs/AMF/releases
https://codecalamity.com/amd-re-introduces-the-b-frame/

**Comment by TimoRoth** [comment]
https://github.com/BtbN/FFmpeg-Builds/blob/master/scripts.d/50-amf.sh

**Comment by nwgat** [comment]
oh nice
