### ISSUE TITLE
32 bits build possible?

### ISSUE THREAD

**Issue by superbonaci** [BtbN/FFmpeg-Builds#169]
Hi could be possible to have 32 bit builds for old Intel Atom cpus?

**Comment by BtbN** [comment]
Yes, win32 target exists and works.
Just follow the instructions in the readme with win32 as build target.

**Comment by superbonaci** [comment]
Sorry I meant pre-build binaries...

**Comment by BtbN** [comment]
There's not going to be windows/linux 32bit x86 builds for download here, no.
The list of releases is already enough of a mess, and it would needlessly confuse people who just want a windows build, which would then end up with an inferior and MUCH slower build.
There is also only limited asset space, and what's left is reserved for windows arm64 builds whenever I get around to figuring those out.

**Comment by superbonaci** [comment]
I got thanks.
