### ISSUE TITLE
README.md improvements

### ISSUE THREAD

**Issue by superbonaci** [BtbN/FFmpeg-Builds#170]
- The line `Available:` I think it should be `Available variants:`
- The `addins.` replaced by `addins:`
- Specify how many addins you can set, one two or the three.
- Also explain whether the `gpl` variant is the one "more complete" that has the most dependencies possible in the build, or if each variants has its own features exclusive per variant which the others don't have.

**Comment by BtbN** [comment]
The readme had a bunch of changes since this was opened, and I think most of this has been addressed?

**Comment by superbonaci** [comment]
No they haven't been addressed yet. I can't make a pull request since i don't really know how some of the features work, like addins number.
