### ISSUE TITLE
ffmpeg args 

### ISSUE THREAD

**Issue by Alice-Thirty** [BtbN/FFmpeg-Builds#178]
what is your command build with ffmpeg
enable or disable xxx

**Comment by BtbN** [comment]
It's part of the very first things the ffmpeg binary prints every time 
you invoke it.
It's quite a long line, and you can look at all the scripts for an idea 
of what's included directly.

**Comment by Alice-Thirty** [comment]
what is your build env on windows 10
Using mingw64?

**Comment by Alice-Thirty** [comment]
Do you meet the Creating library libavcodec/avcodec.lib and object libavcodec/avcodec.exp?
I keep the status word on terminal when building ffmpeg
Until I ctrl +c , it will be break

**Comment by BtbN** [comment]
I have no idea what you are asking exactly.
The build environment is an Ubuntu docker container, with latest gcc and mingw.

**Comment by Alice-Thirty** [comment]
LINK : libavcodec\avcodec-59.dll not found or not built by the last incremental link; performing full link
what is the library should I install?

**Comment by BtbN** [comment]
Again, I don't really understand what you're asking.
The shared release archives come with all the neccesary import libs (.dll.a) for you to link against them.
How to set that up in your development environment of choice, I cannot tell you.
