### ISSUE TITLE
static library (.lib) for windows

### ISSUE THREAD

**Issue by goodtogood** [BtbN/FFmpeg-Builds#179]
great job. would you like to release static library for windows?
thanks!

**Comment by BtbN** [comment]
That doesn't work unfortunately.
Those static libraries would be useless without the exact matching set of dozens of other static libraries from the build environment.
Plus, adding all those would inflate the size of the zip file by several hundred megabytes, which is not exactly workable.

If you need to link something statically yourself, you can grab the docker images and use them to build. They have all the static dependencies and build environment in them.

**Comment by goodtogood** [comment]
I see . thank you !
