### ISSUE TITLE
HOWTO  start

### ISSUE THREAD

**Issue by Alice-Thirty** [BtbN/FFmpeg-Builds#180]
https://trac.ffmpeg.org/wiki/CompilationGuide/MSVC
I can build it on windows.
If I also want to build these , how can I do on linux with your project
```
--enable-cuda-nvcc --enable-gpl --enable-libfreetype --enable-ffnvcodec --enable-cuvid --enable-nvdec --enable-nvenc --enable-shared --toolchain=msvc --arch=x86_64 --enable-cross-compile --target-os=win64
```

**Comment by BtbN** [comment]
There is no support for actual nvcc, since it makes the build non-free and non-redistributable.
But unless you are debugging a CUDA filter, there is no need for it and the default cuda-clang mode is fine.

For instructions on how to build, see the README. In the most simple case, all you need is a shell and docker, and you run build.sh with your desired target and variant.

**Comment by Alice-Thirty** [comment]
In fact, I alreay build ffmpeg on my docker .
And I want to build it for windows.
Do you have the command for cross-compiler windows?


I dont see like --enable-cross-compile parameter (I dont know does it need)

**Comment by BtbN** [comment]
Not sure what you mean. The configure script is able to figure out it's cross compiling on its own when it sees a mingw gcc on a Linux host.
If you want to use these set of scripts and images to make an ffmpeg build, you either have to use the supplied build script, or manually pull the image, launch a container and run the respective configure/make commands manually.
The exact configure invocation is pieced together from the various sources, so doing it manually is a pain and I'd recommend just invoking build.sh.

**Comment by Alice-Thirty** [comment]
invoking build.sh.
Do you have the total command  for cross-compiler

**Comment by BtbN** [comment]
You can see the final commandline for configure in the output of build.sh.
Any compiled ffmpeg binary will also print it as part of its info-header it prints on every invocation.
