### ISSUE TITLE
 nonfree build option give me   403 (Forbidden)

### ISSUE THREAD

**Issue by SalimF** [BtbN/FFmpeg-Builds#183]
I'm trying to build the `nonfree build` but I got an error message, this is part of build log. 

```
+ docker run --rm -v /root/FFmpeg-Builds-latest:/uidtestdir ghcr.io/btbn/ffmpeg-builds/linux64-nonfree:latest touch /uidtestdir/uidtestfile
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Trying to pull ghcr.io/btbn/ffmpeg-builds/linux64-nonfree:latest...
Error: initializing source docker://ghcr.io/btbn/ffmpeg-builds/linux64-nonfree:latest: Requesting bearer token: invalid status code from registry 403 (Forbidden)
```

I use this command to build 
`./build.sh linux64 nonfree`

I want none free build for `fdk-aac`

**Comment by BtbN** [comment]
There unsurprisingly are no pre-build images for nonfree.
So you have to make the respective image first as well, via the respective script for it.
