### ISSUE TITLE
Request: build with --enable-vapoursynth

### ISSUE THREAD

**Issue by mugiritsu** [BtbN/FFmpeg-Builds#188]
VapourSynth is the spiritual successor of AviSynth, which has been included in popular ffmpeg builds for years.

It can do more complex things than AviSynth/+ and is more reliable, optimized and modern. Also, it has a [huge community](https://github.com/vapoursynth/vapoursynth) and its development is very active.

It's pretty nice to have VapourSynth input in such a powerful tool as ffmpeg, but would be cool to have it enabled in these builds to easily share the binaries with friends and colleagues periodically.

**Comment by BtbN** [comment]
As explained in #134 it's impossible to add in any reasonable way.
