### ISSUE TITLE
Enable rubberband library

### ISSUE THREAD

**Issue by l00tzOMG** [BtbN/FFmpeg-Builds#19]
Would you be so kind to make builds with rubberband enabled, please?

**Comment by BtbN** [comment]
You mean https://breakfastquay.com/rubberband/ ?
That library appears to have quite a few dependencies, so adding it is far from trivial.
I'll see if I find time for it, but no promises.

**Comment by l00tzOMG** [comment]
Yes, thank you. Other, weekly only win builds from `gyan.dev` contain this, so you might get some inspiration from here as well: https://www.gyan.dev/ffmpeg/builds/

Also, official documentation has some hints: http://ffmpeg.org/ffmpeg-all.html#rubberband

**Comment by BtbN** [comment]
It's that librubberband depends on libsamplerate and fftw3 at the very least.
So I'll have to package those as well and make sure they find each other properly while linking fully statically.
