### ISSUE TITLE
Disabling assert in libmp3lame to fix segfaults

### ISSUE THREAD

**Issue by Poulpatine** [BtbN/FFmpeg-Builds#198]
Hi,

I've faced many segfaults in ffmpeg.
After inspecting the coredumps and searching around I've found this bug at VLC: 

https://code.videolan.org/videolan/vlc/-/commit/c9e146e7872a6a16f9cf05e3f36aab14105cffa8

It appears that under certain circumstances ffmpeg can segfaults and disabling asserts in libmp3lame fix that.

In scripts.d/50-libmp3lame.sh, I've been able to do that with this line:

`CFLAGS="$CFLAGS -DNDEBUG" ./configure "${myconf[@]}"`

Do you think you could integrate this modification ?

Thanks.

**Comment by BtbN** [comment]
That should be easy enough, and I'll give VLC the benefit of the doubt on this that it's safe.
