### ISSUE TITLE
ffmpeg -version

### ISSUE THREAD

**Issue by 237dmitry** [BtbN/FFmpeg-Builds#199]
Please add the official base version of ffmpeg (5.1.1, 5.1.2 etc) in order to make it easier to navigate among autobuilds. Or write this in Readme.md
```powershell
PS > (ffmpeg -version)[0,1]
ffmpeg version N-108577-g6bf99f8c93-20221009 Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
```

**Comment by BtbN** [comment]
N-108577 is the official version.
If you want something that's based off of a release branch, grab a build of the respective branch.
Currently 5.1 and 4.4 are available.

**Comment by 237dmitry** [comment]
> N-108577 is the official version.

Well, if it is not clear which release the build most corresponds to, I will download it once a month.

**Comment by BtbN** [comment]
It does not correspond to any release. Not sure what exactly you're asking, but every build builds the latest commit at the time, and that N-XXXXX numbering is how ffmpeg officially versions those.

**Comment by 237dmitry** [comment]
> Not sure what exactly you're asking

I want to update ffmpeg (by script) when the daily build is most consistent with the generally accepted version of the new release. I do not know which is newer than 5.1 or N-XXXXX. For example, on the Arch I can see and it is clear:
```powershell
PS > (pacman -Qi ffmpeg | sls '(?<=Version.+:)[\d.]+').Matches.Value
5.1.2

PS > [version] '5.1.2'

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      2      -1
```

**Comment by BtbN** [comment]
What do you mean, "generally accepted version of the new release"?
The generally accepted version of ffmpeg is the latest version on git master, which is what all builds that don't mention a release branch are.
If you want a consistent link, you can rely on the floating "latest" release tag, that is recreated every day.

**Comment by 237dmitry** [comment]
> What do you mean, "generally accepted version of the new release"?

A version designation that conforms to the norms of the version designation. `5.1.1`, `0.3.2-rc`, etc. Or at least a reference to the fact that `N-12345` corresponds to the new minor release 5.1.3. How else can I find out which `N-98765` and on what day should I download it?

**Comment by BtbN** [comment]
I really don't understand what you are asking.
These builds build the latest commit from git master, every day. It does not correspond to any release. The N-XXXX designation denotes the number of commits since an arbitrary "N" tag from long ago.

**Comment by zhongfly** [comment]
Maybe he want build for tag like https://github.com/FFmpeg/FFmpeg/releases/tag/n5.1.2 and `ffmpeg -verson` can get 5.1.2

**Comment by 237dmitry** [comment]
> Maybe he want builds for ffmpeg tags like

Yes. Displaying versions in daily builds does not give an idea whether to download them or not. It is unclear if something has changed or if ffmpeg, similar to yesterday's or a weeks ago, was just automatically built. At this moment I think to download daily build monthly, this give more chances to get really new build.

**Comment by 237dmitry** [comment]
I'm very sorry, I DIDN'T NOTICE that there are more assets under the spoiler, which indicate a clear version.
Because of this, there was a misunderstanding between us. Thank for your work!

```powershell
$assets = (Invoke-WebRequest https://api.github.com/repos/BtbN/FFmpeg-Builds/releases).Content | ConvertFrom-Json
$url = [uri]($assets.assets | Where-Object { $_.name -match 'ffmpeg-n[\d.]+-latest-win64-gpl-[\d.]+\.zip' }).browser_download_url[-1]
$file = $url.Segments[-1]

Invoke-WebRequest $url -OutFile $file
```

**Comment by 237dmitry** [comment]
> Not quite sure what you mean with spoiler either

Spoiler on release page "Show all 38 assets". I want a clear version display. Nothing more than that. I need this to compare versions when updating if the version has changed. For me, "Build" token is not too important, but it would be nice to have it.
```
PS > [version] '5.1.1'

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      1      -1
```
At the moment I'm only comparing Major and Minor tokens of versions:
```powershell


$assets = (Invoke-WebRequest https://api.github.com/repos/BtbN/FFmpeg-Builds/releases).Content | ConvertFrom-Json
$latest = ($assets.assets | Where-Object { $_.name -match 'ffmpeg-n[\d.]+-latest-win64-gpl-[\d.]+\.zip' })[-1]

$url = $latest.browser_download_url
$file = $latest.name
$file_version = $latest.name -replace '.+-|\.zip'                       # 5.1, It would be better 5.1.2
$ffmpeg_version = (ffmpeg -version)[0] -replace '.+n(\d+\.\d+).+','$1'  # 5.1, '.+n([\d.]+).+', '$1' for 5.1.2

if ([version] $file_version -gt [version] $ffmpeg_version)
{
    Invoke-WebRequest $url -OutFile $file
    # Unpack zip to the ffmpeg location 
}

else { 'ffmpeg is up to date' }
```

**Comment by ZaquL** [comment]
Stable is latest master. That is the policy of ffmpeg. There are plans to do an LTS release, but I am not sure when.

**Comment by hayguen** [comment]
i'm not sure, if i have the same issue as @237dmitry  .. but it sounds similar enough!

as i describe in https://github.com/yt-dlp/FFmpeg-Builds/issues/31, i would like to determine automatically, if there's need to download a new version of ffmpeg, e.g. https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n5.1-latest-linux64-gpl-5.1.tar.xz listed in https://api.github.com/repos/BtbN/FFmpeg-Builds/releases/latest from the 5.1 release.

one way might be, if `ffmpeg -version` would output one same comparable id, e.g. the git commit/sha-id, which can also get identified/found in the `name` or `browser_download_url` field of the `assets` list in https://api.github.com/repos/BtbN/FFmpeg-Builds/releases/latest
