### ISSUE TITLE
Unable to find shared libraries

### ISSUE THREAD

**Issue by shubmittal** [BtbN/FFmpeg-Builds#2]
After installing ffmpeg full build  from here, I am not able to get other libraries like avformat-55.dll. Can you please let me know where to download these from?

**Comment by BtbN** [comment]
This is a purely static build, it's only the executables, no libraries.
Building with them is possible, but would double build times and size, so I opted against it, since I'm not sure what use those standalone shared libs would serve.

**Comment by garoto** [comment]
Shared builds in would be a nice addition, since they generally take the same size as a single CLI binary in a static build, and there are thre of them in a static one.

**Comment by BtbN** [comment]
The size of the zip wouldn't change much, since the 3 nearly identical binaries compress down anyway.
But it would be twice the amount of zips.

**Comment by BtbN** [comment]
There's now shared variants of all current variants.

**Comment by garoto** [comment]
Fricking awesome BtbN, thanks a bunch. Zip sizes are a nice.

**Comment by BtbN** [comment]
I'm actually surprised they're that much smaller. Makes me want something better than zipfiles, but that would greatly reduce easy accessibility on Windows.

**Comment by garoto** [comment]
> but that would greatly reduce easy accessibility on Windows.

True.

But in case you haven't tried it already, here's a default .7z compression results with the most recent shared binaries: 

```
[ C:\Apps\AV\ffmpeg ]
> 7z a ffmpeg-N-99346-g003b5c800f-win64-gpl-shared.7z *.exe *.dll -xr"!x264*"

7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21

Scanning the drive:
11 files, 85895680 bytes (82 MiB)

Creating archive: ffmpeg-N-99346-g003b5c800f-win64-gpl-shared.7z

Add new data to archive: 11 files, 85895680 bytes (82 MiB)

Files read from disk: 11
Archive size: 20642830 bytes (20 MiB)
Everything is Ok
```
