### ISSUE TITLE
Could you please add some patches to update the AMF SDK to 1.4.23.0 (or support hevc_amf encode h265 10bit)?

### ISSUE THREAD

**Issue by ishkong** [BtbN/FFmpeg-Builds#202]
Hi, 

I want to use hevc_amf in ffmpeg to encode hevc 265 10bit video.

But ffmpeg does not support it. When I found amf's repo, the developer said that ffmpeg has not merged relevant pr. 

[AMF#348-comment-1234987600](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/348#issuecomment-1234987600)

[AMF#348-comment-1247070971](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/348#issuecomment-1247070971)

Cloud you please add some patches to support this feature?

Thanks.

**Comment by BtbN** [comment]
I'm not applying patches to ffmpeg itself, and to dependencies only if they're dead and unresponsive.
The maintenance burden is too high, and I also have no way to ensure the quality of the code applied. The regular review process for ffmpeg is the way to go.
It'd be 3 different versions of patches as well, which all could break any day.
