### ISSUE TITLE
Q: Issue about turn m4s-->MP4

### ISSUE THREAD

**Issue by StillYoung1214** [BtbN/FFmpeg-Builds#206]
Does the latest version of FFMPEG(win64) support the format of 'm4s'?
In my PC, it turned out that FFMPEG doesnt support this format.

**Comment by BtbN** [comment]
m4s is a segment from a DASH stream for all I know.
Those cannot be played on their own. You at the very least need the corresponding init-segment from the DASH manifest, which you then need to prepend to the m4s file(s) to get a valid mp4 file.

In any case, the ffmpeg-user list is a much better place for questions regarding ffmpeg.

**Comment by StillYoung1214** [comment]
To be specific, I'm about to turn segmented .m4s into one .mp4 file, i used the `ffmpeg -i seg-1.mp4 -codec copy seg-1.mp4`
And the

**Comment by StillYoung1214** [comment]
> m4s is a segment from a DASH stream for all I know. Those cannot be played on their own. You at the very least need the corresponding init-segment from the DASH manifest, which you then need to prepend to the m4s file(s) to get a valid mp4 file.
> 
> In any case, the ffmpeg-user list is a much better place for questions regarding ffmpeg.

aight， thank u so much.
