### ISSUE TITLE
Bug : When remuxing dolby atmos mkv to mp4, complexity index is not present.

### ISSUE THREAD

**Issue by bluewidy** [BtbN/FFmpeg-Builds#209]
Here is a Dolby Atmos sample file with an EAC3-JOC audio stream : https://we.tl/jxvi4Pgwz9
source : https://thedigitaltheater.com/dolby-trailers/

From this, if I demux the EAC3-JOC, as you can see the complexity index is set correctly.
<img width="346" alt="demuxed eac3-joc" src="https://user-images.githubusercontent.com/40682277/198607696-cace19e5-ea56-4544-a1a7-6767ffe5027d.png">

However, when I remux MKV to MP4, the complexity index is not present.
<img width="338" alt="MKV to MP4" src="https://user-images.githubusercontent.com/40682277/198609017-02fc30f6-d458-4412-81d5-2ba1bc04a44c.png">

The reason this bug needs to be resolved is that, in the case of a smartphone that supports Dolby Atmos, the Dolby Atmos virtualizer is automatically activated only when the complexity index is presented.

**Comment by BtbN** [comment]
That doesn't look like an issue with these builds to me.
Please raise issues with ffmpeg itself in the ffmpeg bugtracker.

**Comment by bluewidy** [comment]
> That doesn't look like an issue with these builds to me.

Does that mean my problem is not happening with this build? : Latest Auto-Build (2022-10-28 12:38)

**Comment by BtbN** [comment]
It's still not an issue of these builds.
Please only report issues specifically with the builds here. I cannot take care of all ffmpeg related issues. FFmpeg has its own bugtracker and support channels.

If this would be happening only with my builds, but not with something you or someone else built, then it'd be a valid issue here.
But to me this looks like it's an issue with ffmpeg itself, not specifically these builds.

**Comment by bluewidy** [comment]
Okay. Thank you for the information.
