### ISSUE TITLE
stable download URL and version?

### ISSUE THREAD

**Issue by hayguen** [BtbN/FFmpeg-Builds#210]
just noticed, that i commented / asked on the closed issue https://github.com/BtbN/FFmpeg-Builds/issues/199; now deleted the comment there.

i'm not sure, if i have the same issue as @237dmitry  .. but it sounds similar enough!

as i describe in https://github.com/yt-dlp/FFmpeg-Builds/issues/31, i would like to determine automatically, if there's need to download a new version of ffmpeg, e.g. https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n5.1-latest-linux64-gpl-5.1.tar.xz listed in https://api.github.com/repos/BtbN/FFmpeg-Builds/releases/latest from the 5.1 release.

one way might be, if `ffmpeg -version` would output one same comparable id, e.g. the git commit/sha-id, which can also get identified/found in the `name` or `browser_download_url` field of the `assets` list in https://api.github.com/repos/BtbN/FFmpeg-Builds/releases/latest

**Comment by BtbN** [comment]
Like I said in that issue already: There's new commits to master almost every day. So you can safely assume that there's been some changes.

The daily releases have exactly what you are asking for in the file name. What else are you looking for?

**Comment by BtbN** [comment]
Maybe you missed that there's two releases every day? One with specific version numbers, and one which is just "latest" so there's stable URLs that never change.
The "latest" release is recreated every day.

**Comment by BtbN** [comment]
Also: Even if the ffmpeg version did not change, the dependencies very well might have been upgraded.
For example, on Monday there will be the critical openssl update. The version number of the release-builds won't change, yet you very much will want to use the latest version of them.

**Comment by hayguen** [comment]
@BtbN : you mean, that https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n5.1-latest-linux64-gpl-5.1.tar.xz  really changes every day (2 times)?

dependency updates: hmm, didn't think on those

**Comment by BtbN** [comment]
That link will be re-built every day, yes. If something changed depends on if something was pushed to the 5.1 release branch that day, or if dependencies were updated (which won't be reflected in the version number whatsoever)

**Comment by hayguen** [comment]
@BtbN ooookay. Thank You for clarification.
