### ISSUE TITLE
enable 10 bit decoding for uavs3d

### ISSUE THREAD

**Issue by zhongfly** [BtbN/FFmpeg-Builds#211]
[uavs3d](https://github.com/uavs3/uavs3d) support 10 bit but default configuration only support 8bit decoding.

https://github.com/uavs3/uavs3d#compile :

> To support 10bit streams decoding: cmake -DCOMPILE_10BIT=1

Test samples:
avs3 10bit https://github.com/xatabhk/avs2-avs3-video-samples/blob/master/jellyfish-640x360-avs3-10bit.mkv

**Comment by zhongfly** [comment]
I try to use ffplay play this sample https://github.com/xatabhk/avs2-avs3-video-samples/blob/master/jellyfish-640x360-avs3-10bit.mkv with [2022-11-06](https://github.com/BtbN/FFmpeg-Builds/releases/tag/autobuild-2022-11-06-13-08) build.
But only heard the sound, did not see the video content, even the window did not appear.

**Comment by BtbN** [comment]
Yes, isn't working for me either. Not much I can do about it though at the scope of these builds.
Seems to be a bug in either the ffmpeg wrapper or the library itself.
