### ISSUE TITLE
which one should i download

### ISSUE THREAD

**Issue by idkman2021** [BtbN/FFmpeg-Builds#212]
[ffmpeg-master-latest-win64-gpl-shared.zip](https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl-shared.zip) or [ffmpeg-master-latest-win64-gpl.zip](https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip)

**Comment by BtbN** [comment]
If you need shared libs, the one with shared libs. Otherwise just use the completely static one.

**Comment by idkman2021** [comment]
> If you need shared libs, the one with shared libs. Otherwise just use the completely static one.

what does that mean? I need it to edit videos

**Comment by BtbN** [comment]
If you don't know what shared libraries are, there's a very high chance you don't need them.
You only need them if you are developing an application yourself, or need to use ffmpeg as plugin in other software.

**Comment by shaoshilei** [comment]
You should try ffmpeg-master-latest-win64-gpl-shared.zip

**Comment by BtbN** [comment]
Don't use a shared build unless you know you need one. It's just needlessly inviting issues with DLL collisions some other software might have installed.

Gonna close the issue. Feel free to re-open if you feel like you didn't get the answer you were looking for yet.

**Comment by jesus2099** [comment]
Hello @BtbN,

I read somewhere shared package included DLL so it was better and I installed it.
Apparently it was wrong.

I think you should explain in the README for people like us who just want to install **a working version of ffmpeg on their Windows**.

Example of explanation:

> _For normal people, you should download non-shared packages._

And as a bonus, but maybe not necessary, maybe explain what is a shared package.
