### ISSUE TITLE
ffnvcodec requested but not found

### ISSUE THREAD

**Issue by shaoshilei** [BtbN/FFmpeg-Builds#215]
I run “./makeimage.sh win32 gpl” successfully. But when I run "./build.sh win32 gpl" failure. The error message is:
ERROR: ffnvcodec requested but not found.
Wthat's the problem?

**Comment by BtbN** [comment]
What's the error output you get in the config.log?

**Comment by shaoshilei** [comment]
i686-w64-mingw32-gcc -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -U__STRICT_ANSI__ -D__USE_MINGW_ANSI_STDIO=1 -D__printf__=__gnu_printf__ -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -static-libgcc -static-libstdc++ -I/opt/ffbuild/include -O2 -pipe -D_FORTIFY_SOURCE=2 -fstack-protector-strong -DLIBTWOLAME_STATIC -std=c11 -fomit-frame-pointer -pthread -I/opt/ffbuild/include -I/opt/ffbuild/include -DCHROMAPRINT_NODLL -I/opt/ffbuild/include -I/opt/ffbuild/include/libvmaf -pthread -I/opt/ffbuild/include -I/opt/ffbuild/include/libpng16 -I/opt/ffbuild/include/lilv-0 -DLILV_STATIC -I/opt/ffbuild/include -I/opt/ffbuild/include/serd-0 -I/opt/ffbuild/include/sord-0 -I/opt/ffbuild/include/sratom-0 -DSRATOM_STATIC -DSORD_STATIC -DSERD_STATIC -I/opt/ffbuild/include -I/opt/ffbuild/include/freetype2 -I/opt/ffbuild/include/libxml2 -DLIBXML_STATIC -I/opt/ffbuild/include/harfbuzz -I/opt/ffbuild/include/fribidi -DFRIBIDI_LIB_STATIC -I/opt/ffbuild/include -I/opt/ffbuild/include/libxml2 -DLIBXML_STATIC -I/opt/ffbuild/include/freetype2 -I/opt/ffbuild/include -I/opt/ffbuild/include -I/opt/ffbuild/include/freetype2 -I/opt/ffbuild/include/libxml2 -DLIBXML_STATIC -I/opt/ffbuild/include/freetype2 -I/opt/ffbuild/include -I/opt/ffbuild/include/fribidi -DFRIBIDI_LIB_STATIC -I/opt/ffbuild/include -I/opt/ffbuild/include -DHWY_STATIC_DEFINE -DJXL_STATIC_DEFINE -DJXL_STATIC_DEFINE=1 -I/opt/ffbuild/include -DJXL_THREADS_STATIC_DEFINE -DJXL_STATIC_DEFINE=1 -I/opt/ffbuild/include -DKVZ_STATIC_LIB -I/opt/ffbuild/lib/pkgconfig/../../include -I/opt/ffbuild/lib/pkgconfig/../../include/vpl -I/opt/ffbuild/include -I/opt/ffbuild/include/openjpeg-2.5 -DOPJ_STATIC -I/opt/ffbuild/include -I/opt/ffbuild/include/opus -I/opt/ffbuild/include/opus -I/opt/ffbuild/include -I/opt/ffbuild/include/spirv_cross -I/opt/ffbuild/include -pthread -DCJSON_HIDE_SYMBOLS -I/opt/ffbuild/include -I/opt/ffbuild/include -I/opt/ffbuild/include -DLIBSSH_STATIC -I/opt/ffbuild/include -I/opt/ffbuild/include/srt -I/opt/ffbuild/include -I/opt/ffbuild/include -I/opt/ffbuild/include/libvmaf -pthread -I/opt/ffbuild/include -I/opt/ffbuild/include -I/opt/ffbuild/include -I/opt/ffbuild/include -I/opt/ffbuild/include -I/opt/ffbuild/include -I/opt/ffbuild/include -I/opt/ffbuild/include/webp -I/opt/ffbuild/include -I/opt/ffbuild/include/webp -I/opt/ffbuild/include -I/opt/ffbuild/include -I/opt/ffbuild/include -I/opt/ffbuild/include -I/opt/ffbuild/include/libxml2 -DLIBXML_STATIC -I/opt/ffbuild/include -I/opt/ffbuild/include/AL -DAL_LIBTYPE_STATIC -I/opt/ffbuild/include -I/opt/ffbuild/include -Wdeclaration-after-statement -Wall -Wdisabled-optimization -Wpointer-arith -Wredundant-decls -Wwrite-strings -Wtype-limits -Wundef -Wmissing-prototypes -Wstrict-prototypes -Wempty-body -Wno-parentheses -Wno-switch -Wno-format-zero-length -Wno-pointer-sign -Wno-unused-const-variable -Wno-bool-operation -Wno-char-subscripts -O3 -fno-math-errno -fno-signed-zeros -fno-tree-vectorize -Werror=format-security -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=return-type -Werror=vla -Wformat -fdiagnostics-color=auto -Wmaybe-uninitialized -c -o /tmp/ffconf.zrAPahJi/test.o /tmp/ffconf.zrAPahJi/test.c
ERROR: ffnvcodec requested but not found

**Comment by BtbN** [comment]
That's not the relevant part. You need to find the part where it fails to find ffnvcodec.
ffnvcodec and the ffmpeg dependency on it was somewhat recently bumped. So make sure the image you are using for the build is up to date. An image from a week ago isn't going to work.

**Comment by shaoshilei** [comment]
In config.log:
pkg-config --exists --print-errors ffnvcodec >= 12.0.11.0
Package dependency requirement 'ffnvcodec >= 12.0.11.0' could not be satisfied.
Package 'ffnvcodec' has version '11.1.5.1', required version is '>= 12.0.11.0'

In 50-ffnvcodec.sh:
SCRIPT_REPO="https://github.com/FFmpeg/nv-codec-headers.git"
SCRIPT_COMMIT="3ed7c9a0a2c0b698b83088e13008f3ec983219b2"

Is that  SCRIPT_COMMIT="3ed7c9a0a2c0b698b83088e13008f3ec983219b2" wrong?

**Comment by BtbN** [comment]
It's too old for current ffmpeg master.
You either need 11.1.5.2 or 12.0.11.0. I pushed an update for that yesterday, so make sure you're up to date and stuff should work then.

**Comment by shaoshilei** [comment]
I just download [Latest Auto-Build (2022-11-05 12:37)](https://github.com/BtbN/FFmpeg-Builds/releases/tag/latest),
and add one empty line into 50-ffnvcodec.sh(Update its write-time), and re-run './makeimage.sh win32 gpl'  successfully.
When I run './build.sh win32 gpl', error occurs again:
ERROR: ffnvcodec requested but not found

In config.log yet:
pkg-config --exists --print-errors ffnvcodec >= 12.0.11.0
Package dependency requirement 'ffnvcodec >= 12.0.11.0' could not be satisfied.
Package 'ffnvcodec' has version '11.1.5.1', required version is '>= 12.0.11.0'

What can I do next?

**Comment by BtbN** [comment]
Not sure what you mean by you downloaded the latest release.
You need to clone this repo, and make sure it's up to date. The version was updated less than 24h ago.
If you are using your own fork, you need to update it.
Make sure you have 3bb2b17e48330854887b8658481bb02ab0fe82e4

**Comment by shaoshilei** [comment]
I edit 50-ffnvcodec.sh,change  SCRIPT_COMMIT="master". 
After this change, everything goes OK. ./build.sh win32 gpl can work.

I think , 3ed7c9a0a2c0b698b83088e13008f3ec983219b2 in 50-ffnvcodec.sh may be a wrong tag value.

**Comment by BtbN** [comment]
Like I said, it's too old, and got updated recently.
You are using an outdated version. Make sure to pull before building your image.

**Comment by shaoshilei** [comment]
Anyway, thank you again.
