### ISSUE TITLE
Unknown encoder 'libfdk_aac'

### ISSUE THREAD

**Issue by mochazi** [BtbN/FFmpeg-Builds#216]
Why isn't `--enable-libfdk-aac` enabled here?
![image](https://user-images.githubusercontent.com/54659396/201683842-a87d48d1-e8b8-4f8a-ab2a-105d97b9cfc8.png)

**Comment by BtbN** [comment]
libfdk-aac is nonfree and thus cannot be in redistributable builds.
If you want libfdk, you got to produce a nonfree build locally yourself.

**Comment by mochazi** [comment]
@BtbN 
In redistributable builds, which audio encoder can I use?

**Comment by garoto** [comment]
> ffmpeg -encoders | grep -i aac
