### ISSUE TITLE
v4l2m2m hwaccel not working on rpi kernel 5.15.61+

### ISSUE THREAD

**Issue by NickM-27** [BtbN/FFmpeg-Builds#217]
We have seen that hwaccel on the rpi has stopped working after kernel 5.15.61. There was an issue posted on the rpi linux repo and it seems to have been fixed there: https://github.com/raspberrypi/linux/issues/5150#issuecomment-1245215001 

I am wondering if this fix is going to propogate to BtbN builds here?

Thanks!

**Comment by BtbN** [comment]
If it gets merged into FFmpeg, it will naturally end up in the builds here as well.
But I don't see a patch for FFmpeg anywhere in that issue?

**Comment by BtbN** [comment]
I build latest master every day. If the patch got merged already, it's part of these builds.
The branch linked there is a really out of date FFmpeg version, and I'm not seeing any of the patches in there(which look of questionable quality to me) upstream. So I don't think they ever got submitted.

**Comment by NickM-27** [comment]
Thanks for your explanation, our current build is from `autobuild-2022-07-31-12-37` so I'll definitely do a build with the latest master and have our users test to see if it is still an issue.

**Comment by jherby2k** [comment]
I just tested this for @NickM-27. Looks like the patch didn't make it upstream as the issue persists.

**Comment by BtbN** [comment]
You will need to contact the developer of the patch then and ask them to submit it.
I'm not accepting patches to FFmpeg here, that's out of scope for this repo.

**Comment by NickM-27** [comment]
Makes sense, should this issue be closed since once the issue is fixed upstream it'll automatically be included in a new build here?

**Comment by BtbN** [comment]
There's not much I can do about it here, so can probably be closed.
