### ISSUE TITLE
BUG 

### ISSUE THREAD

**Issue by yehaku** [BtbN/FFmpeg-Builds#218]
ffmpeg-N-109149-g459527108a-win64-gpl-shared.zip 用 FFQueue 1.7.59.284 调用压 H265 调整 视频格式后会出现
双视频通道的BUG

ffmpeg-N-109149-g459527108a-win64-gpl-shared. Zip uses FFQueue 1.7.59.28to call H265 to adjust the video format

BUG of dual video channels

**Comment by zhongfly** [comment]
Please only report issues specifically with the builds here. FFmpeg has its own bugtracker and support channels.

If this would be happening only with this builds, but not with something you or someone else built, then it'd be a valid issue here.
