### ISSUE TITLE
ffmpeg gpu?

### ISSUE THREAD

**Issue by Nex4rius** [BtbN/FFmpeg-Builds#22]
Is this with the <a href="https://docs.nvidia.com/video-technologies/video-codec-sdk/ffmpeg-with-nvidia-gpu/index.html">ffmpeg nvidia gpu support</a>?

**Comment by BtbN** [comment]
Yes

**Comment by BtbN** [comment]
Though keep in mind that libnpp specifically is nonfree, so it's missing. scale_cuda works however.

**Comment by Nex4rius** [comment]
Okay thanks.
