### ISSUE TITLE
Compiler Switches - /HIGHENTROPYVA and /GS

### ISSUE THREAD

**Issue by MrMontana1889** [BtbN/FFmpeg-Builds#223]
We have just upgraded to use the latest 5.1 nightly build of ffmpeg.  However, the compiler switches /HIGHENTROPYVA and /GS are not being used.

Our security audit will fail without these compiler switches.

I have yet to successfully build locally for Win64.  Is there any way these switches can be added to the official nightly build?

**Comment by BtbN** [comment]
According to Get-PESecurity, HighentropyVA is enabled already, and /GS is MSVCs version of -fstack-protector-strong, which is already enabled as well and pretty much always has been.
Just added another hardening flag I learned about when researching this, though I'm not sure it does much, but can't hurt either.

**Comment by MrMontana1889** [comment]
Thank you!  I will forward this on to our security team.  I appreciae the quick responses.
