### ISSUE TITLE
Screen recording fails to this application Calculator , Alarm & Clock, Microsoftoutlook

### ISSUE THREAD

**Issue by badashaha** [BtbN/FFmpeg-Builds#224]
i used ffmpeg with Windows 10 OS
FFmpeg do recording well and excellent for Desktop as well as title=<windowname>
title=windowname  lke title=notpad, title = any application window name it work fine 
but the problem it that when we try to record title=Calculator or title=Alarm&Clock or Title=Inbox -outlook
FFmpeg shows window found but for this three application , it only record Black window with mouse course and its movement ,
i unable to trace exact issue and how to solve this i try almost all with gdigrab options can you please help me to record screen for this application. is something i missed for this application

**Comment by BtbN** [comment]
Please direct usage-questions to the ffmpeg-user mailinglist or #ffmpeg on Libera.Chat.
