### ISSUE TITLE
make win32-gpl image error

### ISSUE THREAD

**Issue by shaoshilei** [BtbN/FFmpeg-Builds#225]
When I run ./makeimage.sh win32 gpl, following errors  are showed:

error: failed to solve: process "/bin/sh -c    git clone --filter=blob:none https://github.com/crosstool-ng/crosstool-ng.git /ct-ng && cd /ct-ng &&     ./bootstrap &&     ./configure --enable-local &&     make -j$(nproc) &&     cp /.config .config &&     ./ct-ng build &&     cd / &&     git config --global --unset http.proxy &&     git config --global --unset https.proxy &&     rm -rf ct-ng" did not complete successfully: exit code: 2
+ rm -f /tmp/tmp.cYh82bJAGE.toml
+ docker container stop ffbuildreg
ffbuildreg
[root@localhost FFmpeg-Builds-latest]# 

What's the problem?

**Comment by BtbN** [comment]
Impossible to tell, you did not include the actual error in your paste.
Please paste the full error output.

**Comment by shaoshilei** [comment]
Because network fault, downloading of MingW did not completed. When network recover, makeimage worked successfully. Thank you.
