### ISSUE TITLE
AVS2 video encoder is not available and AVS3's video encoding is also not included

### ISSUE THREAD

**Issue by oncebeloved** [BtbN/FFmpeg-Builds#226]
AVS2 video encoder is not available, using FFMEG to convert and HEVC encoded video into AVS2 encoding can not generate AVS2 encoded video, and this project does not seem to provide AVS3 video encoding solution, I hope Tycoon can solve these two points, thank you!

avs2
https://github.com/pkuvcl/xavs2
https://github.com/pkuvcl/FFmpegAVS2
https://github.com/pkuvcl/buildFFmpegAVS2

avs3
https://github.com/uavs3/uavs3e
https://github.com/uavs3/uavs3e_ffmpeg_interface

**Comment by BtbN** [comment]
Both of those libraries are already built and supported:
https://github.com/BtbN/FFmpeg-Builds/blob/master/scripts.d/50-xavs2.sh
https://github.com/BtbN/FFmpeg-Builds/blob/master/scripts.d/50-uavs3d.sh

**Comment by oncebeloved** [comment]
AVA2,After my actual use, the last version of AVS encoding by you can't generate video (HEVC-> AVS2)
AVS3, you only provided video decoding(uavs3d), but not video encoding (uavs3e)
So I gave this feedback.Thanks

**Comment by BtbN** [comment]
From what I can tell, there is no support for uavs3e (and the encoding portion of xavs2) in ffmpeg, that's not something I can address. Patches for FFmpeg need to go via the appropriate channels.

If those two projects added encoding support, they need to upstream those patches, and they will automatically end up here.
