### ISSUE TITLE
makeimage error

### ISSUE THREAD

**Issue by shaoshilei** [BtbN/FFmpeg-Builds#227]
When I run ./makeimage win64 gpl, an error occurs:
 => # + timeout 1020 sh -c 'rm -rf gmp && hg clone -r '\''614a1cd8bb1d'\'' -
 => => # u '\''614a1cd8bb1d'\'' '\''https://gmplib.org/repo/gmp/'\'' gmp'      
 => => # abort: error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify fail
 => => # ed: certificate has expired (_ssl.c:997)                              
 => => # ++ shuf -i 5-90 -n 1                                                  
 => => # + sleep 60                                                            

When I download gmp by command line
hg clone -r 614a1cd8bb1d -u 614a1cd8bb1d https://gmplib.org/repo/gmp/gmp
Some error messages are displayed as followed:

 [root@localhost Downloads]# hg clone -r 614a1cd8bb1d -u 614a1cd8bb1d https://gmplib.org/repo/gmp/gmp
abort: error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)
[root@localhost Downloads]# 

What's the matter?

**Comment by BtbN** [comment]
Their certificate expired it seems. Nothing I can do about that.
In the meantime you'll have to use pre-built images and hope they fix it before a rebuilt becomes necessary.

**Comment by shaoshilei** [comment]
Thank you.

**Comment by shaoshilei** [comment]
https://gmplib.org/repo/gmp has recovered. I can run ./makeimage again.
