### ISSUE TITLE
Switching from libmfx to libvpl

### ISSUE THREAD

**Issue by paulober** [BtbN/FFmpeg-Builds#228]
See the benefits here: https://www.intel.com/content/www/us/en/developer/articles/technical/onevpl-in-ffmpeg-for-great-streaming-on-intel-gpus.html#inpage-nav-2  

Quote: 
"`
Switching from libmfx to libvpl for the *_qsv codecs in FFMPEG provides an easy way to align with future updates from Intel. Media SDK has already had its final feature updates. Even if security fixes force a new release, features will not change beyond Media SDK’s current 1.35 API implementation. New features will be enabled for new Intel hardware in oneVPL. As an example, one of the first places that oneVPL features start to differentiate from Media SDK is AV1 encode.  Intel released GPUs with the industry’s first hardware accelerated AV1 encoder, which can be accessed via FFMPEG.  This approach is written on top of oneVPL.  In general, Media SDK represents legacy GPU support and oneVPL is for current and future Intel integrated  and discrete GPUs.
`" - Quote from link intel.com article linked above

Fix:

"The switch to oneVPL from Media SDK in FFMPEG, is simple. Just substitute `--enable-libvpl` instead of `--enable-libmfx` in the configure stage of FFMPEG compilation.  Both options enable compilation of Intel® Quick Sync Video (*_qsv) codecs, which can be used without change from the FFMPEG command line or in applications.

Users can switch to oneVPL in FFMPEG, even for older Intel hardware." - Quote from link intel.com article linked above

**Comment by BtbN** [comment]
https://github.com/BtbN/FFmpeg-Builds/commit/8fff2b2a8ee851f7b0ff401f6ca64b792a9e9f71

**Comment by paulober** [comment]
@BtbN Ok, sorry. Is it possible to also enable it for the 5.1 builds?

**Comment by BtbN** [comment]
5.1 does not support libvpl

**Comment by paulober** [comment]
> 5.1 does not support libvpl

Ah ok
