### ISSUE TITLE
how to get current release

### ISSUE THREAD

**Issue by hr8** [BtbN/FFmpeg-Builds#233]
current release seems to be 5.1.2:

https://ffmpeg.org/pipermail/ffmpeg-devel/2022-September/301362.html

how do we get that?

**Comment by BtbN** [comment]
The latest build from the 5.1 series is part of every build. All the archives with n5.1 in their name.

**Comment by hr8** [comment]
I dont see any:

https://github.com/BtbN/FFmpeg-Builds/releases/tag/latest

**Comment by BtbN** [comment]
They're all there, sorted at the bottom alphabetically.

**Comment by hr8** [comment]
ah crap, my mistake. they were hidden:

> Show all 38 assets
