### ISSUE TITLE
Why can't I download it

### ISSUE THREAD

**Issue by zcg3648806** [BtbN/FFmpeg-Builds#235]
Every download failed a few minutes after it started, prompting me to ask for authorization :-(

**Comment by BtbN** [comment]
That must be an issue on either your on Githubs end.
The release artifacts are not in any way locked behind authorization.

**Comment by Pingger** [comment]
it is a github issue: releases caused by gothub actions require you to be signed in, preventing easy wget and curl downloads. (at least when I try this in germany)

**Comment by BtbN** [comment]
`wget https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip` works fine for me.
Do you have a reference to that issue?

**Comment by zcg3648806** [comment]
> `wget https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip` works fine for me. Do you have a reference to that issue?

Thank you, I successfully downloaded it by this way. :-)

**Comment by BtbN** [comment]
Where and how do you run into this issue?
I've checked every recent release, you can download all of them perfectly fine without logging in.

**Comment by jasonmorales1** [comment]
This may be the same issue I'm running into
```
+ docker run --rm -v /home/jay/Downloads/FFmpeg-Builds-master:/uidtestdir ghcr.io/btbn/ffmpeg-builds/linux64-nonfree:latest touch /uidtestdir/uidtestfile
Unable to find image 'ghcr.io/btbn/ffmpeg-builds/linux64-nonfree:latest' locally
docker: Error response from daemon: Head "https://ghcr.io/v2/btbn/ffmpeg-builds/linux64-nonfree/manifests/latest": denied.
See 'docker run --help'.
```

**Comment by zcg3648806** [comment]
> Where and how do you run into this issue? I've checked every recent release, you can download all of them perfectly fine without logging in.

Well, in fact, in my previous attempts, whenever I tried to download this file with a downloader (such as the one that comes with the browser or whatever) it would pop up at about 8-9Mb, prompting me to ask for authorization. This doesn't happen when I download with wget.
I think it might be a problem with the downloader.
