### ISSUE TITLE
makeimage.sh fails: cannot retrieve file from server (libiconv)

### ISSUE THREAD

**Issue by stamasd** [BtbN/FFmpeg-Builds#237]
I was trying today makeimage.sh for target=linux64, variant=nonfree. It built the image for about 40 minutes, then stalled at:

 => [layer-20-libiconv 1/1] RUN --mount=src=scripts.d/20-libiconv.sh,dst=/stage.sh run_stage /stage.sh
=> => # cd045e114e96a9f00483                                                   
 => => # Retry 2...                                                             
 => => # error: Server does not allow request for unadvertised object e46dee2f581c1167137bcd045e114e96a9f00483                                     
 => => # ++ shuf -i 5-90 -n 1                                                  
 => => # + sleep 80    

 => => # + echo 'Retry 6...'                                                                                                      
 => => # + [[ 6 -lt 10 ]]                                                                                                         
 => => # + timeout 480 git -C iconv fetch --depth=1 origin e46dee2f581c1167137bcd045e114e96a9f00483                               
 => => # error: Server does not allow request for unadvertised object e46dee2f581c1167137bcd045e114e96a9f00483                    
 => => # ++ shuf -i 5-90 -n 1                                                                                                     
 => => # + sleep 85      

 => => # + echo 'Retry 7...'                                                                                                      
 => => # + [[ 7 -lt 10 ]]                                                                                                         
 => => # + timeout 540 git -C iconv fetch --depth=1 origin e46dee2f581c1167137bcd045e114e96a9f00483                               
 => => # error: Server does not allow request for unadvertised object e46dee2f581c1167137bcd045e114e96a9f00483                    
 => => # ++ shuf -i 5-90 -n 1                                                                                                     
 => => # + sleep 41 

eventually it fails with 

#0 619.8 Retry 10...
#0 619.8 + [[ 10 -ge 10 ]]
#0 619.8 + echo 'Max retry count exceeded.'
#0 619.8 Max retry count exceeded.
#0 619.8 + exit 1

**Comment by BtbN** [comment]
Their git server is ridiculously broken. Every time they update, it forgets about the history somehow...

**Comment by stamasd** [comment]
Yes, thank you, got over that step now. :)

**Comment by Brainiarc7** [comment]
Still broken, see:

```sh
#0 422.2 + timeout 600 git -C iconv fetch --depth=1 origin 0a05ca75c08ae899f6fca5f79254491e13ffb500
#0 424.0 error: Server does not allow request for unadvertised object 0a05ca75c08ae899f6fca5f79254491e13ffb500
#0 424.0 ++ shuf -i 5-90 -n 1
#0 424.0 + sleep 7
#0 431.0 Retry 9...
#0 431.0 + RETRY_COUNTER=9
#0 431.0 + CUR_TIMEOUT=660
#0 431.0 + echo 'Retry 9...'
#0 431.0 + [[ 9 -lt 10 ]]
#0 431.0 + timeout 660 git -C iconv fetch --depth=1 origin 0a05ca75c08ae899f6fca5f79254491e13ffb500
#0 432.7 error: Server does not allow request for unadvertised object 0a05ca75c08ae899f6fca5f79254491e13ffb500
#0 432.7 ++ shuf -i 5-90 -n 1
#0 432.7 + sleep 39
#0 471.7 + RETRY_COUNTER=10
#0 471.7 + CUR_TIMEOUT=720
#0 471.7 + echo 'Retry 10...'
#0 471.7 + [[ 10 -lt 10 ]]
#0 471.7 + [[ 10 -ge 10 ]]
#0 471.7 + echo 'Max retry count exceeded.'
#0 471.7 + exit 1
#0 471.7 Retry 10...
#0 471.7 Max retry count exceeded.
------
Dockerfile:11
--------------------
   9 |     COPY --from=layer-10-xorg-macros $FFBUILD_PREFIX/share/aclocal/. /usr/share/aclocal
  10 |     FROM layer-10 AS layer-20-libiconv
  11 | >>> RUN --mount=src=scripts.d/20-libiconv.sh,dst=/stage.sh run_stage /stage.sh
  12 |     FROM layer-10 AS layer-20-libxml2
  13 |     RUN --mount=src=scripts.d/20-libxml2.sh,dst=/stage.sh run_stage /stage.sh
--------------------
ERROR: failed to solve: process "/bin/sh -c run_stage /stage.sh" did not complete successfully: exit code: 1
+ rm -f /tmp/tmp.VfacDGwL2z.toml
+ docker container stop ffbuildreg
ffbuildreg
```

is there another mirror that hosts the libiconv package?

**Comment by BtbN** [comment]
None that I'm aware of.
Their official git is the only source, and it's super broken. You can only fetch the latest commit, not any older one...
