### ISSUE TITLE
Nonfree docker image access denied

### ISSUE THREAD

**Issue by ernaro** [BtbN/FFmpeg-Builds#238]
Hi, please help me resolve the issue. 
When I run command "./build.sh linux64 nonfree" it ends with error:

Unable to find image 'ghcr.io/btbn/ffmpeg-builds/linux64-nonfree:latest' locally
docker: Error response from daemon: Head "https://ghcr.io/v2/btbn/ffmpeg-builds/linux64-nonfree/manifests/latest": denied.
See 'docker run --help'.

**Comment by BtbN** [comment]
nonfree images are not redistributable, 
So they are not available for download, and you need to build it yourself with the respective makeimage script.
