### ISSUE TITLE
build with librsvg

### ISSUE THREAD

**Issue by ecurien** [BtbN/FFmpeg-Builds#24]
Hi,
would it be possible to include librsvg in your ffmpeg build?
This would be great
Thank you

**Comment by BtbN** [comment]
That library seems to be written in rust.
First of, installing rust build tools blows up the size of the build image by several gigabytes, which is not something I'm too keen on.
I also have no idea how to get rust to support cross-compiling for Windows, specially for a fully static target.

They also do not seem to provide pre-built binaries, like rav1e does.

**Comment by BtbN** [comment]
I looked into it some more, and even with rust added, which already adds 2GB and more to the build images, it still wants A LOT more stuff:

```
configure: error: Package requirements (        cairo >= 1.16.0                 cairo-png >= 1.16.0             cairo-gobject >= 1.16.0         freetype2 >= 20.0.14            gdk-pixbuf-2.0 >= 2.20  gio-2.0 >= 2.24.0                       glib-2.0 >= 2.50.0                    harfbuzz >= 2.0.0               libxml-2.0 >= 2.9.0             pangocairo >= 1.38.0            pangoft2 >= 1.38.0             ) were not met:

No package 'cairo' found
No package 'cairo-png' found
No package 'cairo-gobject' found
No package 'gdk-pixbuf-2.0' found
No package 'gio-2.0' found
No package 'glib-2.0' found
No package 'pangocairo' found
No package 'pangoft2' found
```

That's way too much to add, it would take multiple days of work and would also likely increase the binary size by quite a large amount.
Sorry, but librsvg will not be added.

**Comment by ecurien** [comment]
Great Thanks anyway for our time.

**Comment by Jamaika1** [comment]
https://github.com/GyanD/codexffmpeg/issues/1
