### ISSUE TITLE
Problem converting 6-channel audio

### ISSUE THREAD

**Issue by AndresRohr** [BtbN/FFmpeg-Builds#241]
If I use Windows build "ffmpeg-2023-01-22-git-9d5e66942c-full_build" and try to convert this audio track to AAC
Stream #0:1[0x2](eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, 6 channels, fltp, 393 kb/s (default),
I get the output:
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))
	[aac @ 0000000002caff80] Unsupported channel layout "6 channels"
	[aac @ 0000000002caff80] Qavg: nan
	Error initializing output stream 0:1 -- Error while opening encoder for output stream #0:1 - maybe incorrect parameters such as bit_rate, rate, width or height
	Conversion failed!

I tried also the build from https://github.com/BtbN/FFmpeg-Builds/releases, similar result:
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))
	[aac @ 0000000002235ec0] Unsupported channel layout "6 channels"
	[aac @ 0000000002235ec0] Qavg: nan
	[aost#0:1/aac @ 0000000002235bc0] Error initializing output stream: Error while opening encoder for output stream #0:1 - maybe incorrect parameters such as bit_rate, rate, width or height
	Conversion failed!

If I do exactly the same with a nearly 2 year old build from here https://sourceforge.net/projects/ffmpeg-windows-builds/ it can do it without error:
Output is:
  Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, 5.1, fltp, 341 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc58.134.100 aac

The sizes of both packages are about the same. Maybe multichannel support somehow?

**Comment by BtbN** [comment]
Please raise this as an issue on ffmpeg trac. This is either a regression or just a plain change in behaviour that needs an adapted invocation.
Could also be worth asking about this on #ffmpeg IRC, good chance you just need to slightly change your commandline.

If you still think this is an issue with these builds specifically, please explain why and I'll re-open.
