### ISSUE TITLE
ffmpeg443: error while loading shared libraries: libmvec.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by scroot** [BtbN/FFmpeg-Builds#243]
ffmpeg443: error while loading shared libraries: libmvec.so.1: cannot open shared object file: No such file or directory

**Comment by JayeShen** [comment]
http://events.jianshu.io/p/825dc205227d

**Comment by JayeShen** [comment]
可能需要升级glibc

**Comment by BtbN** [comment]
What distribution are you using?
As per the Readme, the minimum glibc requirements are:

- linux64 (x86_64 Linux, glibc>=2.23, linux>=4.4)
- linuxarm64 (arm64 (aarch64) Linux, glibc>=2.27, linux>=4.15)
