### ISSUE TITLE
Please add ffmpeg 6.0 stable build

### ISSUE THREAD

**Issue by abcfy2** [BtbN/FFmpeg-Builds#244]
Nowadays ffmpeg 6.0 released. But download pages only contains ffmpeg 4.4 & 5.1 stable build, please also add ffmpeg 6.0 stable build.

Thanks.

**Comment by BtbN** [comment]
I haven't decided what to do yet.
Having 3 releases might be too much for the available asset space. So either 4.4 or 5.1 has to go.
It'd also make the download list even more of a mess as it already is.

Just use master for now, it's the same ABI version anyway.

**Comment by BtbN** [comment]
What do you want specifically a 6.0 build for?
As of right now, master and 6.0 are practically identical. So I see no rush.

**Comment by Barough** [comment]
The cut that v6.0 is made from is hopefully a lot more stable then the master. As you said..... As things is now the master and v6 is somewhat identical imo. But this is just my way of seeing things.

**Comment by hudrazine** [comment]
In my opinion, adding a build of 6.0 will make version management easier for users.

This is because the version information obtained by file or directory name and `ffmpeg -version` is more clearly version identifiable and verifiable with `n6.0-x-gxxxxxxxxxx` than with the master `N-xxxxxx-gxxxxxxxxxx`.

**Comment by hudrazine** [comment]
If asset space is a concern, I feel that we can drop 4.4 now that 5.0 has been released for a year and 5.1 is marked as LTS.

**Comment by BtbN** [comment]
The thing with 4.4 is, there's still a bunch of software that depends on its old ABI.
A potential idea I had was dropping all non-shared builds of the two older releases, but that might be too confusing for normal users who got no clue about ABI versions.
For now, 6.0 builds are part of the mix, and asset space seems to be sufficient and build times did not go too crazy.
So three releases might be where it's at for the future. Once 6.1 comes out, 6.0 will be dropped. And once 7.0 comes out, 4.4 will have to go.

I don't see how an ever increasing linear number is harder to understand than release numbers. And all of them contain the commit, which is as clear as it can get.

**Comment by ZaquL** [comment]
>The cut that v6.0 is made from is hopefully a lot more stable then the master

The FFmpeg devs mandate that only HEAD of master is stable. They do not do stable LTS releases yet, it is only planned.

**Comment by hudrazine** [comment]
@ZaquL As for 5.1 LTS, the [release notes](https://git.ffmpeg.org/gitweb/ffmpeg.git/blob/refs/heads/release/5.1:/RELEASE_NOTES) clearly state...

**Comment by ZaquL** [comment]
> @ZaquL As for 5.1 LTS, the [release notes](https://git.ffmpeg.org/gitweb/ffmpeg.git/blob/refs/heads/release/5.1:/RELEASE_NOTES) clearly state...

Yeah, nice! So they did it after all. That is good.

**Comment by BtbN** [comment]
The only thing that means is that this branch will receive backports of critical fixes for longer.
Since in the past, that was done for every single branch there was, and the maintenance burden got too much.
For normal usage outside of being a distro package maintainer, you should always use latest master.
