### ISSUE TITLE
[Regression/upstream] hevc_nvenc: B frames as references are not supported on Pascal

### ISSUE THREAD

**Issue by nyanmisaka** [BtbN/FFmpeg-Builds#245]
Upstream commit https://github.com/FFmpeg/FFmpeg/commit/28680e2f41b93b75863720e42397441dfcc29f94 causes a regression on Pascal GPU.

Maybe all pre-Turing GPUs (no b-frame) are affected too. A workaround is to disable it explicitly in master and 6.0. `-b_ref_mode 0`

Windows 10, Driver 528.24, GTX 1050

@BtbN Can't we query from NVENC API before setting the option?

```
./ffmpeg -f lavfi -i testsrc=s=1920x1080,format=nv12 -c:v hevc_nvenc -preset p1 -b:v 4M -maxrate 4M -f null -
```

```
[hevc_nvenc @ 000001debf9a0840] B frames as references are not supported
[hevc_nvenc @ 000001debf9a0840] No capable devices found
[vost#0:0/hevc_nvenc @ 000001debf9a0540] Error initializing output stream: Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!
```

**Comment by BtbN** [comment]
It's way too early to query anything when option defaults are being set.
The issue should be fixable, but it seems like a bug on Nvidias side to me, if their defaults include a mode the hardware does not support.

In any case, this is not an issue with these builds. Please report issues with FFmpeg on trac.

**Comment by nyanmisaka** [comment]
> It's way too early to query anything when option defaults are being set. The issue should be fixable, but it seems like a bug on Nvidias side to me, if their defaults include a mode the hardware does not support.
> 
> In any case, this is not an issue with these builds. Please report issues with FFmpeg on trac.

Thanks for your input! IMHO the fix is very straight forward:
```
From 8a27162d64464c2cba50a1e6f7c13bc57901c868 Mon Sep 17 00:00:00 2001
From: nyanmisaka <nst799610810@gmail.com>
Date: Sat, 4 Mar 2023 00:01:33 +0800
Subject: [PATCH] avcodec/nvenc: fix b_ref_mode capability check

fixes #28680e2
---
 libavcodec/nvenc.c | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/libavcodec/nvenc.c b/libavcodec/nvenc.c
index a8b7a4c0a0..6d0797bc3c 100644
--- a/libavcodec/nvenc.c
+++ b/libavcodec/nvenc.c
@@ -544,12 +544,12 @@ static int nvenc_check_capabilities(AVCodecContext *avctx)
     if (ctx->b_ref_mode == NV_ENC_BFRAME_REF_MODE_EACH && ret != 1 && ret != 3) {
         av_log(avctx, AV_LOG_WARNING, "Each B frame as reference is not supported\n");
         return AVERROR(ENOSYS);
-    } else if (ctx->b_ref_mode != NV_ENC_BFRAME_REF_MODE_DISABLED && ret == 0) {
+    } else if (ctx->b_ref_mode > 0 && ret == 0) {
         av_log(avctx, AV_LOG_WARNING, "B frames as references are not supported\n");
         return AVERROR(ENOSYS);
     }
 #else
-    if (ctx->b_ref_mode != 0) {
+    if (ctx->b_ref_mode > 0) {
         av_log(avctx, AV_LOG_WARNING, "B frames as references need SDK 8.1 at build time\n");
         return AVERROR(ENOSYS);
     }
-- 
2.34.1

```

**Comment by BtbN** [comment]
Nvidias own presets enable the mode, on hardware that doesn't support it.
All the patch you linked does is make ffmpeg stop overriding the preset-provided value unless the user explicitly requested so.

**Comment by ZaquL** [comment]
I think this was a bug that when b_ref_mode  is unset the check against HW capabilities does not happen. Cannot check, I only have Turing.

Fixed: https://github.com/FFmpeg/FFmpeg/commit/7a8560cb22dd9f5c54df71af3fef26db9a2a28b0
