### ISSUE TITLE
linux armhf or arm32

### ISSUE THREAD

**Issue by lucasmz1** [BtbN/FFmpeg-Builds#248]
can you provide for linux armhf or arm32 ?
thank you!!!

**Comment by BtbN** [comment]
No, sorry.
The amount of work I'd take to get stuff to build and work those platforms, and the poor performance you'd get on them, does not really make it worthwhile.

The list of builds is also already long enough, so if at all, it'd be the same deal was win32, which is "build at home"-only.
If someone wants to do the legwork on it, I'm happy to accept contributions as long as they don't make a giant mess to get stuff to build. But I won't invest any time into it myself.
