### ISSUE TITLE
Feat.req. Add update build flag / option

### ISSUE THREAD

**Issue by necros2k7** [BtbN/FFmpeg-Builds#249]
Can any update methods be implemented in subj. like in "yt-dlp -U" tool?

**Comment by BtbN** [comment]
Not sure what you're asking.
You want ffmpeg itself to be able to download a new version of itself?
Cause that ain't happening. FFmpeg does not endorse any specific binaries. It's only distributed as source.

**Comment by Danila2k8** [comment]
Yes that`s exactly what I meant, thanx for answer

**Comment by necros2k7** [comment]
> Not sure what you're asking. You want ffmpeg itself to be able to download a new version of itself? Cause that ain't happening. FFmpeg does not endorse any specific binaries. It's only distributed as source.

Yes
