### ISSUE TITLE
Why libx265 not up to date?

### ISSUE THREAD

**Issue by kydex** [BtbN/FFmpeg-Builds#250]
I checked build 2023-03-17 and libx265 version is 3.5+86, while AFAIK latest version is 3.5+96, at least GyanD build have it.
I want to use your ffmpeg builds, and I would like have latest libx265.
Do you have any reason for outdated version or it just not updated yet?

**Comment by BtbN** [comment]
I don't update dependencies every single day, that'd get out of hand way too fast.
Any specific feature in libx265 you're looking for?
Normally I do one run of updates every month, and it usually takes a whole day of work to straighten out all issues it causes.

**Comment by kydex** [comment]
I don't looking any specific feature in libx265 right now. I work with x265 every day, sometimes it has important bug fixes or new features and I just want have less delay for getting it.
However if it takes a lot of time to keep up to date, I guess I can live with one month update period.
Thank you for quick response, very grateful for your work.

**Comment by BtbN** [comment]
You can always build yourself and bump any packages you care about.

**Comment by kydex** [comment]
Thank you! Your instruction looks not very complicated, so I will try to build.

**Comment by ZaquL** [comment]
Did you consider that FFmpeg may need to be updated to support new x265 versions?

**Comment by ZaquL** [comment]
> > Did you consider that FFmpeg may need to be updated to support new x265 versions?
> 
> I don't understand what you mean unfortunately. My question was why libx265 has slightly outdated version compared to other FFmpeg builds.

There is no garantee newer versions will just work with ffmpeg without patches to ffmpeg.

**Comment by BtbN** [comment]
That's not how libraries work. Offering a stable interface is the whole point, and API breaks are rare exceptions that cause a SONAME bump.
Why are you bumping up a bunch of closed issues anyway?

**Comment by ZaquL** [comment]
>Offering a stable interface is the whole point, and API breaks are rare exceptions that cause a SONAME bump.

That is only assuming FFmpeg is using API of it correctly.

>Why are you bumping up a bunch of closed issues anyway?

Silent bug fix in https://github.com/BtbN/FFmpeg-Builds/issues/245 :)
