### ISSUE TITLE
How to get latest build?

### ISSUE THREAD

**Issue by kydex** [BtbN/FFmpeg-Builds#252]
There were "latest" builds with static links, and last few days I cant get it.
No more static links?

**Comment by BtbN** [comment]
Not sure what you mean exactly.

Every build produces a release with the specific date in it, which will always refer to that release specific: https://github.com/BtbN/FFmpeg-Builds/releases/tag/autobuild-2023-03-24-12-46
And a "floating" latest release, so there are unchanging links that always point to the latest build: https://github.com/BtbN/FFmpeg-Builds/releases/tag/latest

There is a short period each day where the build workflow deletes the old latest tag, and then uploads the new one.
This usually takes less than a minute to complete though. So if you ever saw a lack of a latest tag, you must have hit exactly those few seconds of the day.

While it's re-packing the assets for the latest-tag, that tag is also temporarily a day behind the already released date-based build, but the links still work, and just keep being yesterdays build. The re-packing takes almost an hour now, so there's quite a bit of a time each day where the "latest"-Tag is not the latest build, but second in the list.

There isn't anything I can sensibly change about that process. Other than artificially delaying the date based release, but that seems unnecessary.

**Comment by kydex** [comment]
I know about delay. It's strange, I checked many times yesterday and today and there were no latest builds at all. 
Also this command was getting me error "404 Not Found".
wget "https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip"

But now I can see "latest" releases and wget work well. Anyway, thanks for reply and sorry for disturbing.

**Comment by youcmd** [comment]
it's gone again https://github.com/BtbN/FFmpeg-Builds/releases/tag/latest
https://i.imgur.com/mmEOqRz.png

**Comment by BtbN** [comment]
https://github.com/BtbN/FFmpeg-Builds/actions/runs/4532195209/jobs/7983553567#step:5:12398 the release was created successfully and all assets were attached.
So this must be on the end of Github, and there is nothing I can do about it.

**Comment by pzhlkj6612** [comment]
Recently I experienced the same issue when releasing new version with artifacts. I tried sleeping 60 seconds after deleting the old release and before making the new one, and it works until now.
