### ISSUE TITLE
FFMPEG_REPO_OVERRIDE and GIT_BRANCH_OVERRIDE

### ISSUE THREAD

**Issue by brycechesternewman** [BtbN/FFmpeg-Builds#253]
Hello,
I have a need to use a ffmpeg mirrored repository that is an internal gitlab repository. The reason for the override is we have some custom code that has not been approved to merge into FFmpeg master branch. It appears I could set an environment variable for FFMPEG_REPO_OVERRIDE and GIT_BRANCH_OVERRIDE to my internal repository/branch?

A separate question and somewhat related since I have not gotten as far as FFMPEG_REPO_OVERRIDE and GIT_BRANCH_OVERRIDE. Since we need to use our own ffmpeg repo, I am having a problem running ./makeimage.sh linuxarm64 gpl on 22.3.0 Darwin Kernel. I do have the latest bash version, but I run into other problems with build.sh as well using bash on Mac.

i.e.
```
./makeimage.sh linuxarm64 gpl  
++ dirname ./makeimage.sh
+ cd .
+ source util/vars.sh
++ [[ 2 -lt 2 ]]
++ TARGET=linuxarm64
++ VARIANT=gpl
++ shift 2
++ [[ -f variants/linuxarm64-gpl.sh ]]
++ LICENSE_FILE=COPYING.LGPLv2.1
++ ADDINS=()
++ ADDINS_STR=
++ [[ 0 -gt 0 ]]
++ REPO=btbn/ffmpeg-builds
util/vars.sh: line 34: ${REPO,,}: bad substitution
```

I have tried to `docker run -it -v ubuntu:20.04 bash`, download this project and run ./makeimage.sh, but that failed with docker not found. I install docker on ubuntu:20.04 and then can't start it so the makeimage.sh fails with `Cannot connect to the Docker daemon at unix:///var/run/docker.sock` and I can't start docker within docker. I am sort of stuck on how best to run ./makeimage.sh linuxarm64 gpl and ./buildl.sh linuxarm64 gpl in - for example - a .gitlab-ci.yml. Do you have any suggestions?
Thank you.

**Comment by BtbN** [comment]
Those variables do what their names suggest, yes.

Not sure what to tell you for your other questions.
To run the build scripts, you need a working docker setup, since the entire build makes extensive use of it.
If you get that cannot connect error, you just don't have a working docker daemon.

And that "bad substitution" error looks like you're trying to run this with not-bash? Or some very old version of bash.

**Comment by brycechesternewman** [comment]
On Mac the bash shell is. Which is the most recent I can get.
```
bash-5.2$ bash -version
GNU bash, version 5.2.15(1)-release (x86_64-apple-darwin22.1.0)
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by BtbN** [comment]
The ",," substitution for lower-case is supported since bash 4.0.
So not sure what Apple did there, but something is seriously broken in their bash if they removed that.
I'd strongly suggest using Linux for this, since Docker is exclusively Linux already anyway.

**Comment by brycechesternewman** [comment]
I see what the issue with with bash. The newer version of bash is in /usr/local/bin/bash and scripts use /bin/bash. The latter is normal, so not checking that. Unfortunately with Apple I can not delete the /bin/bash and sym link /usr/local/bin/bash without doing to hacks to bypass security. I agree Linux is better for this and have tried but still having issues where I can't run `docker run -it -v ubuntu:20.04` and run docker inside or docker even when I use these instructions https://docs.docker.com/engine/install/ubuntu/. You have answered my initial question and I thank you. The issue with trying to run docker in docker ubuntu:20.04 is perhaps not relevant here, so we can probably close this issue unless someone has run into a simliar issue and solved it.

**Comment by BtbN** [comment]
I never tried, but I don't think you can run docker inside of docker?
The cgroup magic just does not allow that.
What you can do, on Linux at least, is start a docker container, and bind-mount the /run/docker.sock into it, giving it full access to the hosts docker demon.
No idea how to do that on a Mac though. I doubt you can bind-mount sockets into the Linux VM.

**Comment by brycechesternewman** [comment]
docker:dind is a solution. Though the only issue appears to be with mktemp.

```
++ IMAGE=ghcr.io/btbn/ffmpeg-builds/linuxarm64-gpl:latest
++ mktemp --suffix=.toml
mktemp: unrecognized option: suffix=.toml
BusyBox v1.35.0 (2022-11-19 10:13:10 UTC) multi-call binary.

Usage: mktemp [-dt] [-p DIR] [TEMPLATE]

Create a temporary file with name based on TEMPLATE and print its name.
TEMPLATE must end with XXXXXX (e.g. [/dir/]nameXXXXXX).
Without TEMPLATE, -t tmp.XXXXXX is assumed.

	-d	Make directory, not file
	-q	Fail silently on errors
	-t	Prepend base directory name to TEMPLATE
	-p DIR	Use DIR as a base directory (implies -t)
	-u	Do not create anything; print a name

Base directory is: -p DIR, else $TMPDIR, else /tmp
+ TMPCFG=
```
I appear to be able to work around this be using `TMPCFG="$(mktemp)"`. Is the suffix required?
