### ISSUE TITLE
stat: cannot stat 'uidtestfile': No such file or directory

### ISSUE THREAD

**Issue by brycechesternewman** [BtbN/FFmpeg-Builds#254]
Hello,
Using docker:latest/docker:dind Linux(BusyBox), with updated GNU packages I have been able to successfully execute `makeimage.sh linuxarm64 gpl 6.0`, but when `build.sh linuxarm64 gpl 6.0` executes the build fails on the finding the uidtestfile file.

The script is this.
```
     apk --no-cache --update-cache add --upgrade bash coreutils sed
     wget https://github.com/BtbN/FFmpeg-Builds/archive/refs/tags/latest.zip
     unzip latest.zip
     cd FFmpeg-Builds-latest
     ./makeimage.sh linux64 gpl 6.0 2> linux64.log
     ./build.sh linux64 gpl 6.0 2>> linux64.log
```

Output is this.
```
...
enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --disable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi'
++ xargs
+ FF_CFLAGS=-DLIBTWOLAME_STATIC
++ xargs
+ FF_CXXFLAGS=
++ xargs
+ FF_LDFLAGS=-pthread
++ xargs
+ FF_LDEXEFLAGS=-pie
++ xargs
+ FF_LIBS='-ldl -lgomp'
+ TESTFILE=uidtestfile
+ rm -f uidtestfile
+ docker run --rm -v /builds/digitalassetmanagement/forks/ffmpeg/FFmpeg-Builds-latest:/uidtestdir ghcr.io/btbn/ffmpeg-builds/linuxarm64-gpl-6.0:latest touch /uidtestdir/uidtestfile
++ stat -c %u uidtestfile
stat: cannot stat 'uidtestfile': No such file or directory
+ DOCKERUID=
```

I confirmed `/builds/digitalassetmanagement/forks/ffmpeg/FFmpeg-Builds-latest` directory does exist. The code calls `"$(stat -c "%u" "$TESTFILE")"`, so doesn't this need to be `"$(stat -c "%u" "$PWD/$TESTFILE")"?

**Comment by BtbN** [comment]
No it doesn't, the file is created in /uidtestdir which is mounted as a volume from $PWD, so the testfile will always be created in the current working dir.
I can't think of a good reason why this would not work for you. Something must be broken with your docker install, making it fail to bind-mount the directory while simultaneously still completing successfully.

**Comment by brycechesternewman** [comment]
Yah. It is strange. The Docker version is 23.0.2, build 569dd73. I am sort of at a loss as to why docker is able to run for makeimage.sh, but can't write that file.
i.e.
```
...
+ docker container inspect ffbuildreg
+ docker run --rm -d -p 127.0.0.1:0:5000 --name ffbuildreg registry:2
++ docker container inspect '--format={{range $p, $conf := .NetworkSettings.Ports}}{{(index $conf 0).HostPort}}{{end}}' ffbuildreg
+ LOCAL_REG_PORT=49155
+ LOCAL_ROOT=127.0.0.1:49155/local
+ trap 'rm -f '\''/tmp/tmp.rlzQp8iydo.toml'\''; docker container stop ffbuildreg' EXIT
+ grep 'FROM.*base.*' images/base-linux64/Dockerfile
+ docker buildx --builder ffbuilder build --cache-from=type=local,src=.cache/ghcr.io/btbn/ffmpeg-builds/base_latest --cache-to=type=local,mode=max,dest=.cache/ghcr.io/btbn/ffmpeg-builds/base_latest --push --tag 127.0.0.1:49155/local/base:latest images/base
#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 1.23kB done
#1 DONE 0.0s
...
```

**Comment by BtbN** [comment]
This isn't running on Windows/OSX or something, where bind mounts aren't a native thing, is it?
I could see those OS doing some nonsense and breaking stuff.

**Comment by brycechesternewman** [comment]
It's linux. I am probably running into this issue https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#known-issues-with-docker-in-docker. Though I can't seem to get it to work yet with $PWD:/uidtestdir

**Comment by brycechesternewman** [comment]
The problem is running docker in docker in a gitlab runner. gitlab-ci is not mounting the same location as the /uidtestdir/uidtestfile, so the uidtestfile is never found. I might need to fork this repo so I don't require using `docker run -v...`

**Comment by BtbN** [comment]
The build itself also relies on volumes working to actually get the build artifacts out of the container.
If your docker install is broken and volumes do not work, I'm afraid you won't be able to properly use this.
I have trouble imagining Gitlab does not properly support running docker, so you must be missing something obvious?

**Comment by brycechesternewman** [comment]
We have no issues running gitlab and running docker unless the -v option is used. Mimicking what the build.sh does for the uidtestfile the file ends up in a different directly. This is a known issue  https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#known-issues-with-docker-in-docker and the work arounds don't work unless the runners share the mounts and we don't have control over the ci-runners. One option that could work is we `docker cp...` form the FFMBuilds container - which would require removing the --rm and add --name for the `docker run --rm -v $PWD:/uidtestdir...` in the build.sh - that would work since we can copy out the files from the container to the correct directory. 

```
build:
  image: docker:23.0.2
  before_script:
    - ls -l $PWD
    - echo $PWD
    - docker run --rm -v $PWD:/uidtestdir ghcr.io/btbn/ffmpeg-builds/linuxarm64-gpl-6.0:latest ls -l /uidtestdir
    - docker run --rm -v $PWD:/uidtestdir ghcr.io/btbn/ffmpeg-builds/linuxarm64-gpl-6.0:latest touch /uidtestdir/uidtestfile
    - stat -c %u uidtestfile
```

```
$ echo $PWD
/builds/digitalassetmanagement/forks/ffmpeg
$ ls -l $PWD
total 688
-rw-rw-rw-  1 root root    418 Apr  4 13:24 CONTRIBUTING.md
-rw-rw-rw-  1 root root  18092 Apr  4 13:24 COPYING.GPLv2
-rw-rw-rw-  1 root root  35147 Apr  4 13:24 COPYING.GPLv3
-rw-rw-rw-  1 root root  26526 Apr  4 13:24 COPYING.LGPLv2.1
-rw-rw-rw-  1 root root   7651 Apr  4 13:24 COPYING.LGPLv3
-rw-rw-rw-  1 root root    274 Apr  4 13:24 CREDITS
-rw-rw-rw-  1 root root  68884 Apr  4 13:24 Changelog
-rw-rw-rw-  1 root root    432 Apr  4 13:24 Dockerfile
-rw-rw-rw-  1 root root    596 Apr  4 13:24 INSTALL.md
-rw-rw-rw-  1 root root   4376 Apr  4 13:24 LICENSE.md
-rw-rw-rw-  1 root root  31303 Apr  4 13:24 MAINTAINERS
-rw-rw-rw-  1 root root   6549 Apr  4 13:24 Makefile
-rw-rw-rw-  1 root root   1810 Apr  4 13:24 README.md
-rw-rw-rw-  1 root root      4 Apr  4 13:24 RELEASE
-rw-rw-rw-  1 root root    887 Apr  4 13:24 RELEASE_NOTES
drwxrwxrwx 11 root root    248 Apr  4 13:24 compat
-rwxrwxrwx  1 root root 272037 Apr  4 13:24 configure
drwxrwxrwx  5 root root   4096 Apr  4 13:24 doc
drwxrwxrwx  2 root root    160 Apr  4 13:24 ffbuild
drwxrwxrwx  2 root root   4096 Apr  4 13:24 fftools
drwxrwxrwx 16 root root  49152 Apr  4 13:24 libavcodec
drwxrwxrwx  3 root root   4096 Apr  4 13:24 libavdevice
drwxrwxrwx  9 root root  20480 Apr  4 13:24 libavfilter
drwxrwxrwx  3 root root  20480 Apr  4 13:24 libavformat
drwxrwxrwx 14 root root   8192 Apr  4 13:24 libavutil
drwxrwxrwx  2 root root    262 Apr  4 13:24 libpostproc
drwxrwxrwx  6 root root   4096 Apr  4 13:24 libswresample
drwxrwxrwx  9 root root   4096 Apr  4 13:24 libswscale
drwxrwxrwx  2 root root    158 Apr  4 13:24 presets
drwxrwxrwx  7 root root   4096 Apr  4 13:24 tests
drwxrwxrwx  3 root root   4096 Apr  4 13:24 tools
$ docker run --rm -v $PWD:/uidtestdir ghcr.io/btbn/ffmpeg-builds/linuxarm64-gpl-6.0:latest ls -l /uidtestdir
total 0
-rw-r--r-- 1 root root  0 Apr  4 13:55 uidtestfile
$ docker run --rm -v $PWD:/uidtestdir ghcr.io/btbn/ffmpeg-builds/linuxarm64-gpl-6.0:latest touch /uidtestdir/uidtestfile
$ stat -c %u uidtestfile
stat: cannot stat 'uidtestfile': No such file or directory
```

**Comment by brycechesternewman** [comment]
Going to close this. The issue with the gitlab runner and docker -v is really not an issue with this project.
