### ISSUE TITLE
unable to access 'https://github.com/FFmpeg/FFmpeg.git/'

### ISSUE THREAD

**Issue by blogwy** [BtbN/FFmpeg-Builds#257]
./build.sh win64 gpl 5.1

```bash
...
...
...
+ docker run --rm -i -t -u 1000:1000 -v /home/norman/Desktop/code/FFmpeg-Builds/ffbuild:/ffbuild -v /tmp/tmp.I67W2KulE1:/build.sh ghcr.io/btbn/ffmpeg-builds/win64-gpl-5.1:latest bash /build.sh
+ cd /ffbuild
+ rm -rf ffmpeg prefix
+ git clone --filter=blob:none --branch=release/5.1 https://github.com/FFmpeg/FFmpeg.git ffmpeg
Cloning into 'ffmpeg'...
fatal: unable to access 'https://github.com/FFmpeg/FFmpeg.git/': Could not resolve host: github.com
+ rm -f -- /tmp/tmp.I67W2KulE1
```

os: ubuntu 22.04.2
Docker version: 23.0.4, build f480fb1
GNU bash version: 5.1.16(1)-release (x86_64-pc-linux-gnu)

It was working fine yesterday, but not today. I run git clone --filter=blob:none --branch=release/5.1 https://github.com/FFmpeg/FFmpeg.git ffmpeg alone by myself, it is normal. But running build.sh gives an error

**Comment by BtbN** [comment]
That looks like an issue with your internet connection to me.
If it works outside of docker, something with dockers network setup must be broken.

**Comment by blogwy** [comment]
It may be my vmware virtual machine problem, I reset the vmware network, it can work
