### ISSUE TITLE
What build previous version run with driver 470 ?

### ISSUE THREAD

**Issue by Augusto7743** [BtbN/FFmpeg-Builds#259]
Hello.
Thanks for reading my topic.

Trying use the current build version not have hardware acceleration.
Here Ubuntu Linux 20.04.6 using geforce 600 series driver 470.
Perhaps is being required use updated drivers.

What build previous version have compatibility with driver 470 ?

Have an nice week.

**Comment by BtbN** [comment]
4.4, 5.0 and 5.1 are built with legacy ffnvcodec versions which support driver version 471.41 and higher.
master is always built against the latest codec headers, which currently need driver 522.25 or newer.

**Comment by Augusto7743** [comment]
You are saying is possible tweak the build script to run ffmpeg 6 in driver 470 ?
Is an simple task ?
I am an Linux novice user.

The file below run in driver 470 ?
https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n5.1-latest-linux64-gpl-5.1.tar.xz

**Comment by BtbN** [comment]
You can build any version of ffmpeg with any version of the headers.
But obviously not multiple at a time, so a choice has to be made there.
Latest versions -> latest drivers
Old versions -> older drivers

If you want a different combination, you'll have to make a custom build yourself.
Nvidias documentation says 471.41 is the oldest supported driver for the 11.1 Video Codec headers, so you might have to update your driver a bit.

**Comment by BtbN** [comment]
None of them are compatible with 470. 471 should work though, and is a supported legacy driver for your old card.
Any 5.1 or 4.4 build will work with driver 471 or newer.

**Comment by Augusto7743** [comment]
The nvidia headers are in nvidia binary driver and distro driver PPA or in ffmpeg git source ?

**Comment by BtbN** [comment]
Not sure what you're asking.
If you want to make a custom build that uses a specific version, you got to modify the ffnvcodec script in this very repo.
