### ISSUE TITLE
"FFmpeg(64bit Static Builds)" ..?

### ISSUE THREAD

**Issue by puppiescouts** [BtbN/FFmpeg-Builds#261]
hello... sorry, im new, and am not sure if this is where i ask this question but im having a hard time trying to find this specific ffmpeg...
im looking for "FFmpeg(64bit Static Builds)" for windows or the one that is compatible with animeeffects, http://animeeffects.org/en/?page_id=6
i was wondering if anyone was familiar with it or the ffmpeg it used. they linked the ffmpeg on their page but the ffmpeg is blocked for some reason
sorry if this is a stupid question, this is the first time iver ever even heard of ffmpeg. it appears there are a lot more ffmpeg downloads than i thought

**Comment by BtbN** [comment]
Any version you can execute should work for that. But I never used that software, so you might be better off asking in their support channels.
