### ISSUE TITLE
zimg is error

### ISSUE THREAD

**Issue by cherrynechou** [BtbN/FFmpeg-Builds#262]
zimg  every time is build error

**Comment by BtbN** [comment]
Please elaborate.

**Comment by cherrynechou** [comment]
![image](https://user-images.githubusercontent.com/4892608/235302137-70fc3eba-e0ad-4bfe-a5b6-f984a18bd88e.png)

**Comment by cherrynechou** [comment]
![image](https://user-images.githubusercontent.com/4892608/235302586-dbd3bd1d-cc9f-4354-9c5c-2c2376703263.png)

error

**Comment by BtbN** [comment]
That looks like some kind of internet issue on your end, or an intermittent hickup on Github.
The commit exists on the googletest repo, and it fetches just fine for me.
Have you tried just trying it again?

**Comment by cherrynechou** [comment]
ok
