### ISSUE TITLE
Add libsvt_hevc encoder

### ISSUE THREAD

**Issue by galstudio** [BtbN/FFmpeg-Builds#267]
Please add the libsvt_hevc encoder to the assembly. The patch is here https://github.com/OpenVisualCloud/SVT-HEVC/tree/master/ffmpeg_plugin

**Comment by BtbN** [comment]
Again, I do not add any patches on top of ffmpeg by principle (and by maintenance burden).
Please submit any features you'd like added to ffmpeg upstream.
