### ISSUE TITLE
will you please support VVenC and VVdeC and vvc path with ffmpeg6 compile?

### ISSUE THREAD

**Issue by logitechlike** [BtbN/FFmpeg-Builds#269]
https://github.com/fraunhoferhhi/vvenc/wiki/FFmpeg-Integration#using-latest-ffmpeg-release-60
please add VVenC and VVdeC compile
and patch for ffmpeg6.

**Comment by BtbN** [comment]
Again: No third party patches. If you want support for a new feature in ffmpeg, submit your patches upstream.
