### ISSUE TITLE
Why disable-libmfx in Win64 lgpl shared?

### ISSUE THREAD

**Issue by huangjinshe** [BtbN/FFmpeg-Builds#271]
If you disable libmfx, how do we hardware acceleration for decoding? Or is that using gpl license??

**Comment by BtbN** [comment]
Not sure what you mean, there is no license check in either the mfx or onevpl script.

**Comment by huangjinshe** [comment]
So why did you disable it from [win64-lgpl-6.0.zip](https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2023-05-14-12-49/ffmpeg-n6.0-18-g27205c0b47-win64-lgpl-6.0.zip) ? If you disable it when compile, we can't use it.

> ffplay version n6.0-18-g27205c0b47-20230514 Copyright (c) 2003-2023 the FFmpeg developers
>   built with gcc 12.2.0 (crosstool-NG 1.25.0.152_89671bf)
>   configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-version3 --disable-debug --enable-shared --disable-static --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-libaribb24 --disable-avisynth --enable-chromaprint --enable-libdav1d --disable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --disable-frei0r --enable-libgme --enable-libkvazaar --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --disable-libmfx --enable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --disable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --disable-vaapi --disable-libvidstab --enable-vulkan --enable-libshaderc --disable-libplacebo --disable-libx264 --disable-libx265 --disable-libxavs2 --disable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20230514

**Comment by BtbN** [comment]
Because it got superseded by libvpl.
