### ISSUE TITLE
ffmpeg libraries 32 bits

### ISSUE THREAD

**Issue by agustinvaquero** [BtbN/FFmpeg-Builds#274]
I have found what I need at https://github.com/BtbN/FFmpeg-Builds/releases
Buat all of this releases are in 64 bits architecture
Is posible Obtain the same build but at 32 bit configuration.

I Have read the compilation instructions but I don´t know at which bash is referenced and the docker (how it isntall It in Windows 10 ¿?)

It could be a great help to me, to obtain a ".sln" solution at Microsoft Visual C++ 2017 Solution project...
The final purpose for me is obtain the libs:  avcodec.lib avdevice.lib avfilter.lib avformat.lib avutil.lib postproc.lib swresample.lib swscale.lib for compile whit my project under windows 10. but in 32 bits !!
Thank you very mutch.

**Comment by BtbN** [comment]
I use gcc for all builds, so you will never end up with any Visual Studio stuff.
To produce a 32 bit build yourself, just follow the two commands outlines in the readme.
All you need, in theory, is bash and docker. Ideally on Linux, people had weird things happen with gitbash/cygwin before. WSL works fine.

**Comment by agustinvaquero** [comment]
Sorry I don´t know, what is docker. I´m using windows 10. Is posible install docker on windows 10 ?

**Comment by BtbN** [comment]
Yes, but you'll still need to go via WSL to do the actual building.

**Comment by agustinvaquero** [comment]
It´s posible do it by "MSYS2 MINGW64" ?

**Comment by BtbN** [comment]
Someone recently had issues with that, I'm only testing WSL and actual Linux, so I'd recommend either of those.

**Comment by agustinvaquero** [comment]
ok... i´m installing WSL system now...

**Comment by agustinvaquero** [comment]
So, when i have the ubuntu installed, I have to install the docker too, Or is that linux the docker itself?

**Comment by agustinvaquero** [comment]
If I execute the commnad ./makeimage.sh win32 lgpl I obtain and error: >>
++ dirname ./makeimage.sh
+ cd .
+ source util/vars.sh
++ [[ 2 -lt 2 ]]
++ TARGET=win32
++ VARIANT=lgpl
++ shift 2
++ [[ -f variants/win32-lgpl.sh ]]
++ LICENSE_FILE=COPYING.LGPLv2.1
++ ADDINS=()
++ ADDINS_STR=
++ [[ 0 -gt 0 ]]
++ REPO=btbn/ffmpeg-builds
++ REPO=btbn/ffmpeg-builds
++ REGISTRY=ghcr.io
++ BASE_IMAGE=ghcr.io/btbn/ffmpeg-builds/base:latest
++ TARGET_IMAGE=ghcr.io/btbn/ffmpeg-builds/base-win32:latest
++ IMAGE=ghcr.io/btbn/ffmpeg-builds/win32-lgpl:latest
++ mktemp --suffix=.toml
+ TMPCFG=/tmp/tmp.3jDPbwovpn.toml
+ cat
+ trap 'rm -f '\''/tmp/tmp.3jDPbwovpn.toml'\''' EXIT
+ docker buildx inspect ffbuilder
+ docker buildx create --bootstrap --name ffbuilder --config /tmp/tmp.3jDPbwovpn.toml --driver-opt network=host --driver-opt env.BUILDKIT_STEP_LOG_MAX_SIZE=-1 --driver-opt env.BUILDKIT_STEP_LOG_MAX_SPEED=-1
./makeimage.sh: line 13: docker: command not found

**Comment by agustinvaquero** [comment]
So I Supose that i have to install this... https://docs.docker.com/desktop/windows/wsl/

**Comment by agustinvaquero** [comment]
ok. under WSL (ubuntu inside windows)
I go to the source folder >> agus@ASUSAGUSGTX:/mnt/c/desagl/ffmpeg/ffmpeg-builds-latest
and execute                     >> sudo ./makeimage.sh  win32 gpl   (It works....It takes a long long time... hours...)
then I execute                  >> sudo ./build.sh win32 gpl (It Works... but not produce zip file)

Finally I Obtain this message

+ [[ -n COPYING.GPLv3 ]]
+ cp ffbuild/ffmpeg/COPYING.GPLv3 ffbuild/pkgroot/ffmpeg-N-110664-g2838138975-win32-gpl/LICENSE.txt
+ cd ffbuild/pkgroot
+ [[ win32 == win* ]]
+ OUTPUT_FNAME=ffmpeg-N-110664-g2838138975-win32-gpl.zip
+ zip -9 -r /mnt/c/desagl/ffmpeg/ffmpeg-builds-latest/artifacts/ffmpeg-N-110664-g2838138975-win32-gpl.zip ffmpeg-N-110664-g2838138975-win32-gpl
./build.sh: line 93: zip: command not found
+ rm -f -- /tmp/tmp.ND1J9t0niC


So I don´t have zip file at the artifacts folder... because zip is not installed

But i am looking for *.lib libraries for my project in windows and  I can´t find Them
Only at this folder C:\DesaGL\ffmpeg\FFmpeg-Builds-latest\ffbuild\prefix\lib I have libs.a but I need Libs.lib for the win 32 visual studio project

Thank you

**Comment by BtbN** [comment]
Just throw in the shared addin (just append it to the command line) for both the image build process and the actual ffmpeg build.
But again, I can't promise if old Visual Studio can do anything useful with that.

**Comment by agustinvaquero** [comment]
Ok, I will try It, and Tell you later...

**Comment by agustinvaquero** [comment]
So.... 

I have the zip File for 32 Bits... 
Inside It...
   I have the libs for 32 Bits
   I have the dlls for 32 Bits
I´ve included properly in my opengl Microsoft Visual Studio 2017 .sln project
And IT WORKS PERFECTLY

Thanks !!
