### ISSUE TITLE
Call out whether this is official or not in the readme?

### ISSUE THREAD

**Issue by Pomax** [BtbN/FFmpeg-Builds#277]
It would be quite useful to know whether this is the official binaries release location, with a link to the relevant section about that on the ffmpeg website if it is, so that people can be confident that the downloads aren't just "a random person who set up a compile repo but can't actually be trusted". 

(even if the ffmpeg site already links here, the readme would need a link back so folks can verify if they land here first)

**Comment by BtbN** [comment]
There are no official FFmpeg binaries. FFmpeg only distributes its sourcecode.

**Comment by Pomax** [comment]
Except there are, because https://ffmpeg.org/download.html literally links here, so the README.md should probably link back.

**Comment by BtbN** [comment]
That's just a collection of links for convenience. None of them are in any way official.
Due to the general patent situation, the FFmpeg project cannot offer official binaries.
And I will not start claiming to be "official" when there is no such thing as official binaries.

**Comment by Pomax** [comment]
Fair enough, but at least linking back to the download page so that folks can verify that, indeed, you're not some random repo pretend to serve binaries that are actually just malware or worse, would still be a _good_ idea.
