### ISSUE TITLE
ffmpeg cannot find the program input point vkBindImageMemory 2

### ISSUE THREAD

**Issue by w0853** [BtbN/FFmpeg-Builds#28]
I want to install ffmpeg, cmd executes ffmpeg -version, and then ran out of this window (I found that ffmpeg was changed to an English path and directly clicked on ffmpeg.exe, and the result will run out of this window)

https://answers.microsoft.com/zh-hant/windows/forum/windows_10-hardware/%E5%A6%82%E4%BD%95%E4%BF%AE%E5%BE%A9/716b4fed-3de3 -4e61-8700-98521ebea273

I executed

Windows+X select A and enter the following command,

DISM /Online /Cleanup-Image /RestoreHealth

cmd.exe /c "for %1 in (%windir%\system32\*.dll) do regsvr32.exe /s %1" 

Try again from boot.

But still not resolved

Can ask what to do to solve

Problems with dynamic link libraries
Normally, ffmpeg -version should run out of information

could you tell me how do I do it?

![ffmpeg2](https://user-images.githubusercontent.com/57361016/100542460-f3114800-3284-11eb-9c5d-7bd7bd809967.png)

**Comment by BtbN** [comment]
Either install a properly working Vulkan-Capable graphics driver, or download a non-vulkan variant.
That's the exact reason it's its own variant.
