### ISSUE TITLE
build.sh requires zip to be installed on local OS

### ISSUE THREAD

**Issue by pjt-15e** [BtbN/FFmpeg-Builds#284]
1st thanks for creating "FFmpeg-Builds".

I found that when using your scripts and docker image to cross compile a win64 version of ffmpeg that the "build.sh" script didn't place anything into the "artifacts" folder.  Reviewing bash's output "build.sh" failed when it was unable to zip any of the ffmpeg files - zip wa missing.  The local OS used was Ubuntu server 22.04.  After installing "zip" and re-running "./build.sh win64 nonfree" it worked.  

So this isn't really an issue with your "FFmpeg-Builds", but perhaps something to add to the prerequisites that "zip" is also needed for win32/64 builds?

Thanks again.

**Comment by pzhlkj6612** [comment]
FWIW, the code is:

https://github.com/BtbN/FFmpeg-Builds/blob/c07b573acd10e813c500ed50f4ceeee9cd819b04/build.sh#L91-L93
