### ISSUE TITLE
Add ability to pass arbitrary extra encoder settings

### ISSUE THREAD

**Issue by m9IsKoN** [BtbN/FFmpeg-Builds#287]
Hello, I could not create a question in your obs-multi-rtmp fork, tell me how to specify Extra Options correctly?

**Comment by BtbN** [comment]
Lines of
```
integer_option_name:i=1234
string_option_name:s=blabla
double_option_name:d=1.5
false_bool_option_name:b=0
true_bool_option_name:b=1
```
For the option names you will have to dig into the source of the respective encoder you are setting them on.

**Comment by m9IsKoN** [comment]
Thank you

**Comment by m9IsKoN** [comment]
> Lines of
> 
> ```
> integer_option_name:i=1234
> string_option_name:s=blabla
> double_option_name:d=1.5
> false_bool_option_name:b=0
> true_bool_option_name:b=1
> ```
> 
> For the option names you will have to dig into the source of the respective encoder you are setting them on.

I tried different variations, but unfortunately I didn't succeed, could you show me an example of any codec and any variable, so that I could understand how it should work, if it doesn't bother you?

**Comment by BtbN** [comment]
`preset2:s=p7` to set the preset of nvenc for example.

**Comment by m9IsKoN** [comment]
Should the changes be displayed in the log when the broadcast starts?
![Screenshot 2023-07-27 041645](https://github.com/BtbN/FFmpeg-Builds/assets/108962211/f54ef088-4b26-4077-a104-62e205ae3ada)
![Screenshot 2023-07-27 041741](https://github.com/BtbN/FFmpeg-Builds/assets/108962211/0e04511b-17e9-4dc8-b11f-64d5d8b4a3bb)

**Comment by BtbN** [comment]
Yes
