### ISSUE TITLE
get error when compile win64-verison-ffmpeg in centos?

### ISSUE THREAD

**Issue by akingbrDu** [BtbN/FFmpeg-Builds#288]
in centos use command: ./build.sh win64 gpl-shared 6.0 get error:
first time:
 ... x86_64-w64-mingw32/bin/ld: cannot find -ldl: No such file or directory  

how fix the error?it seems to some bad things happen in win docker.

thanks a lot

**Comment by BtbN** [comment]
Please provide more logs and information on how you ended up in that situation.
The builds work fine for me locally and on actions.
It not finding -ldl on windows-builds makes sense, that's a Linux-Library and doesn't exist on Windows.

**Comment by akingbrDu** [comment]
I don't know very well about how to compile for window-ffmpeg-builds actually without doc,  and I only success to compile for linux-ffmpeg-builds. From what I understand now, I guess the whole process is to download the window-docker-image first, and then try to compile it in the container; below are my compilation steps:

[1]. git clone code in centos7
[2]. ./build.sh win64 gpl-shared 6.0
[3]. the script stops when it executes the ffmpeg cofigure test, like below:

+ ./configure --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --enable-shared --disable-static --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-chromaprint --enable-libdav1d --enable-libdavs2 --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= '--extra-libs=-ldl -lgomp' --extra-version=20230807
x86_64-w64-mingw32-gcc is unable to create an executable file.
C compiler test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.libera.chat.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.

-------------------------------------------------------------------------------------------------------------------------------
I went to config.log to check bug report, it shows:

BEGIN /tmp/ffconf.eyQyRlM4/test.c
    1   int main(void){ return 0; }
END /tmp/ffconf.eyQyRlM4/test.c
x86_64-w64-mingw32-gcc -static-libgcc -static-libstdc++ -I/opt/ffbuild/include -O2 -pipe -D_FORTIFY_SOURCE=2 -fstack-protector-strong -DLIBTWOLAME_STATIC -c -o /tmp/ffconf.eyQyRlM4/test.o /tmp/ffconf.eyQyRlM4/test.c
x86_64-w64-mingw32-gcc -static-libgcc -static-libstdc++ -L/opt/ffbuild/lib -O2 -pipe -fstack-protector-strong -pthread -o /tmp/ffconf.eyQyRlM4/test.exe /tmp/ffconf.eyQyRlM4/test.o -ldl -lgomp
/opt/ct-ng/lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -ldl: No such file or directory
collect2: error: ld returned 1 exit status
C compiler test failed.

--------------------------------------------------------------------------------------------------------------------------------
Does the bug show that there is something wrong with my host machine ? or other reasons?
if you can give the general principle or introducation of comping for window-ffmpeg-builds , very appreciateful.

**Comment by akingbrDu** [comment]
I rename libplacebo, ibjxl, libdrm x11(dir), soxr in scripe.d/, configure passed, then compilation is ok except that it cannot be outputed to artificate-directory at last, error shows:
docker run --rm -i -t -v /root/ffmpeg/winff/FFmpeg-Builds/artifacts:/out -v /root/ffmpeg/winff/FFmpeg-Builds/ffbuild/pkgroot/ffmpeg-6.0-win64-gpl-shared-6.0:/ffmpeg-6.0-win64-gpl-shared-6.0 -w / ghcr.io/btbn/ffmpeg-builds/win64-gpl-shared-6.0:latest zip -9 -r /out/ffmpeg-6.0-win64-gpl-shared-6.0.zip ffmpeg-6.0-win64-gpl-shared-6.0
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "zip": executable file not found in $PATH: unknown.

but I found *.dll and *.lib in ffbuild/prefix which all can run in windows. but I still confused :

./build.sh win64 gpl-shared 6.0

the command seems to do everything in docker, why do I encounter various test errors during the configure process and why "zip" cannot be found in docker?

**Comment by BtbN** [comment]
You must be using some outdated image if zip isn't found in it.
It was added relatively recently.
Make sure to not have any stale images stored locally.

**Comment by akingbrDu** [comment]
how do I decide which docker image to use? it seems to be decided by build.sh automatic？

**Comment by BtbN** [comment]
Delete any ones you have downloaded, so it gets the latest one.
And also make sure you have the latest code itself, otherwise the two might simply be incompatible.

**Comment by akingbrDu** [comment]
from “docker images", I get:
...
ghcr.io/btbn/ffmpeg-builds/win64-gpl-shared-6.0      latest            396e819b4d2a   3 weeks ago     4.39GB
..

what you mean the images has expired？

**Comment by akingbrDu** [comment]
another questions:　when I git clone lastest master version， scripts.d has ”x11“ directory anytime，does it have any effect on compling the window version? thanks

**Comment by BtbN** [comment]
That's 3 weeks old. That's just too old. delete it or pull the latest one manually.

**Comment by akingbrDu** [comment]
thanks for help, Can you help me explain why the configure parameters are still created through the scrips.d directory when compiling through docker, such as the x11 directory, will these not affect the compilation of the window version?

**Comment by BtbN** [comment]
I don't quite understand what you're asking.
You always need the latest version of the build scripts and the image. Or some old ones that match in their age.
If one is outdated, stuff will break.

**Comment by akingbrDu** [comment]
sorry i didn't explain clearly，What I mean is, I think the parameters of ./configure(for ffmpeg) are obtained by build.sh to traverse the files ending in sh in the scripts.d directory。For example: 50-fdk-aac will bring aac configuration for ffmpeg。

When downloading the lastest code from the git warehouse, I see that the x11 directory of script.d has always existed. When compiling the window version, won't these *.sh script in the x11 directory produce parameters that are not suitable for window compilation?

Is there a problem with my understanding? thanks for help

**Comment by BtbN** [comment]
No they won't, unless you modify them to remove the target os check from them.

**Comment by akingbrDu** [comment]
ok, thanks for help, I try again.
