### ISSUE TITLE
50-ffnvcodec.sh uses older ffnvcodec for FFmpeg 6.0

### ISSUE THREAD

**Issue by ericjut1972** [BtbN/FFmpeg-Builds#289]
Shouldn't there be a "$ADDINS_STR == *6.0*" added at line 20 of https://github.com/BtbN/FFmpeg-Builds/blob/master/scripts.d/50-ffnvcodec.sh?

Thanks.

**Comment by BtbN** [comment]
No, why would it?
6.0 supports SDK 12.0 just fine.
