### ISSUE TITLE
What's the difference between ffmpeg gpl version and lgpl version?

### ISSUE THREAD

**Issue by zhuoziqiang** [BtbN/FFmpeg-Builds#29]

**Comment by woshoxxx** [comment]
GPL version has x264 and x265,but LGPL version doesn't

**Comment by BtbN** [comment]
See the ffmpeg configure file for a complete list of which libraries are GPL-only.

But most importantly, the difference is the license. So depending on what you use the binaries for, you can only use the LGPL version.
