### ISSUE TITLE
How to makeimage via SOCK5 proxy

### ISSUE THREAD

**Issue by shaoshilei** [BtbN/FFmpeg-Builds#290]
When I run ./makeimage win32 gpl, I found that docker runs very very very slowly.
Now,I have a SOCK5 proxy. How can I run makeimage by use of SOCK5 proxy?

**Comment by shaoshilei** [comment]
ErrorInfo:
.....................................
 => [stage-0 1/4] FROM docker.io/library/ubuntu:23.04@shaxxxxxx
 => => # error: failed to copy: read tcp 192.168.220.90:40076->104.18.121.25:44
 => => # 3: read: connection reset by peer                                     
 => => # retrying in 1s                                                        
 => => # error: failed to copy: read tcp 192.168.220.90:53722->104.18.125.25:44
 => => # 3: read: connection reset by peer                                     
 => => # retrying in 2s  
......................

**Comment by BtbN** [comment]
I'm not sure if docker supports that.
You will have to consult its documentation or support channels.

**Comment by shaoshilei** [comment]
Thank you.
