### ISSUE TITLE
libfdk-aac missing on Windows

### ISSUE THREAD

**Issue by dtristany** [BtbN/FFmpeg-Builds#291]
I was going to download your release specifically because it's listed as having non-free enabled by https://www.animmouse.com/p/ffmpeg-binaries/ and I saw 50-fdk-aac.sh and 50-vulkan on your scripts, which is the combination I'm after.

However, I can't find any of your windows releases with fdk-aac enabled.

**Comment by BtbN** [comment]
As you said yourself, libfdk makes ffmpeg nofree, so a build of it can't be distributed.
Hence you won't find any for download. You'll need to build one yourself.

**Comment by dtristany** [comment]
If you don't want to distribute it, that's your choice. Others are doing it, I just can't find a release with both vulkan and non-free.

**Comment by BtbN** [comment]
distributing a nonfree binary is actively breaking the GPL, so if you do that, you are risking legal consequences if someone decided to press them against you. And you're also actively insulting the work of the community.
If you need a build with nonfree features, you need to produce it yourself.
So I'm not sure what you're asking here. If you're asking me to break the GPL, the answer is no.
