### ISSUE TITLE
./makeimage.sh win32 gpl failure.

### ISSUE THREAD

**Issue by shaoshilei** [BtbN/FFmpeg-Builds#292]
I run ./makeimage.sh win32 gpl failure. The error information is as follows：

3276.9 [ERROR]    g++: fatal error: Killed signal terminated program cc1plus
3276.9 [ALL  ]    compilation terminated.
3276.9 [ERROR]    make[2]: *** [Makefile:1157: gimple-match.o] Error 1
3276.9 [ERROR]    make[2]: *** Waiting for unfinished jobs....
3293.0 [ALL  ]    rm gcc.pod
3293.0 [ALL  ]    make[2]: Leaving directory '/ct-ng/build/i686-w64-mingw32/build/build-cc-gcc-core/gcc'
3293.0 [ERROR]    make[1]: *** [Makefile:4601: all-gcc] Error 2
3293.0 [ALL  ]    make[1]: Leaving directory '/ct-ng/build/i686-w64-mingw32/build/build-cc-gcc-core'
3293.0 [ERROR]
3293.0 [ERROR]  >>
3293.0 [ERROR]  >>  Build failed in step 'Installing core C gcc compiler'
3293.0 [ERROR]  >>        called in step '(top-level)'
3293.0 [ERROR]  >>
3293.0 [ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@377]
3293.0 [ERROR]  >>        called from: do_gcc_core_backend[scripts/build/cc/gcc.sh@711]
3293.0 [ERROR]  >>        called from: do_cc_core[scripts/build/cc/gcc.sh@212]
3293.0 [ERROR]  >>        called from: main[scripts/crosstool-NG.sh@697]
3293.0 [ERROR]  >>
3293.0 [ERROR]  >>  There is a list of known issues, some with workarounds, in:
3293.1 [ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
3293.1 [ERROR]  >>
3293.1 [ERROR]  >> NOTE: Your configuration includes features marked EXPERIMENTAL.
3293.1 [ERROR]  >> Before submitting a bug report, try to reproduce it without enabling
3293.1 [ERROR]  >> any experimental features. Otherwise, you'll need to debug it
3293.1 [ERROR]  >> and present an explanation why it is a bug in crosstool-NG - or
3293.1 [ERROR]  >> preferably, a fix.
3293.1 [ERROR]  >>
3293.1 [ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
3293.1 [ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
3293.1 [ERROR]  >>
3293.1 [ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
3293.1 [ERROR]  >>  Read the bug reporting guidelines here:
3293.1 [ERROR]  >>      http://crosstool-ng.github.io/support/
3293.1 [ERROR]
3293.1 [ERROR]  (elapsed: 52:21.33)
3293.1 gmake: *** [ct-ng:261: build] Error 2
------
WARNING: local cache import at .cache/ghcr.io/btbn/ffmpeg-builds/base-win32_latest not found due to err: could not read
.cache/ghcr.io/btbn/ffmpeg-builds/base-win32_latest/index.json: open .cache/ghcr.io/btbn/ffmpeg-builds/base-win32_latest
/index.json: no such file or directory
Dockerfile:4
--------------------
   3 |
   4 | >>> RUN --mount=src=ct-ng-config,dst=/.config \
   5 | >>>     git clone --filter=blob:none https://github.com/crosstool-ng/crosstool-ng.git /ct-ng && cd /ct-ng && \
   6 | >>>     ./bootstrap && \
   7 | >>>     ./configure --enable-local && \
   8 | >>>     make -j$(nproc) && \
   9 | >>>     cp /.config .config && \
  10 | >>>     ./ct-ng build && \
  11 | >>>     cd / && \
  12 | >>>     rm -rf ct-ng
  13 |
--------------------
ERROR: failed to solve: process "/bin/sh -c git clone --filter=blob:none https://github.com/crosstool-ng/crosstool-ng.gi
t /ct-ng && cd /ct-ng &&     ./bootstrap &&     ./configure --enable-local &&     make -j$(nproc) &&     cp /.config .co
nfig &&     ./ct-ng build &&     cd / &&     rm -rf ct-ng" did not complete successfully: exit code: 2
+ rm -f /tmp/tmp.39beeEl0pN.toml

What's the matter?

**Comment by BtbN** [comment]
This works perfectly fine for me locally.
For the lack of a proper error, I can only guess that you ran our of RAM, causing that "Killed" message.

**Comment by shaoshilei** [comment]
I ran ./makeimage win32 gpl many times ago, and they ran perfectly without any error information. This  error information occurred one month before. I think, something wrong happened to script files. I will download and run ./makeimgae some days after. Thank you.

**Comment by BtbN** [comment]
I haven't run into any issues during my latest test runs, so I'm gonna assume this was a local issue to your system and close here.
