### ISSUE TITLE
m3u8/hls livestream recording hangs

### ISSUE THREAD

**Issue by h82b8** [BtbN/FFmpeg-Builds#293]
Hey,

when using ffmpeg to record livestreams ffmpeg sometimes just hangs forever not doing anything.

I suspect the server timed out or a short connection issue on the serverside and then ffmpeg just sits there waiting but not receiving anything, despite the stream continuing.

I tried the -timeout, -rw_timeout and the -reconnect options but nothing seems to make ffmpeg end its endless waiting.

Here the problem is described in more details and with a proxy workaround: http://michael-peeters.blogspot.com/2019/03/hanging-m3u8-downloads-in-ffmpeg.html?m=1

Is there anyway to solve this without using a workaround like a proxy?

**Comment by BtbN** [comment]
I can't really do user support here, so the issues here are reserved for issues with the builds themselves, not generic ffmpeg issues/usage.
I'd recommend asking on the ffmpeg-user mailing list, or in #ffmpeg on Libera.Chat.
