### ISSUE TITLE
makeimage.sh error

### ISSUE THREAD

**Issue by nazarux** [BtbN/FFmpeg-Builds#295]
I don’t know why but every time I try to make a build I get this error at the end (Ubuntu 22.04):

```
WARNING: local cache import at .cache/ghcr.io/btbn/ffmpeg-builds/linux64-nonfree-6.0_latest not found due to err: could not read .cache/ghcr.io/btbn/ffmpeg-builds/linux64-nonfree-6.0_latest/index.json: open .cache/ghcr.io/btbn/ffmpeg-builds/linux64-nonfree-6.0_latest/index.json: no such file or directory
+ docker container stop ffbuildreg
ffbuildreg
+ docker buildx rm -f ffbuilder
ffbuilder removed
+ rm -f /tmp/tmp.l1p8sA3jhQ.toml
```

But running makeimage.sh again, it takes the job somewhere and in a few minutes the image is completed sucssefully. Also, would be nice to know how often one should re-build the image again.

**Comment by BtbN** [comment]
That's not an error, the build completed successfully.
