### ISSUE TITLE
Add "--enable-libharfbuzz" to default build to re-enable drawtext

### ISSUE THREAD

**Issue by Black-Platypus** [BtbN/FFmpeg-Builds#297]
`drawtext` is currently not working anymore under the current build args without `libharfbuzz` https://trac.ffmpeg.org/ticket/10570#comment:2

**Comment by JonnyTech** [comment]
I noticed that too today, do you know when was the last working version with `drawtext`?

**Comment by BtbN** [comment]
The library should probably be autodetected by FFmpeg, it's not nonfree or anything.

**Comment by JonnyTech** [comment]
Confirmed - build `N-112119-gda1d56776c` works as expected. Thanks for the quick fix.

**Comment by BtbN** [comment]
I see no reason why that would be the case.
6.0 configure does not even know about libharfbuzz: https://git.videolan.org/?p=ffmpeg.git;a=blob;f=configure;hb=refs/heads/release/6.0
6.0 should still work fine without it being explicitly enabled. In fact, trying to enable it would break the build.

**Comment by BtbN** [comment]
```
$ ./ffmpeg-n6.0-latest-win64-gpl-6.0/bin/ffmpeg.exe -filters |& grep drawtext
 T.C drawtext          V->V       Draw text on top of video frames using libfreetype library.
$ ./ffmpeg-n5.1-latest-win64-gpl-5.1/bin/ffmpeg.exe -filters |& grep drawtext
 T.C drawtext          V->V       Draw text on top of video frames using libfreetype library.
$ ./ffmpeg-master-latest-win64-gpl/bin/ffmpeg.exe -filters |& grep drawtext
 T.C drawtext          V->V       Draw text on top of video frames using libfreetype library.
```

All versions got the drawtext filter enabled just fine. It was only an issue for a few days with the master builds, cause of the new libharfbuzz dependency. Nothing changed on all release branches. None of that got backported there.
So your issue must be something else.
You will need to be more specific than "does not work".

**Comment by sebmasterid** [comment]
With 5.1.1 :
/var/www/ktt # ffmpeg
ffmpeg version 5.1.1-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2022 the FFmpeg developers
ffmpeg -i /var/www/ktt/var/upload/sharedMovie/192_movie.mp4 -filter_complex "[0]scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2
:(oh-ih)/2[b];[b]drawtext=fontfile=/var/www/ktt/web/fonts:text= : timecode='00\:00\:00\:00': r='30': x=10: y=10: fontcolor=white: fontsize=50: box=1: boxcolor=0x00000000@1
" -f mp4 -vcodec libx264 -b:v 3M -preset medium /var/www/ktt/var/upload/sharedMovie/192ffmpeg -i /var/www/ktt/var/upload/sharedMovie/192_movie.mp4 -filter_complex "[0]scal
e=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2[b];[b]drawtext=fontfile=/var/www/ktt/web/fonts:text= : timecode='00\:00\:00\:00': r='30'
: x=10: y=10: fontcolor=white: fontsize=50: box=1: boxcolor=0x00000000@1" -f mp4 -vcodec libx264 -b:v 3M -preset medium /var/www/ktt/var/upload/sharedMovie/192_movie_1.mp4
It runs flawless

Same with version 6 (wget https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz)
/var/www/ktt # ffmpeg
ffmpeg version N-67181-g984d0b6e6f-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
/var/www/ktt # ffmpeg -i /var/www/ktt/var/upload/sharedMovie/192_movie.mp4 -filter_complex "[0]scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2
:(oh-ih)/2[b];[b]drawtext=fontfile=/var/www/ktt/web/fonts:text= : timecode='00\:00\:00\:00': r='30': x=10: y=10: fontcolor=white: fontsize=50: box=1: boxcolor=0x00000000@1
" -f mp4 -vcodec libx264 -b:v 3M -preset medium /var/www/ktt/var/upload/sharedMovie/192ffmpeg -i /var/www/ktt/var/upload/sharedMovie/192_movie.mp4 -filter_complex "[0]scal
e=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2[b];[b]drawtext=fontfile=/var/www/ktt/web/fonts:text= : timecode='00\:00\:00\:00': r='30'
: x=10: y=10: fontcolor=white: fontsize=50: box=1: boxcolor=0x00000000@1" -f mp4 -vcodec libx264 -b:v 3M -preset medium /var/www/ktt/var/upload/sharedMovie/192_movie_1.mp4
 -hide_banner
[AVFilterGraph @ 0x6832b80] No such filter: 'drawtext'
Failed to set value '[0]scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2[b];[b]drawtext=fontfile=/var/www/ktt/web/fonts:text= : timecode='00\:00\:00\:00': r='30': x=10: y=10: fontcolor=white: fontsize=50: box=1: boxcolor=0x00000000@1' for option 'filter_complex': Filter not found
Error parsing global options: Filter not found

**Comment by BtbN** [comment]
Both of those builds are not from here.

**Comment by sebmasterid** [comment]
Sorry. :-(
I will try your build.
Many thanks for all your help.
