### ISSUE TITLE
Invalid dll name

### ISSUE THREAD

**Issue by senyai** [BtbN/FFmpeg-Builds#30]
Downlaoded ffmpeg-n4.3.1-26-gca55240b8c-win64-lgpl-shared-4.3.zip. Linked executable. It required avcodec-57.dll, zip contains avcodec-58.dll. Only me?

**Comment by senyai** [comment]
I'm sure the issue is on my side. Closing.

**Comment by BtbN** [comment]
-57 is an old version of ffmpeg, Probably 4.1 or something like that.
