### ISSUE TITLE
Fraunhofer VVC

### ISSUE THREAD

**Issue by mrtajniak** [BtbN/FFmpeg-Builds#302]
How can I add VVC enc and dec to FFmpeg Build?
![image](https://github.com/BtbN/FFmpeg-Builds/assets/33846499/7bcc530f-5308-401c-bb5a-8d05ab66cb26)

I need VVC

**Comment by BtbN** [comment]
FFmpeg does not support either of that yet. So you can't(unless you write the code yourself).
There's some preliminary patches on the ML, so it will happen eventually.

**Comment by mrtajniak** [comment]
Are you sure? Because I have ffmpeg build that only supports VVC
![image](https://github.com/BtbN/FFmpeg-Builds/assets/33846499/ed2ccc1b-41ae-40b3-adb0-08f300f7c8b2)

**Comment by mrtajniak** [comment]
So how can I do it

**Comment by mrtajniak** [comment]
Can I add a couple of flags to this tool? maybe I can easily compile it from source using the same method that is used by this tool

**Comment by BtbN** [comment]
Find the correct patches on ffmpeg-devel, apply them to your fork of ffmpeg, and build that fork manually.
I don't carry patches external to ffmpeg itself here, only what's in the main repo.
If you want to use this set of scripts, you'd have to also write a build script for the two fraunhofer libraries first, since that does not exist at all so far.

**Comment by mrtajniak** [comment]
I thought that if this tool has no nfree codecs I will also get VVC

**Comment by BtbN** [comment]
It will, once it's merged into FFmpeg.
As of right now, FFmpeg has not merged a single h266 de/encoder.

**Comment by mrtajniak** [comment]
Ok so I am not getting VVC, I will try to fix [MABS](https://github.com/m-ab-s/media-autobuild_suite)

**Comment by classicdoomenjoyer** [comment]
> It will, once it's merged into FFmpeg. As of right now, FFmpeg has not merged a single h266 de/encoder.

So, sir, when wil FFMPEG officially start supporting vvenc encoder ?

I would like FFMPEG to support the encoder as soon as possible coz, VVC the future of 4K and 8K Video Encoding!

**Comment by BtbN** [comment]
Whenever it's ready. This repo is not the place for requests about it.

**Comment by classicdoomenjoyer** [comment]
> Whenever it's ready. This repo is not the place for requests about it.

Okay sir.
