### ISSUE TITLE
failed with error: Server does not allow request for unadvertised object

### ISSUE THREAD

**Issue by huangjinshe** [BtbN/FFmpeg-Builds#309]
```
 => [layer-10-mingw 1/1] RUN --mount=src=scripts.d/10-mingw.sh,dst=/stage.sh run_stage /stage.sh                                    336.0s
 => => # + echo 'Retry 5...'                                                                                                              
 => => # + [[ 5 -lt 10 ]]                                                                                                                 
 => => # + timeout 420 git -C mingw fetch --depth=1 origin 9df2e604ddf16765410724716a8d1887ffc61fa9                                       
 => => # error: Server does not allow request for unadvertised object 9df2e604ddf16765410724716a8d1887ffc61fa9                            
 => => # ++ shuf -i 5-90 -n 1                                                                                                             
 => => # + sleep 44                                                      
```
and
```
69.8 + echo 'Max retry count exceeded.'
569.8 + exit 1
569.8 Retry 10...
569.8 Max retry count exceeded.

```
By the way: The Ubuntu download process such a disaster, can't download once, need to download all again and again from start.

I'm using [FFmpeg-Builds-Win32](https://github.com/sudo-nautilus/FFmpeg-Builds-Win32) branch.

**Comment by BtbN** [comment]
I don't quite understand what you mean with "can't download at once", docker caches intermediate layers just fine for me.
I also can't reproduce that error. The hash given there is not the one in the script either, probably because you're using a fork, and not this repo.

Please contact the maintainer of that fork for issues with it, or reproduce it with an unmodified version and re-open.

**Comment by huangjinshe** [comment]
Ok, thanks.

**Comment by pzhlkj6612** [comment]
Hello @huangjinshe .

> ... I'm using [FFmpeg-Builds-Win32](https://github.com/sudo-nautilus/FFmpeg-Builds-Win32) branch.

As **BtbN** said, that's a fork, not a branch of this repository.

Maybe you would like to know:

> # About forks
> 
> A fork is a new repository that shares code and visibility settings with the original “upstream” repository.
> 
> _[About forks - GitHub Docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/about-forks)_

**Comment by huangjinshe** [comment]
@pzhlkj6612 Yes I know, sorry for my mistake for confusing you.
