### ISSUE TITLE
make win32 gpl-shared failure

### ISSUE THREAD

**Issue by shaoshilei** [BtbN/FFmpeg-Builds#311]
I run ./makeimage.sh win32 gpl-shared failed. The error message is as follows:
....
=> ERROR [layer-50-vulkan 2/5] RUN --mount=src=scripts.d/50-vulkan/50-sh  6.9s
.....
2.626 -- Performing Test COMPILER_SUPPORTS_PIC
2.910 -- Performing Test COMPILER_SUPPORTS_PIC - Success
6.466 -- Found Python3: /usr/bin/python3 (found version "3.11.4") found components: Interpreter 
6.466 -- Configuring incomplete, errors occurred!
6.466 See also "/opt/ffdl/scripts.d/50-vulkan/50-shaderc.sh/build/CMakeFiles/CMakeOutput.log".
6.467 CMake Error at third_party/spirv-tools/external/CMakeLists.txt:47 (message):
6.467   SPIRV-Headers was not found - please checkout a copy under external/.
6.467 
6.467 
......

What's the matter?

**Comment by BtbN** [comment]
I can't reproduce this. `./makeimage.sh win32 gpl-shared` complete without issues for me.
Did you do anything special/unusual that might cause that?

**Comment by shaoshilei** [comment]
After I run ./makeimage.sh win64 gpl successfully, I run ./makeimage.sh win32 gpl-shared successfully.

**Comment by BtbN** [comment]
My guess would be that you had old docker images flying around, which then interfered with the latest build scripts.
