### ISSUE TITLE
Memory leak with hardware accelerated filter_complex

### ISSUE THREAD

**Issue by sharinganthief** [BtbN/FFmpeg-Builds#314]
ran into an issue where all my memory was getting consumed with a "simple" trim/concat operation such as I do frequently.

was on latest Gyan build, found this reddit post - https://www.reddit.com/r/ffmpeg/comments/16c57p1/memory_leak_when_using_hardware_acceleration/
- check for latest build here, same issue, jumped back a few months at a time until I got to the last build of 2022 i think.

rolled back to - https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2022-12-31-12-36/ffmpeg-n5.1.2-9-g807afa59cc-win64-gpl-5.1.zip - and im not seeing the memory leak anymore with the same command

**Comment by BtbN** [comment]
Please report issues with ffmpeg itself to ffmpeg. I can't do anything about that here.
