### ISSUE TITLE
May I ask if I am using QSV decoding and CPU decoding for playback? I found that the QSV image is delayed by a few frames compared to the CPU. Are there any parameters that can be set? My version is ffmpeg4.3

### ISSUE THREAD

**Issue by zhuya1996** [BtbN/FFmpeg-Builds#315]
May I ask if I am using QSV decoding and CPU decoding for playback? I found that the QSV image is delayed by a few frames compared to the CPU. Are there any parameters that can be set? My version is ffmpeg4.3

**Comment by BtbN** [comment]
Please ask user question on ffmpeg irc or the ffmpeg-user mailing list.
