### ISSUE TITLE
Unauthorized image pull from ghcr repo?

### ISSUE THREAD

**Issue by dp289m** [BtbN/FFmpeg-Builds#316]
+ docker run --rm -v /home/azureuser/FFmpeg-Builds-master:/uidtestdir ghcr.io/btbn/ffmpeg-builds/linux64-nonfree-6.0:latest touch /uidtestdir/uidtestfile
Unable to find image 'ghcr.io/btbn/ffmpeg-builds/linux64-nonfree-6.0:latest' locally
docker: Error response from daemon: Head "https://ghcr.io/v2/btbn/ffmpeg-builds/linux64-nonfree-6.0/manifests/latest": denied.
See 'docker run --help'

**Comment by dp289m** [comment]
reolved with a token.

**Comment by BtbN** [comment]
There are no nonfree-images for download, since they would be nonfree.
So token or not, it will fail.

**Comment by MrShoenel** [comment]
@BtbN So how can the nonfree version then be built locally?

**Comment by BtbN** [comment]
Run makeimage first instead of just build.
