### ISSUE TITLE
Attempt building 6.0. Error: "docker: Error response from daemon: manifest unknown"

### ISSUE THREAD

**Issue by dp289m** [BtbN/FFmpeg-Builds#317]
+ docker run --rm -v /home/azureuser/FFmpeg-Builds-master:/uidtestdir ghcr.io/btbn/ffmpeg-builds/linux64-nonfree-6.0:latest touch /uidtestdir/uidtestfile
Unable to find image 'ghcr.io/btbn/ffmpeg-builds/linux64-nonfree-6.0:latest' locally
docker: Error response from daemon: manifest unknown.
See 'docker run --help'.

**Comment by BtbN** [comment]
Again, there are no nonfree images for download, since they are nonfree.
You need to build them yourself, or stick to gpl/lgpl.
