### ISSUE TITLE
Question about Game Music Emu support

### ISSUE THREAD

**Issue by vico93** [BtbN/FFmpeg-Builds#32]
Does your builds have support for [Game Music Emu (libgme)](http://underpop.online.fr/f/ffmpeg/help/libgme.htm.gz)?

Downloaded 4.3.1 GPL and seems like this library wasn't enabled.

**Comment by BtbN** [comment]
It does not, and I have never heard of that library. If it's not extremely large or has huge dependencies(and plays nice with static linking), there's no reason not to add it though.

**Comment by vico93** [comment]
> It does not, and I have never heard of that library. If it's not extremely large or has huge dependencies(and plays nice with static linking), there's no reason not to add it though.

Thanks for the info btw, i searched more and realized the builds available [on this site](https://www.gyan.dev/ffmpeg/builds/) have that library enabled.
