### ISSUE TITLE
Release asset filename has been changed

### ISSUE THREAD

**Issue by pzhlkj6612** [BtbN/FFmpeg-Builds#323]
Hi! First of all, thanks for your work for this repository.

Today I've found that the filename formats of FFmpeg 5 and 6 are not the same as old ones:

> ## [Auto-Build 2023-11-12 12:58](https://github.com/BtbN/FFmpeg-Builds/releases/tag/autobuild-2023-11-12-12-58)
> 
> - [ffmpeg-n4.4.4-6-gd5fa6e3a91-linux64-gpl-shared-4.4.tar.xz](https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2023-11-12-12-58/ffmpeg-n4.4.4-6-gd5fa6e3a91-linux64-gpl-shared-4.4.tar.xz)
> - [ffmpeg-n5.1.4-linux64-gpl-shared-5.1.tar.xz](https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2023-11-12-12-58/ffmpeg-n5.1.4-linux64-gpl-shared-5.1.tar.xz)
> - [ffmpeg-n6.0.1-linux64-gpl-shared-6.0.tar.xz](https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2023-11-12-12-58/ffmpeg-n6.0.1-linux64-gpl-shared-6.0.tar.xz)

> ## [Auto-Build 2023-10-31 13:06](https://github.com/BtbN/FFmpeg-Builds/releases/tag/autobuild-2023-10-31-13-06)
> 
> - [ffmpeg-n4.4.4-6-gd5fa6e3a91-linux64-gpl-shared-4.4.tar.xz](https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2023-10-31-13-06/ffmpeg-n4.4.4-6-gd5fa6e3a91-linux64-gpl-shared-4.4.tar.xz)
> - [ffmpeg-n5.1.3-105-g7739dabb89-linux64-gpl-shared-5.1.tar.xz](https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2023-10-31-13-06/ffmpeg-n5.1.3-105-g7739dabb89-linux64-gpl-shared-5.1.tar.xz)
> - [ffmpeg-n6.0-162-g07e3223dd0-linux64-gpl-shared-6.0.tar.xz](https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2023-10-31-13-06/ffmpeg-n6.0-162-g07e3223dd0-linux64-gpl-shared-6.0.tar.xz)

Is this change intentional? Thanks.

**Comment by BtbN** [comment]
That's just what git describe does when a commit hits an exact tag.

**Comment by pzhlkj6612** [comment]
I got it, thank you!
