### ISSUE TITLE
ffmpeg mediacodecdec tunneled playback feature support

### ISSUE THREAD

**Issue by lcksk** [BtbN/FFmpeg-Builds#324]
The mediacodec decoder in ffmpeg also seems to lack tunneled playback support. Would you be interested in improving it as well? This could benefit many people who use ffply to play on the android side.

**Comment by BtbN** [comment]
This repository is for issues with the builds only. I cannot take care of ffmpeg issues or feature requests.
Please open such issues upstream on FFmpeg trac, or ask on the ffmpeg-user ML for support.
