### ISSUE TITLE
Record remote desktop

### ISSUE THREAD

**Issue by WorldWarriorIII** [BtbN/FFmpeg-Builds#325]
Hi,

I would like to run FFmpge to record remote machine, but I don't want to install FFmpge in the remote machine. I  already installed FFmpge in my localhost. Can I use SSH to run FFmpge to record remote machine? Thanks.

**Comment by BtbN** [comment]
Please ask usage questions on the ffmpeg-user mailing list.
Issues here are only regarding the builds themselves.
