### ISSUE TITLE
`7ed76a8` commit seems to cause compilation to fail

### ISSUE THREAD

**Issue by gz83** [BtbN/FFmpeg-Builds#327]
I tried to compile ffmpeg using the script you provided on kubuntu 24.04. I found that it seemed that the cache related to `openmpt` could not be uploaded normally during the execution of the `makeimage.sh` script, and an error message exceeding the maximum number of retries appeared. After reverting `7ed76a8`, the `makeimage.sh` script and subsequent `build.sh` script can be executed and compiled normally.

Here are the commands I used when compiling:
`./makeimage.sh linux64 nonfree lto`
`./build.sh linux64 nonfree lto`

This is the first time I'm trying to compile on my computer.

https://github.com/BtbN/FFmpeg-Builds/commit/7ed76a8724e0178f16729384bf607e9b34ec1e9c

@BtbN

**Comment by BtbN** [comment]
Please provide additional information.
So far, best I can tell you that maybe a broken download got cached. Try deleting the affected archive, so it'll re-download it.
Might also just be an intermittent issue on some external server, that's the only thing that has retries.

**Comment by gz83** [comment]
> Please provide additional information. So far, best I can tell you that maybe a broken download got cached. Try deleting the affected archive, so it'll re-download it. Might also just be an intermittent issue on some external server, that's the only thing that has retries.

Thanks for your reply, this problem seems to be related to network issues, now I can compile ffmpeg normally using the script you provided.

@BtbN
