### ISSUE TITLE
Request to add libvmaf_cuda to latest builds

### ISSUE THREAD

**Issue by alexdns1** [BtbN/FFmpeg-Builds#328]
Can you please add support for libvmaf_cuda in the builds ?

https://github.com/FFmpeg/FFmpeg/commit/7f685d0f493bbfa44cf1b3b65f9347291e23872b
https://github.com/search?q=repo%3AFFmpeg%2FFFmpeg+libvmaf_cuda&type=code

 ffmpeg -filters|grep vmaf
ffmpeg version N-113111-g4fee63b241-20231226 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13.2.0 (crosstool-NG 1.25.0.232_c175b21)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-openssl --enable-lzma --enable-fontconfig --enable-libharfbuzz --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-chromaprint --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libaribcaption --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20231226
  libavutil      58. 36.100 / 58. 36.100
  libavcodec     60. 36.100 / 60. 36.100
  libavformat    60. 20.100 / 60. 20.100
  libavdevice    60.  4.100 / 60.  4.100
  libavfilter     9. 14.101 /  9. 14.101
  libswscale      7.  6.100 /  7.  6.100
  libswresample   4. 13.100 /  4. 13.100
  libpostproc    57.  4.100 / 57.  4.100
 ... libvmaf           VV->V      Calculate the VMAF between two video streams.
 ... vmafmotion        V->V       Calculate the VMAF Motion score.

**Comment by BtbN** [comment]
As far as I understand how libvmaf handles CUDA, that's impossible.
It links directly against CUDA, making an installed Nvidia-Driver a requirement to run the binaries.
This is unacceptable for hopefully obvious reasons.

Plus, it needs the CUDA SDK to build, which would just like that more than triple the size of every single build image.

Please correct me if I'm wrong and there is some way to make it dynamically load the library and build without the full SDK.

**Comment by alexdns1** [comment]
You are 100% right thank you

**Comment by gedoensmax** [comment]
@BtbN since I changed the VMAF lib to dynamically load the CUDA driver libs it would be possible to link the lib now and execute without a CUDA driver. That being said it still requires the CUDA toolkit for compilation. 
Is this a hard blocker ? I tried to compile without CUDA headers, but it turned out to be a nightmare.

**Comment by BtbN** [comment]
The CUDA SDK is a hard blocker, yeah.
Since I build docker-images of the build env and publish them here, I'm inevitably redistributing it.
And the license of the CUDA SDK forbids redistributing it.
Plus, the CUDA SDK alone would more than double the size of those images, so I'm not too keen on adding it in general.

**Comment by gedoensmax** [comment]
Yes makes sense. How about picking up a built binary from the VMAF repo instead of building it here ? Are you open to that ? Since none of CUDA Toolkit libs are required - just the headers.

**Comment by BtbN** [comment]
That kinda feels dishonest to the point of this whole repo.
Do the headers have a more liberal license? The whole nv-codec-headers exist to solve that entire problem.

**Comment by gedoensmax** [comment]
I would have to read up on the headers. I was trying to get around having a cuda_runtime.h combat header like ffmpeg has. But maybe I'll have to introduce that. 
Another point is that I was seeing slower kernels when compiling with clang.

**Comment by gedoensmax** [comment]
@BtbN I create a branch: https://github.com/gedoensmax/vmaf/tree/clang_cuda_compat
I am stuck at enabling a shuffle down intrinsic that is only defined for a CUDA arch >= sm60. I am setting the compilation to do sm_75 but for some reason clang complains inside the container. 
```
5.381 /usr/bin/clang --cuda-gpu-arch=sm_75 --cuda-device-only -m64 -O2 -S -nocudainc -nocudalib -Wno-c++11-narrowing -I ../src/compat/cuda ../src/./feature/cuda/integer_adm/adm_csf_den.cu -o src/adm_csf_den.fatbin -I ./src -I ../src -I ../include -I ../src/feature -I ../src/./cuda/ -DDEVICE_CODE
5.381 In file included from ../src/./feature/cuda/integer_adm/adm_csf_den.cu:21:
5.381 In file included from ../src/feature/cuda/integer_adm_cuda.h:25:
5.381 In file included from ../src/./cuda/common.h:31:
5.381 In file included from ../src/./cuda/cuda_helper.cuh:25:
5.381 ../src/compat/cuda/cuda_runtime.h:202:114: error: '__nvvm_shfl_sync_down_i32' needs target feature ptx60|ptx61|ptx63|ptx64|ptx65|ptx70|ptx71|ptx72|ptx73|ptx74|ptx75|ptx76|ptx77|ptx78|ptx80|ptx81|ptx82|ptx83
5.381   202 | static inline __device__ unsigned __shfl_down_sync(unsigned mask, unsigned int var, unsigned int delta) { return __nvvm_shfl_sync_down_i32(mask, var, delta, 32); }
5.381       |                                                                                                                  ^
5.381 1 error generated when compiling for sm_75.
```

**Comment by BtbN** [comment]
I have never seen such an error before.
I'd assume you need to pass some additional feature flags akin to -mavx to clang, like with intrinsics on normal CPU code.

**Comment by gedoensmax** [comment]
@BtbN Thanks this feature flag thought helped me figure it out. I never really worked with clang before. Could you give my branch a review ? I can open a VMAF PR if this has everything you would need.

**Comment by BtbN** [comment]
Not entirely sure what to look at.
Do the patches in https://github.com/gedoensmax/vmaf/tree/clang_cuda_compat enable using it without any need for the CUDA SDK?

**Comment by gedoensmax** [comment]
Yes they do. It is a compromise on speed though ...
It would help me knowing that your setup in this repo would work with this branch. Then i can see if i can fix performance on clang.

**Comment by BtbN** [comment]
There's pretty much only a few conditions for that.
It shouldn't pull in gigabytes of stuff in dependencies, the stuff it pulls in should be under a compatible license I can redistribute and build, and the resulting binaries should have no hard dependency on Nvidia things that'd make the binaries unusable on systems without the Nvidia/CUDA-SDK driver installed.

**Comment by weneedred1-stack** [comment]
@gedoensmax did you have any progress on this? Or did you manage to make something even if it breaks the license? So people can manually rebuild it.

**Comment by gedoensmax** [comment]
@weneedred1-stack Yeah so i have this branch linked above, it is able to compile with clang but is not correct and non performant last time i checked. So i sticked to using nvcc and did not find the time to return to this branch....
https://github.com/gedoensmax/vmaf/tree/clang_cuda_compat
