### ISSUE TITLE
What dependencies uses the Media Foundation Platform?

### ISSUE THREAD

**Issue by AnimMouse** [BtbN/FFmpeg-Builds#33]
Running your GPL & LGPL builds in Windows 10 LTSC N, I got the following error:\
The code execution cannot proceed because MFPlat.DLL was not found.

**Comment by BtbN** [comment]
That's probably ffmpeg itself, since it supports dxva/d3d11va.
Just add the Media Feature Pack via Optional Windows Features and it should work.

**Comment by AnimMouse** [comment]
Ahh, ok, I just wondering why [gyan.dev](https://www.gyan.dev/ffmpeg/builds/) builds are working, and I noticed that their builds are having `--enable-dxva2` & `--enable-d3d11va`. So it seems like adding those dependencies, instead of relying on FFmpeg's native dxva/d3d11va, allows it to be run without MFPlat.DLL. Thanks!

**Comment by BtbN** [comment]
Not sure what you mean by that. You cannot statically link parts of the OS.

**Comment by AnimMouse** [comment]
Then how gyan.dev builds built their binaries with `--enable-dxva2` & `--enable-d3d11va`, which is part of the OS you said? Or there are some dependencies that use MFPlat.DLL other than the dxva/d3d11va that is in your builds?

**Comment by BtbN** [comment]
Could just be a different or older Windows SDK being used, that does not properly support mediafoundation.
It's a separate configure option, which autodetects if the necessary libraries are present.

**Comment by AnimMouse** [comment]
Well, gyan.dev builds has `--disable-autodetect` option. I think that is the reason why it did not autodetect those dependencies.

**Comment by TimoRoth** [comment]
I'm also manually configuring MinGW to target Windows 7+, while by default it's Windows XP+, and Media Foundation does not exist on WinXP.
Will be any combination of those.
But I don't really see any reason to disable the mediafoundation features. Some people might find them useful.
