### ISSUE TITLE
Error and abort while running build.sh

### ISSUE THREAD

**Issue by carsten-s** [BtbN/FFmpeg-Builds#330]
Hello Together,

when i´m running the "build.sh" with the parameters "win64" and "nonfree" i receive multiple errors which are ending up in aborting of the script.
To rule out possible human errors, i deleted the whole docker container and his stuff, pulled the current git-repo content and start from the scratch. 

First "./makeimage.sh win64 nonfree" and then "./build.sh win64 nonfree" as described in the readme.md

The Scripts stats with the feedback of the parameters etc. an the the erros came up:

libavdevice/dshow.c: In function 'dshow_cycle_formats':
libavdevice/dshow.c:987:39: warning: unused variable 'acaps' [-Wunused-variable]
  987 |             AUDIO_STREAM_CONFIG_CAPS *acaps = caps;
      |                                       ^~~~~
In file included from ./libavutil/common.h:40,
                 from ./libavutil/avutil.h:301,
                 from ./libavfilter/avfilter.h:41,
                 from ./libavfilter/internal.h:28,
                 from libavfilter/af_afftfilt.c:22:
In function 'memmove',
    inlined from 'filter_channel' at libavfilter/af_afftfilt.c:297:9:
/opt/ct-ng/x86_64-w64-mingw32/sysroot/mingw/include/string.h:218:10: warning: '__builtin_memmove' specified bound between 18446744065119617024 and 18446744073709551608 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
  218 |   return __builtin___memmove_chk(__dst, __src, __n, __mingw_bos(__dst, 0));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ./libavutil/common.h:40,
                 from ./libavutil/avutil.h:301,
                 from ./libavutil/opt.h:31,
                 from libavfilter/af_firequalizer.c:23:
In function 'memset',
    inlined from 'generate_min_phase_kernel' at libavfilter/af_firequalizer.c:558:5,
    inlined from 'generate_kernel' at libavfilter/af_firequalizer.c:690:13:
/opt/ct-ng/x86_64-w64-mingw32/sysroot/mingw/include/string.h:212:10: warning: '__builtin_memset' specified bound between 18446744069414584316 and 18446744073709551608 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
  212 |   return __builtin___memset_chk(__dst, __val, __n, __mingw_bos(__dst, 0));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libavfilter/f_graphmonitor.c: In function 'draw_items':
libavfilter/f_graphmonitor.c:308:50: warning: unknown conversion type character 'z' in format [-Wformat=]
  308 |         len = snprintf(buffer, sizeof(buffer)-1, "%"SIZE_SPECIFIER, frames);
      |                                                  ^~~
In file included from ./libavutil/common.h:576,
                 from ./libavutil/avutil.h:301,
                 from ./libavutil/opt.h:31,
                 from libavfilter/f_graphmonitor.c:28:
./libavutil/internal.h:141:25: note: format string is defined here
  141 | #define SIZE_SPECIFIER "zu"
      |                         ^
libavfilter/f_graphmonitor.c:308:50: warning: too many arguments for format [-Wformat-extra-args]
  308 |         len = snprintf(buffer, sizeof(buffer)-1, "%"SIZE_SPECIFIER, frames);
      |                                                  ^~~
libavfilter/graphparser.c: In function 'avfilter_graph_segment_create_filters':
libavfilter/graphparser.c:548:58: warning: unknown conversion type character 'z' in format [-Wformat=]
  548 |                 snprintf(name, sizeof(name), "Parsed_%s_%zu", f->name, idx);
      |                                                          ^
libavfilter/graphparser.c:548:46: warning: too many arguments for format [-Wformat-extra-args]
  548 |                 snprintf(name, sizeof(name), "Parsed_%s_%zu", f->name, idx);
      |                                              ^~~~~~~~~~~~~~~
In file included from /opt/ffbuild/include/CL/cl.h:20,
                 from ./libavutil/hwcontext_opencl.h:25,
                 from libavfilter/opencl.h:31,
                 from libavfilter/opencl.c:26:
/opt/ffbuild/include/CL/cl_version.h:22:9: note: '#pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)'
   22 | #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)")
      |         ^~~~~~~
In file included from /opt/ffbuild/include/CL/cl.h:20,
                 from ./libavutil/hwcontext_opencl.h:25,
                 from libavfilter/opencl.h:31,
                 from libavfilter/vf_avgblur_opencl.c:30:
/opt/ffbuild/include/CL/cl_version.h:22:9: note: '#pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)'
   22 | #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)")
      |         ^~~~~~~
In file included from /opt/ffbuild/include/CL/cl.h:20,
                 from ./libavutil/hwcontext_opencl.h:25,
                 from libavfilter/opencl.h:31,
                 from libavfilter/vf_colorkey_opencl.c:22:
/opt/ffbuild/include/CL/cl_version.h:22:9: note: '#pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)'
   22 | #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)")
      |         ^~~~~~~
In file included from /opt/ffbuild/include/CL/cl.h:20,
                 from ./libavutil/hwcontext_opencl.h:25,
                 from libavfilter/opencl.h:31,
                 from libavfilter/vf_convolution_opencl.c:33:
/opt/ffbuild/include/CL/cl_version.h:22:9: note: '#pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)'
   22 | #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)")
      |         ^~~~~~~

In file included from /opt/ffbuild/include/CL/cl.h:20,
                 from ./libavutil/hwcontext_opencl.h:25,
                 from libavfilter/opencl.h:31,
                 from libavfilter/vf_deshake_opencl.c:62:
/opt/ffbuild/include/CL/cl_version.h:22:9: note: '#pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)'
   22 | #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)")
      |         ^~~~~~~
libavfilter/vf_drawtext.c: In function 'shape_text':
libavfilter/vf_drawtext.c:687:13: error: implicit declaration of function 'is_newline'; did you mean 'ff_is_newline'? [-Werror=implicit-function-declaration]
  687 |         if (is_newline(unicodestr[line_end]) || line_end == len - 1) {
      |             ^~~~~~~~~~
      |             ff_is_newline
	  
cc1: some warnings being treated as errors
make: *** [ffbuild/common.mak:81: libavfilter/vf_drawtext.o] Error 1

###################################################################################################
System-Infos:

Debian 12 bookworm
6.1.0-17-amd64 SMP PREEMPT_DYNAMIC Debian 6.1.69-1 (2023-12-30) x86_64 GNU/Linux

GNU bash, Version 5.2.15(1)-release-(x86_64-pc-linux-gnu)

docker version
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:08:02 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:08:02 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.26
  GitCommit:        3dd1e886e55dd695541fdcd67420c2888645a495
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by BtbN** [comment]
That is an actual error in the code of ffmpeg itself, it affects all builds.
This needs to be fixed upstream.

**Comment by carsten-s** [comment]
Thanks :-)
