### ISSUE TITLE
About x264: why use a github mirror repo instead of a videolan repo?

### ISSUE THREAD

**Issue by Aniark** [BtbN/FFmpeg-Builds#332]
I've noticed that the build script used to use the videolan repo 
https://github.com/BtbN/FFmpeg-Builds/blob/b4bbce3020bbb1de61a7cc1361a8cd57ad417d91/scripts.d/50-x264.sh#L3-L4

then switched to the github mirror repo
https://github.com/BtbN/FFmpeg-Builds/blob/3119034c9234be55afaccecfe3a457bb4e0eb402/scripts.d/50-x264.sh#L3-L4

but the videolan repo seems to be more actively maintained, so I'd like to know why

**Comment by BtbN** [comment]
Cause videolan infrastructure is too unreliable, specially in regards to their peering with github.
Also, the army of builds this repo and its forks produce is quite a substantial server and bandwidth load, so whenever a project has a Github mirror, I will prefer it.

**Comment by Aniark** [comment]
On github, [Anton Mitrofanov](https://github.com/MasterNobody)
, one of the primarily developer of x264, has a [x264](https://github.com/MasterNobody/x264) repo that maintains a more active than the [mirror/x264](https://github.com/mirror/x264 ) repo, could this be a better alternative?

**Comment by BtbN** [comment]
Supposedly videolan fixed their peering issues with Github, so I'll give it a try again.
Cachine has improved a lot since then as well.
