### ISSUE TITLE
Off Topic, but related...

### ISSUE THREAD

**Issue by newcapricasean** [BtbN/FFmpeg-Builds#337]
Is there a way to take this fdk-aac code here...
https://github.com/mstorsjo/fdk-aac
Or the FDK-AAC code your build uses...
To make an executable only for audio decoding and encoding?

I can make either a .dll or .exe, with that script there, but they only accept .dll input. I want it to be capable of inputting almost any format, but especially, avisynth served audio stream...

**Comment by abrar71** [comment]
So Do you basically want a very small build of FFmpeg with only `fdk_aac` decoding/encoding support?

**Comment by newcapricasean** [comment]
In a manner of speaking... One that I can compile, with a script, that will get the most recent version of the FDK-AAC decode/encode library, but also have the ability of FFMPEG to import the audio from nearly any source, including avisynth & vapoursynth scripts...

However, that's not necessarily mandatory. I can just build FFMPEG, and use that. I just don't need everything inside FFMPEG. For video encoding, I use my own compiled x265 command line encoder in 8, 10, & 12 bit variants...

**Comment by sergeevabc** [comment]
Is there a Windows build here that is compiled with `-c:a aac_at` support?

**Comment by BtbN** [comment]
Given that at here stands for audiotoolbox, which is an Apple/OSX API, that seems highly unlikely.

**Comment by Aniark** [comment]
> Given that at here stands for audiotoolbox, which is an Apple/OSX API, that seems highly unlikely.

On Windows, ffmpeg's build process can be tricked into linking to an CoreAudioToolbox.dll commonly distributed alongside iTunes, using [AudioToolboxWrappe](https://github.com/dantmnf/AudioToolboxWrapper)

Would you be interested in integrating it into the windows build? @BtbN

**Comment by BtbN** [comment]
Unless that can be statically linked, no. If the binaries here suddenly only worked if you have iTunes installed, that's not exactly practical.

**Comment by Aniark** [comment]
Just tried to build and find it can statically linked, referred to this [comment](https://www.reddit.com/r/ffmpeg/comments/15ibw8q/comment/kdve4bu/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)

After testing, it doesn't need the whole iTunes, just dll files above, which could be extracted by using [makeportable](https://github.com/nu774/makeportable)

If you are an iTunes user, you may need to refer to [this commit](https://github.com/dantmnf/AudioToolboxWrapper/compare/master...cynagenautes:AudioToolboxWrapper:master) for minor modifications, or just copy the above dll to the ffmpeg root directory, or your environment `Path`

```
ASL.dll
CoreAudioToolbox.dll
CoreFoundation.dll
icudt62.dll
libdispatch.dll
libicuin.dll
libicuuc.dll
objc.dll
msvcp140.dll
vcruntime140.dll
```

`msvcp140.dll` and `vcruntime140.dll` are not necessary, if you have Visual Studio 2015-2022 installed

![image](https://github.com/user-attachments/assets/6a28c9d7-da98-4725-bd61-ee914e14bf17)

Without those, ffmpeg can still works, it shows error only when using `aac_at` @BtbN

**Comment by BtbN** [comment]
I don't see any mention of statically linking in there.
To me this reads like afterwards, the resulting ffmpeg binary won't launch unless those DLLs are around, which is not an acceptable dependency.

Also, it looks like this needs modifications to ffmpeg itself. Those will need to be upstreamed first. I don't see why support for CoreAudio on Windows couldn't be included, sans licensing issues, given it's not a system-lib on Windows.
