### ISSUE TITLE
Scoop can't install ffmpeg and raise errors

### ISSUE THREAD

**Issue by Auto-SK** [BtbN/FFmpeg-Builds#34]
![image](https://user-images.githubusercontent.com/65449120/101316969-8a375a80-3898-11eb-8ace-b481abbd05fb.png)

**Comment by BtbN** [comment]
Only the last 14 daily builds are kept. Older builds are rotated out to save space and avoid too much clutter.
If you need an older build for testing, the last build of each month is kept for two years.

**Comment by Auto-SK** [comment]
> Only the last 14 daily builds are kept. Older builds are rotated out to save space and avoid too much clutter.
> If you need an older build for testing, the last build of each month is kept for two years.

Thank you very much.
