### ISSUE TITLE
Add different colors listed on Wikipedia

### ISSUE THREAD

**Issue by mayconhvab1** [BtbN/FFmpeg-Builds#341]
Hello

I would like you to add several of the colors I listed to FFmpeg?

Lists of colors, remembering that there is a great capacity to be added, and the list is beautiful and very complete, list here:
https://en.wikipedia.org/wiki/Impossible_color
https://en.wikipedia.org/wiki/List_of_colors:_A%E2%80%93F
https://en.wikipedia.org/wiki/List_of_colors:_G%E2%80%93M
https://en.wikipedia.org/wiki/List_of_colors:_N%E2%80%93Z

Remembering that there are very few colors in FFmpeg, when giving the view color command, and I would like it to be added, it will be wonderful to have hundreds of colors in FFmpeg.

**Comment by BtbN** [comment]
I'm not going to accept patches to ffmpeg here.
Please send patches and feature requests upstream.
