### ISSUE TITLE
Invalid Arm64 image architecture

### ISSUE THREAD

**Issue by dsm5791** [BtbN/FFmpeg-Builds#343]
Invalid Arm64 image architecture
`
$ docker inspect ghcr.io/btbn/ffmpeg-builds/linuxarm64-lgpl-shared-6.1:latest | grep 'Architecture'
    "Architecture": "amd64",
`

**Comment by BtbN** [comment]
Not sure what you're trying to say or point out.
The builds work fine for me and on CI.

**Comment by BtbN** [comment]
All images are for linux and x86_64, and cross compile to the respective target arch, if that's your question.
That's working as intended.
