### ISSUE TITLE
Build with librsvg

### ISSUE THREAD

**Issue by tage64** [BtbN/FFmpeg-Builds#344]
Hello and thanks for this helpful repository!

Would it be possible to add the librsvg decoder to the build? I need a Windows executable with librsvg enabled and it seems very difficult to find an FFmpeg build for windows with that enabled.

Thanks,
Tage

**Comment by BtbN** [comment]
librsvg has an absurd amount of dependencies and would single-handedly more than double the time and size of the build.
So I decided against including it.

**Comment by tage64** [comment]
Ok I see. Would it be possible to have an option to include librsvg? Or can you point me in the right direction how it could be done?

**Comment by BtbN** [comment]
librsvg itself has like 10 big dependencies itself, which all have at least a handful of dependencies on their own.
Large parts of GNOME and glib. You'd have to write a build script for every single one of them, convince them to be statically linked, and put them in the right order.

**Comment by tage64** [comment]
Ok, sad.  I solved it with [CairoSVG](https://cairosvg.org/) instead though which worked great.

**Comment by Jamaika1** [comment]
https://github.com/GyanD/codexffmpeg/issues/1
