### ISSUE TITLE
Update svt-av1 to 2.0.0

### ISSUE THREAD

**Issue by mayconhvab1** [BtbN/FFmpeg-Builds#350]
Hello BtbN.

A new version of the svt-av1 codec library is available, released on March 13, 2024.

**Comment by mayconhvab1** [comment]
As I said before, I can't request a new pull request.
I apologize again for requesting updates here, as this is the only method I am able to request new codec updates that can be reviewed on the official provider's website.

**Comment by BtbN** [comment]
A full dependency update is already pending, and again: Is done pretty much automatically and regularly.
You don't need to ping about updates, unless something (serious security issue, etc.) makes them super urgent.
