### ISSUE TITLE
Please, enable the libvmaf_cuda

### ISSUE THREAD

**Issue by tormento** [BtbN/FFmpeg-Builds#353]
Please, enable the libvmaf_cuda.

When I try to run

`ffmpeg -hide_banner -nostdin -f lavfi -i color=c=black:s=320x240:d=1 -lavfi [0:v][0:v]libvmaf_cuda=eof_action=endall:n_threads=15:model=version=vmaf_v0.6.1 -f null -`

I get

```
[AVFilterGraph @ 0000025fbd5c5700] No such filter: 'libvmaf_cuda'
Failed to set value '[0:v][0:v]libvmaf_cuda=eof_action=endall:n_threads=15:model=version=vmaf_v0.6.1' for option 'lavfi': Filter not found
Error parsing global options: Filter not found
```

**Comment by BtbN** [comment]
As explained before(https://github.com/BtbN/FFmpeg-Builds/issues/328), libvmaf_cuda cannot be statically linked, and is also not compatible with the GPL.
So no, that won't happen unfortunately.
