### ISSUE TITLE
[REQ] Intel cartwheel builds (too)

### ISSUE THREAD

**Issue by forart** [BtbN/FFmpeg-Builds#354]
Hi there, thanks for your work !

It would be interesting to have [cartweel](https://github.com/intel/cartwheel-ffmpeg) builds too to take advantage of C/GPU optimizations, for those - like me - who encodes on that hardware.

Hope tat inspires !

**Comment by BtbN** [comment]
You can point the build script at whatever repo you like, but I won't be adding anything except vanilla FFmpeg to CI or the repo itself.

**Comment by forart** [comment]
Thanks anyway.

**Comment by BtbN** [comment]
Just provide their repo to the build script, and it'll happily build you their fork.
But I can't add any more or less random fork here. The list of build artifacts is already a mess as it is.

**Comment by forart** [comment]
Well, check out their repo (previous linked too) seems that there are some instructions:
https://github.com/intel/cartwheel-ffmpeg

BTW a guide on how to build is here: https://github.com/intel/cartwheel-ffmpeg/wiki/How-to-build-cartwheel-ffmpeg

Hope that inspires.

**Comment by oscarbg** [comment]
Hi,
sorry for joining but related, I would be more interested in https://github.com/intel/cartwheel-ffmpeg/commits/master/
for testing the included d3d12va H265 encoder:
https://github.com/intel/cartwheel-ffmpeg/commit/e327b9f471bc5921d7594579725b08e3d0918969
would be nice making some snapshots from time to time (maybe weekly or monthly)..
anyway thanks..

**Comment by forart** [comment]
Very interesting comment about Cartwheel build:
https://www.phoronix.com/forums/forum/phoronix/latest-phoronix-articles/1456715-intel-ffmpeg-cartwheel-2024q1-brings-new-filter-to-transform-old-content?p=1456721#post1456721
