### ISSUE TITLE
[Request] Enable new d3d12va decoders

### ISSUE THREAD

**Issue by oscarbg** [BtbN/FFmpeg-Builds#355]
Hi,
FFMPEG main branch supports D3D12VA since december.. plase can add that to full build in addition to existing D3D11VA decoders?

    ffmpeg -hwaccel d3d12va -i c:\av1\sample.mp4 -f null -

log:

    Device creation failed: -12.
    [vist#0:0/av1 @ 00000235a67716c0] [dec:libdav1d @ 00000235a676df80] No device available for decoder: device type d3d12va needed for codec libdav1d.

also testing with -hwaccel d3d13va (doesn't exist) reveals d3d11va missing from list:

    [vist#0:0/h264 @ 000001a2282bedc0] Unrecognized hwaccel: d3d13va.
    [vist#0:0/h264 @ 000001a2282bedc0] Supported hwaccels: cuda vaapi dxva2 qsv d3d11va opencl vulkan

EDIT: note I made an equal request to GyanD:
https://github.com/GyanD/codexffmpeg/issues/117

thanks..

**Comment by BtbN** [comment]
Last I checked, d3d13 was not out yet :D
I can't enable any d3d12 stuff until mingw implements support for it.
And once they to, it'll turn on all by itself. So there's not much I can do.

**Comment by BtbN** [comment]
It's a matter of them making a new release and crosstools-ng pulling it in, and then me updating the mingw version in the ct-ng configs.

**Comment by oscarbg** [comment]
ah.. ok!

**Comment by BtbN** [comment]
I just don't see any rush, and a whole bunch of stuff is broken on clang that works fine on gcc.

**Comment by oscarbg** [comment]
thanks!
guess tomorrow build will have it?
out of context, but seems you are enabling win arm64 builds very soon, right?

**Comment by BtbN** [comment]
I don't think I will enable them anytime soon. I still have no idea if they even run, for lack of hardware.
And the list of stuff in each release is already a horrible mess.

**Comment by oscarbg** [comment]
@BtbN just tested today builds with d3d12va and they work great.. thanks!
