### ISSUE TITLE
Hope it can support .a static library of mingw32

### ISSUE THREAD

**Issue by mojie126** [BtbN/FFmpeg-Builds#356]
Hope it can support .a static library of mingw32 or mingw64
thinks

**Comment by BtbN** [comment]
I don't understand what you're asking.
If you mean you want a static library to link into your stuff: That won't be happening.
You wouldn't only need the ffmpeg library, but the static libraries of all other dependencies, all their flags, and the specific order to link them in.
There just is no mechanism to export all of that, and it would also be _huge_ and incredibly fragile.

**Comment by BtbN** [comment]
You can copy them out, sure. But using them to build anything with them will be incredibly tedious and error prone.
Best to use the image and its pkg-config itself if you really want to build something against those libs.

**Comment by BtbN** [comment]
If this is related to the other issue about the Ubuntu 24.04 package issues:
You just found out (one of the reasons) why it's on 24.04 and not any older version.
