### ISSUE TITLE
Hope it can support libvmaf cuda

### ISSUE THREAD

**Issue by hungdx6** [BtbN/FFmpeg-Builds#357]
Can you support libvmaf cuda to speedup vmaf calculation? I tried to add cuda 12.4 but i was failed.
Thank you

**Comment by BtbN** [comment]
The answer hasn't changed since the last two times:
https://github.com/BtbN/FFmpeg-Builds/issues/328
https://github.com/BtbN/FFmpeg-Builds/issues/353
