### ISSUE TITLE
Is `--enable-nonfree` used for lgpl builds?

### ISSUE THREAD

**Issue by TechnikEmpire** [BtbN/FFmpeg-Builds#36]
Sorry of this is posted somewhere, a quick search didn't reveal anything.

**Comment by BtbN** [comment]
Build with --enable-nonfree are nonfree and cannot be redistributed.
So no, it's not and cannot be.

**Comment by TechnikEmpire** [comment]
Alright. I'm trying to figure out why your 4.3.x builds are 15+mb bigger than other builds I've come across is all.

**Comment by TechnikEmpire** [comment]
Closing as you answered original q. Thanks again.

**Comment by BtbN** [comment]
Probably just because more dependencies are built in. The majority of extra size comes from them, not ffmpeg itself.
