### ISSUE TITLE
Builds for version 4.4

### ISSUE THREAD

**Issue by insel-maz** [BtbN/FFmpeg-Builds#360]
Is it possible that the builds for version 4.4 will continue to be created?
As a user of https://github.com/unosquare/ffmediaelement, I was previously happy to have the builds provided under the releases.

Thank you.

**Comment by BtbN** [comment]
You can still manually produce a 4.4 build, though I will not be closely monitoring them for breakages anymore.
I've decided to make it a policy to have master + the latest 3 ABIs of releases. The artifact list is messy enough as it is, and storage and asset space on GitHub is also not unlimited.

FFmpeg 5.0 is two years old at this point, any software that still hasn't caught up should seriously reconsider their priorities (or is unmaintained).
