### ISSUE TITLE
could not read /data/FFmpeg-Builds/.cache/images/base/index.json

### ISSUE THREAD

**Issue by sunpengfei0307** [BtbN/FFmpeg-Builds#364]
Hi! boy, I have a compile problem just like the title, need some help!  Thank you!
Linux ubuntu 5.15.0-102-generic #112-Ubuntu SMP Tue Mar 5 16:50:32 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux  (vmware)
![image](https://github.com/BtbN/FFmpeg-Builds/assets/102022066/c113dcdb-e86f-4969-ae48-028854ed008f)

**Comment by BtbN** [comment]
Just ignore that, there simply is no cache on first build.

**Comment by sunpengfei0307** [comment]
Thank you! but I can't build success and get ffmpeg bin.
1、./build.sh linux64 nonfree 6.0 lto， errors like this and abort!
+ docker run --rm -v /data/FFmpeg-Builds:/uidtestdir ghcr.io/btbn/ffmpeg-builds/linux64-nonfree-6.0-lto:latest touch /uidtestdir/uidtestfile
Unable to find image 'ghcr.io/btbn/ffmpeg-builds/linux64-nonfree-6.0-lto:latest' locally
docker: Error response from daemon: manifest unknown.
2、./makeimage.sh linux64 nonfree 6.0 lto， errors like this and abort!
ERROR: could not read /data/FFmpeg-Builds/.cache/images/base/index.json: open /data/FFmpeg-Builds/.cache/images/base/index.json: no such file or directory
+ rm -f /tmp/tmp.JveedEVrDV.toml
Now, I have no idea abot hot to fix it, or could you show me which release to use?(I want to build a full version, need include the vulkan/cuda/libplacebo for hwaccel)

**Comment by BtbN** [comment]
The first error is because the second step did not complete.
And the second one simply is not an error.
Both of these outputs are expected and normal.
So there has to be an actual error further up somewhere.

Also, you don't need a nonfree build for any of the stuff you listed.
The only difference in a nonfree build is that libfdkaac is present.

**Comment by sunpengfei0307** [comment]
> The first error is because the second step did not complete. And the second one simply is not an error. Both of these outputs are expected and normal. So there has to be an actual error further up somewhere.
> 
> Also, you don't need a nonfree build for any of the stuff you listed. The only difference in a nonfree build is that libfdkaac is present.

Yes, if the first error (not find) is not resolved, the compilation script will exit directly from my end, and I will not be able to proceed with the subsequent steps. I am not sure what to do now. 
I hope you can provide assistance in resolving this error or bypassing it！ Thank you!

**Comment by BtbN** [comment]
Again, it not finding the cache is not an error.
It printing that is normal and expected.
Please find the actual error in your logs, otherwise there is nothing I can do for you.

**Comment by sunpengfei0307** [comment]
> Again, it not finding the cache is not an error. It printing that is normal and expected. Please find the actual error in your logs, otherwise there is nothing I can do for you.

Thank you again!  But no other errors output. Can I use it on centos8 someway?   I find the shell script use apt-get, I guess not.
