### ISSUE TITLE
ffmpeg-6.0 libplacebo disabled

### ISSUE THREAD

**Issue by sunpengfei0307** [BtbN/FFmpeg-Builds#366]
![image](https://github.com/BtbN/FFmpeg-Builds/assets/102022066/02c02bc2-081e-4814-b1dd-c3c74d07d11f)
Hi!  I build the nofree/gpl  , but libplacebo is disabled default, how could  I enable it ,  build ffmpeg-7.0? Is there a problem with the current(6.0/5.0) version？

**Comment by BtbN** [comment]
latest libplacebo is not compatible with old ffmpeg versions.
Just use master or if you insist on using an older version, 6.1 or more recent.
