### ISSUE TITLE
Speeding up video doesn't affect duration

### ISSUE THREAD

**Issue by sdfdger** [BtbN/FFmpeg-Builds#369]
Posting here because https://github.com/FFmpeg/FFmpeg disabled the Issue tab

`setpts` speeds up the video, but the duration stays the same. The rest of the video is the last frame.

Version:
https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip
from "Latest Auto-Build (2024-04-30 12:51)" https://github.com/BtbN/FFmpeg-Builds/commit/1a3e916b912dcd3f89c4502803fb08284a586a78

`ffmpeg -i "sampletext.mp4"  -filter:v "setpts=PTS/10" "10x sampletext.mp4"`

[sampletext.mp4](https://github.com/BtbN/FFmpeg-Builds/assets/96592917/25fdb53d-4731-442c-b86d-08c7b166a0bd)
[10x sampletext.mp4](https://github.com/BtbN/FFmpeg-Builds/assets/96592917/98d01133-465c-4186-93a0-92f1a43ef6df)

**Comment by BtbN** [comment]
Please direct user questions at the appropriate channels(#ffmpeg IRC or ffmpeg-user ML).
These issues are for issues regarding these builds specifically.

**Comment by sdfdger** [comment]
Someone should repost this to https://trac.ffmpeg.org

**Comment by BtbN** [comment]
trac is not a support channel either, and this does not look like any kind of bug to me.
