### ISSUE TITLE
Versin file

### ISSUE THREAD

**Issue by brendan8c** [BtbN/FFmpeg-Builds#37]
ffmpeg-N-100459-ga7f9b3b954-win64-gpl-vulkan.zip -- 100 MB.
ffmpeg -i (no working)
ffmpeg -version (no working)

**Comment by garoto** [comment]
Perhaps because vulkan builds needs proper vulkan backend, otherwise the binary won't even start.

See: https://github.com/BtbN/FFmpeg-Builds/issues/8#issuecomment-704554479

**Comment by BtbN** [comment]
Todays builds are working fine on my end.
Likely as garoto says, try a non-vulkan build, or get a vulken capable graphics driver.

**Comment by brendan8c** [comment]
Yes i'm uploaded other version file and this command is working! 
ffmpeg-N-100459-ga7f9b3b954-win64-gpl.zip -- 93 MB.
