### ISSUE TITLE
LLVM based toolchain

### ISSUE THREAD

**Issue by IdrisKalp** [BtbN/FFmpeg-Builds#372]
Hi

Is it possible to build and use LLVM-based toolchains in these builds?

**Comment by BtbN** [comment]
The win-on-arm builds use clang, for lack of a a gcc based toolchain.
gcc-15 added support for it though, so in the future, that will likely also switch back to ct-ng again.
Why?

**Comment by IdrisKalp** [comment]
I used to do my own builds from scratch with clang. I noticed some performance gain over gcc. Though I'm not sure if all other conditions were same.

**Comment by BtbN** [comment]
It seems unlikely the effort really.
clang is not magically faster than gcc. I wouldn't really know how to bootstrap a toolchain for clang either. If you can cook up a working base image, it might work, but would likely need adjustments in all scripts, since a lot of build systems don't expect it.

**Comment by BtbN** [comment]
The huge majority of code involved is C, not C++ though.
And the most performance critical parts are all written in assembly.
There really is no need to pick one toolchain over the other. Getting win-on-arm to build with clang was a huge pain already, which needed a ton of workarounds implemented.

**Comment by BtbN** [comment]
That seems like quite some obstacles to me.
Sorry, but I see zero reason to put in the extra work just to not just keep using gcc.
