### ISSUE TITLE
openssl built for windows builds but is not enabled

### ISSUE THREAD

**Issue by sslivins** [BtbN/FFmpeg-Builds#373]
I was trying to use openssl for a windows build and I see that it's built successfully in the docker containers however this line is preventing openssl from being enabled in the ffmpeg configuration:

https://github.com/BtbN/FFmpeg-Builds/blob/afcd9939cfaa1bec3a64044dc1f9d33481c3da42/scripts.d/25-openssl.sh#L97

I removed it locally and it appears to be working correctly.  Is there a reason it's not enabled or was this an oversight?

**Comment by BtbN** [comment]
Windows uses schannel, not openssl.

**Comment by BtbN** [comment]
More specifically, openssl is only built at all because other things depend on it.
Using an OS provided tls library which gets regular updates is largely preferable over a forever frozen in time version of openssl.

**Comment by sslivins** [comment]
the schannel implementation is still quite buggy and we ran into some serious issues with it hanging in production.  Nevertheless is this was intentional that's fine, I can patch it locally

**Comment by sslivins** [comment]
will do, thanks

**Comment by sslivins** [comment]
I should clarify it's not schannel proper, rather the ffmpeg schannel shim that's buggy.  I will be following up with ffmpeg but for the short term openssl solves the issue.

Btw, this is a fantastic project, thank you for all you do!

**Comment by BtbN** [comment]
Yeah, that's what I mean as well.
The only issues with hangs related to schannel was in the hls code and that got fixed years ago.
So even just an issue with "doing XYZ when using the schannel backend causes this and that." would be valuable.

**Comment by sslivins** [comment]
im familiar with the hls issue, this particular issue is with rtmps
