### ISSUE TITLE
config.h header file

### ISSUE THREAD

**Issue by ShootingKing-AM** [BtbN/FFmpeg-Builds#38]
Hello,

There are many un-added header files in the build archives. All those can be added from source Ffmpeg repo but config.h file is auto generated when built, can you please add autogenerated config.h file into file archives/include folder ? 

Thanks.

**Comment by BtbN** [comment]
config.h is not a public header, it's only purpose is to pass the results of configure to the ffmpeg source.
None of the other public headers require it.

The headers currently part of the archive are what `make install` installs, external users of the libraries are not supposed to use any other headers.
Why do you think you need config.h?

**Comment by ShootingKing-AM** [comment]
Firstly, thnks for the quick reply.

> config.h is not a public header, it's only purpose is to pass the results of configure to the ffmpeg source.
> None of the other public headers require it.
> 
> The headers currently part of the archive are what `make install` installs, external users of the libraries are not supposed to use any other headers.
> Why do you think you need config.h?
Sometimes it's required to use internal functions, especially in my case implementing customized Hardware encoding/decoding, so I need to include internal files like `thread.h`, `hwcontext_internal.h`, etc... Yes, I understand these are vulnerable to future code changes and may break with future releases, that's why I didn't ask to include these internal headers. 

But config.h has thousands of switches, which modifies code inclusion, no extra functions in it. I tried to manually generate this file, but with that many switches it's nearly impossible. config.h in required by many (internal) headers and also for understanding the source-code itself.

Thanks.

**Comment by BtbN** [comment]
config.h is not at all required to use the public API.
Using internal API from outside of ffmpeg code is not supported and a terrible idea.
Those APIs/ABIs can change at any time without advance notice.

If you are implementing new codecs/filters/..., you need to fork the main ffmpeg repo and implement them there.
External codecs/filters are explicitly not supported by ffmpeg.

I'm not going to include internal headers. If you feel like some API is missing, open a bug with FFmpeg and ask for a public API.

**Comment by ShootingKing-AM** [comment]
Config.h does not have any API/ABI in it though. It's just a reflection of build time configuration.
