### ISSUE TITLE
ERROR: vulkan requested but not found

### ISSUE THREAD

**Issue by timothymowens** [BtbN/FFmpeg-Builds#381]
When building for Windows, I get the error:

`ERROR: vulkan requested but not found`

I'm building in WSL using Windows 10 and Ubuntu 22.04.04 using the latest from this repo as of the date of this issue posting.  The following commands are what was used:

`service docker start`
`sleep 5`
`makeimage.sh win64 nonfree`
`build.sh win64 nonfree`

I found a related reddit post stating that the ffmpeg is looking for newer Vulkan headers:

https://www.reddit.com/r/ffmpeg/comments/xe4otp/error_vulkan_requested_but_not_found/

**Comment by BtbN** [comment]
Works fine for me and on CI. Without further info, there's not much I can tell you.

**Comment by timothymowens** [comment]
What info would help?

**Comment by BtbN** [comment]
The actual error and what you did to deviate from the upstream repo here.

**Comment by timothymowens** [comment]
That's the actual error I'm receiving.  It's in the final step when it builds ffmpeg itself.  I'm just going to completely delete everything and start over from scratch, see if the error still occurs.

**Comment by BtbN** [comment]
The actual error is gonna be in the config.log in the build dir.
There has been no changes to ffmpeg configure in a few days, and it's been building fine here and locally. And nothing here has changed in a few days either.
So there has to be some deviation from how stuff is set up here.

**Comment by BtbN** [comment]
Just did a full build of nonfree again to confirm: Indeed still works fine.

**Comment by timothymowens** [comment]
Well I didn't alter anything on my end.  I'm doing another build now after starting over from scratch by removing everything related to this repo and starting all over again.  I'm guessing that since I hadn't built since March, perhaps something old is jamming things up.  I'll reply here if the new build is successful.

**Comment by BtbN** [comment]
My only guess would be that you had some really old images still around and used those for the build, so it seems like a good plan.

**Comment by timothymowens** [comment]
OK.  Taking the nuclear option worked.  Thank you and apologies.
