### ISSUE TITLE
ffmpeg n7.0 "driver does not support required nvenc api. required 12.2 found 12.1" 

### ISSUE THREAD

**Issue by h9j6k** [BtbN/FFmpeg-Builds#382]
Hello, 

Thanks for giving us this wonderful build of ffmpeg binaries without us having to do everything from scratch. 

I used to use your linux amd64 gpl shared build 6.x daily for shotcut. However I have trouble switching to the 7.x branch. I got the error as noted in the issue title

```
"driver does not support required nvenc api. required 12.2 found 12.1" 
```

I found that you actually have two different nvenc sdk flavors for ffmpeg <= 6.1 and >= 7.0 as in

https://github.com/BtbN/FFmpeg-Builds/blob/master/scripts.d/50-ffnvcodec.sh

Could you kindly consider relegating the 7.0 branch to nvenc sdk 12.1? Sdk 12.2 requires nvidia driver 550+ but I am on debian 12 stable and the latest nvidia driver I can have on debian stable is 535. 

Thanks.

**Comment by h9j6k** [comment]
> The 7.0 branch does not have any of the 12.2 specific features, so that should be safe to do. I'd still strongly suggest to update your drivers, since Nvidia recently fixed a bunch of security issues, and it's not like Debian can backport any fixes.

Thank you so much. According to Debian tracker, 

https://tracker.debian.org/pkg/nvidia-graphics-drivers

their nvidia driver team are actively fixing driver security issues, they are likely to keep the stable nvidia driver on the 535 branch though.

**Comment by BtbN** [comment]
They can't do much more than wait for nvidia to release a new stable driver, which happens relatively infrequently.
Given it's open source, they cannot backport any fixes unless they happen to be in open source parts of the driver.

**Comment by h9j6k** [comment]
> They can't do much more than wait for nvidia to release a new stable driver, which happens relatively infrequently. Given it's not open source, they cannot backport any fixes unless they happen to be in open source parts of the driver.

You're right. But just like them waiting for nvidia to release closed source fixes, I dont think I can do much other than waiting for debian team to add newer drivers to debian stable :(

**Comment by h9j6k** [comment]
The latest n7.1 build requires driver 550+ and debian stable nvidia driver is still on 535. Even the unstable debian only offers driver 545. If n7.1 branch as before does not have any of the 12.2 specific features, could you kindly again consider relegating the n7.1 build to nvenc sdk 12.1? Thanks.

**Comment by BtbN** [comment]
7.1 supports everything there is, since it was branches just a few weeks ago. So downgrading the SDK would remove features from it.
Not quite sure what to do here. Generally, needing somewhat recent drivers (550+ isn't even that new anymore) for a very recent version of ffmpeg seems reasonable.
Can always manually make a build that fits your needs, adapting the ffnvcodec script is trivial.

**Comment by h9j6k** [comment]
Thank you. I was trying to play with the latest vulkan h264/265 encoding features so I guess I need to upgrade driver instead of using old sdk.
