### ISSUE TITLE
libvpx issue on windows

### ISSUE THREAD

**Issue by WolfTwi97** [BtbN/FFmpeg-Builds#383]
hello there, im using windows and i tried this command: "ffmpeg",
          "-threads", "4",
          "-i", `${__dirname}/../assets/${id}.mp4`,
          "-c:v", "libvpx", "-b:v", "300k", "-preset", "ultrafast", "-vf", "scale=480:360", "-aspect", "4:3", "-                pix_fmt", "yuv420p",
          "-c:a", "libvorbis",
          "-r", "30", "-g", "30",
          `${__dirname}/../assets/${id}.webm` it gets converted, i tried playing the converted video on a gaming console, but does not work. im currently trying to use vp8 for webm formats.

**Comment by BtbN** [comment]
Other than -preset not being a valid option for libvpx, I see no issue with the command.
Are you sure that gaming console supports vp8 and webm/mkv?
Does it play in vlc/mpv/...?
In any case, this is not the right channel for user support questions, if the file is working fine in a regular player, there is no issue.

**Comment by WolfTwi97** [comment]
never mind, please just close this.
