### ISSUE TITLE
linuxarm32 build help

### ISSUE THREAD

**Issue by harishreddy50552** [BtbN/FFmpeg-Builds#389]
Hi all,
I'm trying to get a linux arm32 build working and i need a bit of help on that front.
I'm following the linuxarm64 as reference point and working on it and i see that it has a crosstool-ng config file.

https://github.com/BtbN/FFmpeg-Builds/blob/master/images/base-linuxarm64/ct-ng-config

1. Wanted to understand what all flags/toolchain was set for linuxarm64. I tried to use the same version of crosstool-ng and 
was not getting the same config as mentioned in the ct-ng-config file present in the repo.
2. I tried setting the basic config for arm32 and it is unable to find the compiler and hence would appreciate it a lot if someone can share me the config/script file which sets it for linuxarm64.

**Comment by harishreddy50552** [comment]
Thank you.

So, this file ct-ng-config (for linuxarm64) was edited manually post getting config from the menu by adjusting target architecture/operating system and other parameters via UI?

sorry, i was under the impression that it is autogenerated fully :/

**Comment by BtbN** [comment]
No, you edit it with menuconfig.

**Comment by harishreddy50552** [comment]
right, can you please share the options/flags which was set for linuxarm64 in the menuconfig.

**Comment by BtbN** [comment]
The options are stored in the resulting config file: https://github.com/BtbN/FFmpeg-Builds/blob/master/images/base-linuxarm64/ct-ng-config

**Comment by harishreddy50552** [comment]
Thanks!

**Comment by waayaa** [comment]
[bump] 
@harishreddy50552 did you succeed?
