### ISSUE TITLE
SPIRV-Tools was not found - required for compilation while makeimage.sh win32 gpl-shared 7.0

### ISSUE THREAD

**Issue by chcent** [BtbN/FFmpeg-Builds#390]
This error happened while makeimage.sh win32 gpl-shared 7.0
![image](https://github.com/user-attachments/assets/8c99b191-8c9d-4732-a898-fdb4732ff31f)

**Comment by BtbN** [comment]
First of all, make sure you cleaned up any old images and caches you 
might have had floating around.
Build on CI works fine, so if this is a 32 bit issue, there's likely not 
much else to do but to disable Vulkan entirely on 32 bit.

**Comment by chcent** [comment]
![image](https://github.com/user-attachments/assets/81371c99-4f78-49c6-8443-9ab067ae4683)
Thank you
It failed when ./utils/git-sync-deps, so No found happened.

**Comment by BtbN** [comment]
hm, that definitely should fail the build and not create a broken asset cache.
Can't look into it right now, but you mean after downloading that bit of download cache, it works again?

**Comment by chcent** [comment]
> hm, that definitely should fail the build and not create a broken asset cache. Can't look into it right now, but you mean after downloading that bit of download cache, it works again?

yes，it works.
I made it.
