### ISSUE TITLE
Win64 - SVT-AV1 encoding uses a single core only in latest auto-build with SVT-AV1 lib v2.1.2

### ISSUE THREAD

**Issue by Rus4kova** [BtbN/FFmpeg-Builds#397]
In the auto-builds with SVT-AV1 encoder lib v.2.1.2 encoding is single core only. Where as auto-builds with SVT-AV1 lib 2.1.1.1 or earlier is using all available cores. If this is related to SVT-AV1 lib v2.1.2 or FFMPEG, I don't know.

**Comment by BtbN** [comment]
I doubt I can do much if anything about that from here.
You'll need to report such bugs upstream.
