### ISSUE TITLE
Stable link to latest builds

### ISSUE THREAD

**Issue by scriptorian** [BtbN/FFmpeg-Builds#4]
It would be very useful to have links with stable paths that are maintained to point at the relevant latest builds.
I'm trying to script up installing FFmpeg on Windows and the paths have just changed. I don't think there was any way I could have predicted what today's path was going to be. I'm trying to use the 4.3.1 shared build.
Thanks!

**Comment by BtbN** [comment]
I'm not sure how I could do that. Due to the nature of Github releases, the links are going to inevitably change, even if filenames were consistent, in which case important information about the contents would be lost.

Releases are also on a rotation, to avoid piling up hundreds and hundreds of releases. So no given link will exist forever.

**Comment by BtbN** [comment]
https://github.com/BtbN/FFmpeg-Builds/wiki/Latest That's probably the closest to any kind of static links I can provide.
Page should be reasonably machine readable.

**Comment by majkinetor** [comment]
It would be great not to build redundant stuff - perhaps check if there was commit before night release ?

**Comment by scriptorian** [comment]
Thanks very much for the update, I've read that page in my script and used the relevant link.

**Comment by BtbN** [comment]
> It would be great not to build redundant stuff - perhaps check if there was commit before night release ?

That would add an insane amount of complexity, for not virtually no functionality gained.
Specially cause it'd also need to keep track of base image and dependency updates, check multiple branches...

So no, builds will just blindly be made every day. So far not a single day without commits went by anyway.

**Comment by mimi89999** [comment]
You can also use https://github.com/BtbN/FFmpeg-Builds/releases/latest as a stable link to the latest release.
