### ISSUE TITLE
Videos with HDR, other pixel formats like prores and yuva444p12le are not displayed in ffplay

### ISSUE THREAD

**Issue by mayconhvab1** [BtbN/FFmpeg-Builds#401]
Today I performed a video test in AV1 and VP9 SMPTE ST 2086 HDR10.
But then I only realized that players like VLC, MPV, PotPlayer and MPC-BE perform the display quality for these pixel formats for the image.

I also realized that it is a little difficult or almost impossible to convert video formats in MP4, WebM and MKV to SMPTE ST 2085 HDR 10 color.

If possible, can you send me the code to convert the video to MP4 H.264 in this quality?

I want to use HDR10 from SMPTE 2086 but it is as a test base, and see how the images look and how much they improve.

I searched on Google, forums on FFmpeg Reddit and I did not find the solution to convert to this format of video quality and pixel.

And about prores and yuva444p12le, they also don't play in the ffplay master version that I always use to download videos with yt-dlp on Windows 11 that I use here.

My video card is an AMD R5 220, fortunately VLC and other video playback software play well, but I do believe that FFmpeg and ffplay have the best and most advanced codecs and updated versions that can play video and audio in sync in the best possible quality.

I believe it is a patch that has not yet been added to FFmpeg and ffplay to play videos in HDR, prores and yuva444p12le.

If I'm wrong, can you send me a code or give me information on how to play videos in prores and HDR SMPTE ST 2086?

For MP4, WebM or MKV video formats, which I have here.

Thanks in advance

Furthermore, I believe it is my video card that does not support HDR or prores in ffplay using Windows.

Or a patch that has not yet been released to reproduce it.

Thanks in advance.

**Comment by BtbN** [comment]
I don't quite understand what you're asking. But it does not sound related to the builds.
Please direct usage questions to the appropiate channels, like the ffmpeg-users mailing list, or #ffmpeg on libera.chat.
