### ISSUE TITLE
VVC and H.266 are ready to use?

### ISSUE THREAD

**Issue by mayconhvab1** [BtbN/FFmpeg-Builds#404]
Hello

I noticed that some complications of the VVC and H.266 video codec are already available in your master repository.

This topic I created is just a question and I would like to know if it is ready for conversion and playback of video formats.

Can it already be downloaded in the master version or will it be necessary to wait for version 7.1 or 8.0 of FFmpeg to arrive so that it can be used. Is the necessary information about the new video codec ready to be used?

I asked this question because in the future I would like the yt-dlp developers to develop the same API and codec information for the platform (of course, in accordance with FFmpeg's terms and conditions), so that we can download videos from YouTube and YouTube Music with the opus and m4a audio codecs within VVC and H.266.

Thank you in advance.

BtbN, as soon as you can answer this question according to your information you can close this topic, thank you very much.

**Comment by BtbN** [comment]
I don't know, I'm not involved in the development of it. So my guess is as good as yours.
I added libvvcenc a while ago, so you can use it for encoding. But it's unsurprisingly abysmally slow.

Not sure I quite understand the question. If you download a built of master, it will contain everything that's in ffmpeg master at the time of build.
