### ISSUE TITLE
why windows build releases ffmpeg no  avfoundation

### ISSUE THREAD

**Issue by u32744** [BtbN/FFmpeg-Builds#408]
ffmpeg -f avfoundation -i 1 -r 30 out.yuv

[in#0 @ 0000026666d50e00] Unknown input format: 'avfoundation'
Error opening input file 1.
Error opening input files: Invalid argument

**Comment by BtbN** [comment]
Because Windows is not OSX? Huh?

**Comment by u32744** [comment]
windows system

**Comment by BtbN** [comment]
avfoundation is the OSX screen capture API.

**Comment by u32744** [comment]
where to get ffmpeg release build included avfoundation

**Comment by BtbN** [comment]
Probably any build for OSX.

**Comment by u32744** [comment]
ffmpeg -i 1 -r 30 out.yuv

[in#0 @ 000001edbbfdfa40] Error opening input: No such file or directory
Error opening input file 1.
Error opening input files: No such file or directory

**Comment by BtbN** [comment]
Again, Windows is not OSX. Use the respective capture APIs like gdigrab or ddagrab on Windows.

**Comment by u32744** [comment]
ffmpeg -i 1 -r 30 out.yuv 

would you help to tell me the how to change this  cmd

**Comment by BtbN** [comment]
This is not an ffmpeg support channel. Please use the respective IRC channels or mailing lists.

**Comment by learner-dhx** [comment]
> ddagrab

how to get any builds with ddagrab api?

**Comment by learner-dhx** [comment]
> > ddagrab
> 
> how to get any builds with ddagrab api?

I have download8.0.0 6.0.0 version full build but both no "ddagrab" devices and apis

**Comment by BtbN** [comment]
8.0 is too old for gfxcapture, ddagrab is part of it though, just checked:

```
$ ./ffmpeg.exe -filters | grep dda
ffmpeg version n8.0-33-g22d0f10943-20251113 Copyright (c) 2000-2025 the FFmpeg developers
[...]
 .. ddagrab           |->V       Grab Windows Desktop images using Desktop Duplication API
```

If you want gfxcapture, use the latest version from master.
