### ISSUE TITLE
What`s the difference between builds? lgpl gpl vulkan, shared

### ISSUE THREAD

**Issue by necros2k7** [BtbN/FFmpeg-Builds#41]
subj

**Comment by nanake** [comment]
`gpl` has [these libraries](https://github.com/FFmpeg/FFmpeg/blob/f26b5acfc03375c96e593197a8145ada1b63b1fd/configure#L1720-L1731). `lgpl` does not.

you need `vulkan` driver to run vulkan build. 

`shared` build splits libavutil, libavcodec, libavformat, ... into its own .dll file.
