### ISSUE TITLE
upgrading `FFmpeg-Builds` and upgrading `./makeimage.sh`

### ISSUE THREAD

**Issue by cinnamonmatexfce** [BtbN/FFmpeg-Builds#415]
Hello!
Thanks for this useful project! 💪
My *Docker* knowledge is below zero, so sorry in advance if I'm asking n00b questions...

Everything went fine and I managed to build `ffmpeg-master-latest-linux64-nonfree.tar.xz`, cool!

But I spent 6 hours in building the *Docker* image.

For the next times, will I need to always run `./makeimage.sh` everytime I perform `git pull`?

**Comment by BtbN** [comment]
If anything in the image changes, yes.

**Comment by cinnamonmatexfce** [comment]
OK. Is there any way to check if the image needs to be rebuilt\upgraded?

**Comment by BtbN** [comment]
By reading the changes in git. Or just run the scripts again and let them figure it out. If you didn't delete the cache, it should just run through near instantly if nothing changed.

**Comment by cinnamonmatexfce** [comment]
> By reading the changes in git. Or just run the scripts again and let them figure it out. If you didn't delete the cache, it should just run through near instantly if nothing changed.

Oh, there's tha cache, obviously... 🫡


Thank you
