### ISSUE TITLE
Commit 1688e51 breaks compatibility with Windows 7

### ISSUE THREAD

**Issue by LiquidLightning** [BtbN/FFmpeg-Builds#417]
[Commit 1688e51](https://github.com/BtbN/FFmpeg-Builds/commit/1688e51aef6f92e56419f2815bb8b2ec3cf68108) breaks compatibility with Windows 7.

The most recent build that runs on Windows 7 is [from May 31, 2024](https://github.com/BtbN/FFmpeg-Builds/releases/tag/autobuild-2024-05-31-12-50).

Subsequent builds show this DLL-related error message when starting the .exe:

```
---------------------------
ffmpeg.exe - Application Error
---------------------------
The application was unable to start correctly (0xc0000005). Click OK to close the application. 
```

Please revert or correct the commit, or otherwise fix what I suppose is [a linker problem](https://learn.microsoft.com/en-us/answers/questions/1008126/the-application-was-unable-to-start-correctly-\(0xc).

**Comment by BtbN** [comment]
As per the README, the minimum version I care for compatibility with is Windows 10 22H2, anything earlier might or might not work, no effort will be made towards it.

**Comment by John01Smith** [comment]
@BtbN :
> As per the **README**, the minimum version I care for compatibility with is Windows **10** 22H2, anything earlier might or might not work, no effort will be made towards it.

Well, as it clearly doesn't work for Windows 7, 
may I suggest updating the mentioned README 
( [https://github.com/BtbN/FFmpeg-Builds](https://github.com/BtbN/FFmpeg-Builds) ) then, 
more specifically the sentence 
"_... targetting Windows **7** and newer, ..._" 
to 
"_... targeting Windows **10** and newer (effective June 1, 2024), ..._" ? 

Current state is somewhat ... confusing and untrue.

What is the **reason** for supporting only Windows **10**+ ?

Is there any extra effort or work needed to make builds compatible with Windows **7** ?

What has **changed** in the way of **creating** the builds between May 31, 2024 and June 30, 2024 ?

Is the change important, necessary and worth breaking the compatibility with Windows 7 ?

Thank you for your great builds, have a nice day :)

**Comment by BtbN** [comment]
I don't know what it takes to make it compatible with Windows 7. Everything on my side is set up to support Windows 7.
What the dozens of other libraries do I can't tell or reasonably fix. The thing that broke it was probably just a regular round of library updates, and some library uses some feature that Win7 does not offer, or something like that.
Windows 7 is dead and should not be used, so like the readme already correctly says, no effort will be made from my end towards it.

**Comment by BtbN** [comment]
And no, the builds _are_ targetting Windows 7. That's the target version mingw and the compiler are set to.
