### ISSUE TITLE
FFmpeg static library issues

### ISSUE THREAD

**Issue by Mangomm** [BtbN/FFmpeg-Builds#418]
Hello, does ffmpeg not support a way to provide static libraries(xxx.a)? Because in some embedded devices, the use of dll or so library, resulting in a large package of directories, and their own compilation of the lack of a lot of features, compilation is complex.

**Comment by pzhlkj6612** [comment]
Hi. 

Some linked threads:

- #120
- #356

**Comment by BtbN** [comment]
Yep, the above issues explain it already.
If you want to build something fully static, grab the docker images and use the toolchain in there to first build a set of static ffmpeg libraries and then your own stuff.
Though it'll always be targetting glibc, so not sure how helpful that is for embedded devices.
