### ISSUE TITLE
about win32 download

### ISSUE THREAD

**Issue by lihetaoking** [BtbN/FFmpeg-Builds#42]
How to download the version of Win32 ？
 Isn't it supported？

**Comment by BtbN** [comment]
No, there are only 64bit downloads.
If you for some reason still need a 32bit version, you will have to build it manually.

As stated multiples times already, the builds are already very close to the asset size limit, and I'd rather use that space for more 64bit variants than for ultra legacy 32bit builds.

**Comment by lihetaoking** [comment]
OK， thanks！

**Comment by ValZapod** [comment]
What is funny is that is compiled with gcc win32. Cannot it use 64 bit gcc?

**Comment by sudo-nautilus** [comment]
> How to download the version of Win32 ？
>  Isn't it supported？

Check [this](github.com/sudo-nautilus/FFmpeg-Builds-Win32) out

**Comment by BtbN** [comment]
> What is funny is that is compiled with gcc win32. Cannot it use 64 bit gcc?

Not sure what you're talking about.
It's being cross compiled from Linux, and the gcc binary is a 64 bit one, even though it doesn't matter for the compilation result.
