### ISSUE TITLE
Erroneous comments in documentation HTML files

### ISSUE THREAD

**Issue by vlakoff** [BtbN/FFmpeg-Builds#420]
There is a Texinfo issue, initially [reported on GyanD builds](https://github.com/GyanD/codexffmpeg/issues/160):

> Looking at source code of `doc/*.html` files, in a ffmpeg build from 2022 there were comments:
> 
> ```
> 
> ```
> 
> but in the ffmpeg build that I downloaded now, these comments have become:
> 
> ```
> 
> ```
> 
> Notice the first "empty" field.

And afterwards:

> I've had a look at Texinfo code (I used [this mirror](https://github.com/debian-tex/texinfo)), but could not figure out the cause for this. Sadly they don't have a GitHub page, only a [mailing list](https://www.gnu.org/software/texinfo/)…
> 
> I noticed BtbN builds have the same problem (Texinfo 7.1).

**Comment by BtbN** [comment]
Hmm, I don't think I have much if any influence on this. It's probably better to reproduce this with a minimal setup, and then report it upstream to FFmpeg or texinfo themselves, depending on who has the bug.
