### ISSUE TITLE
50-xvid.sh can not work

### ISSUE THREAD

**Issue by indiff** [BtbN/FFmpeg-Builds#424]
`svn --non-interactive checkout --username 'anonymous'  http://svn.xvid.org/trunk/xvidcore`

return the message "forbidden"

i use new code like this:
`echo "retry-tool sh -c \"rm -rf xvidcore xvidcore-1.3.7.tar.gz && wget https://downloads.xvid.com/downloads/xvidcore-1.3.7.tar.gz && tar xvf xvidcore-1.3.7.tar.gz && rm -f xvidcore-1.3.7.tar.gz\" && cd xvidcore"`

**Comment by BtbN** [comment]
That cannot be automatically maintained, so I'd rather not.

Given the website still looks reasonably alive and maintained, and still refers to that URL, I hope it's just an intermittent hiccup, and will be fixed soon.

**Comment by harishreddy50552** [comment]
I'm seeing the same issue.

**Comment by BtbN** [comment]
Here's the cache archive for it. Just throw it into the dl cache dir, symlink 50-xvid.tar.xz to it, and it should run through for now.
[xvid_cache.zip](https://github.com/user-attachments/files/17982764/xvid_cache.zip)

**Comment by Aniark** [comment]
> That cannot be automatically maintained, so I'd rather not.
> 
> Given the website still looks reasonably alive and maintained, and still refers to that URL, I hope it's just an intermittent hiccup, and will be fixed soon.

I had the same problem a couple months ago, so I guess it's not a 'intermittent hiccup'

**Comment by BtbN** [comment]
It definitely worked fine again in the meantime, and then broke again.
Something is up with that server. It works fine when opened in a browser, but responds 403 when accessed via svn.

**Comment by BtbN** [comment]
I sent them an E-Mail about it, server is fixed now.
