### ISSUE TITLE
gdigrab grab support for shared lib

### ISSUE THREAD

**Issue by haris-pp** [BtbN/FFmpeg-Builds#428]
I am using this build for Windows 64 with MSVC compiler, I need to capture screen using c++ code using gdigrab, but I can see 
Error: Input format not found: gdigrab

So just checked  using the code for  gdigrab

```
 const AVInputFormat *fmt = nullptr;
    void *opaque = nullptr;

    while ((fmt = av_demuxer_iterate(&opaque))) {
        qDebug() << fmt->name;
    }

```
But does not print gdigrab

Then I check the build config for ffmpeg  using 
    `.\ffmpeg.exe -buildconf`

Which do not  include  --enable-gdigrab

But when I check the ffmpeg exe with formats arg

`      .\ffmpeg.exe -formats
`
Give the result

 **D d gdigrab         GDI API Windows frame grabber**

Which says  gdigrab   is there with ffmpeg exe. And I can screen capture with this exe too.

So is the build for windows does not enabled with gdigrab, if not how the ffmpeg.exe  can capture screen?. I assume the lib and binaries are built using the same config.

**Comment by BtbN** [comment]
There is no configure switch for every single filter or input device.
gdigrab simply uses the Windows API and does not need to be explicitly enabled.

**Comment by haris-pp** [comment]
Thanks for reply,

Then do you have any idea why this not simple code work with screen capture

avformat_network_init();
    
    AVFormatContext *formatCtx = nullptr;
    AVDictionary *options = nullptr;
    
    const char *inputSource = "desktop";
    const char *inputFormat = "gdigrab";

    // Initialize options
    av_dict_set(&options, "video_size", "800x600", 0);
    av_dict_set(&options, "offset_x", "100", 0);
    av_dict_set(&options, "offset_y", "100", 0);
    av_dict_set(&options, "framerate", "30", 0);

    // Debug options
    char *dump = nullptr;
    av_dict_get_string(options, &dump, '=', ',');
    qDebug() << "Options: " << dump;
    av_free(dump);


    const AVInputFormat *fmt = nullptr;
    void *opaque = nullptr;

    while ((fmt = av_demuxer_iterate(&opaque))) {
        qDebug() << fmt->name;
    }


    // Find input format
   const  AVInputFormat *inputFmt = av_find_input_format(inputFormat);
    if (!inputFmt) {
        qDebug() << "Error: Input format not found:" << inputFormat;
    }

    // Open input
    int ret = avformat_open_input(&formatCtx, inputSource, inputFmt, &options);
    if (ret < 0) {
        char errbuf[AV_ERROR_MAX_STRING_SIZE];
        av_strerror(ret, errbuf, sizeof(errbuf));
        qDebug() << "Error: Unable to open input source:" << inputSource << ", " << errbuf;
        return;
    }
    
    It always print
    
    Error: Input format not found: gdigrab
    Error: Unable to open input source: desktop ,  No such file or directory

**Comment by BtbN** [comment]
I can't really help you with usage questions here. The issues are reserved for issues with the builds themselves.
You can ask on the #ffmpeg IRC channel or on the ffmpeg-user mailing list.
If the ffmpeg exe lists gdigrab, it's definitely there, and it's simply a question of correct API usage.

**Comment by haris-pp** [comment]
Sure, thanks for your feedback.
