### ISSUE TITLE
Feature Request: Option to output to folder instead of compressed archive

### ISSUE THREAD

**Issue by NicholasFlamy** [BtbN/FFmpeg-Builds#438]
So in this block of code, it creates a compressed archive (zip on Windows and xz tar for Linux) for the output:
https://github.com/BtbN/FFmpeg-Builds/blob/93aace027adccefcc3f4cd7a0647eea54980dc9b/build.sh#L61-L67

Since I'm trying to make my setup on my server reproducible, the best option for me would be to fork and make the one change and then pull from my fork, but this requires me to update my fork.

If you would be open to having an option (either an env, a command line flag, or addin etc.) I would be happy to implement it and PR it. This way, there's no need for me to maintain a fork, and if someone else finds it useful, they will benefit.

Also, I'm the same guy who made #426. (If you want me to close that one because it's not planned, I will do that, just lmk!)

**Comment by NicholasFlamy** [comment]
> It kinda already does that, so you can achieve is by just hitting Ctrl+C at the right time, basically when it starts generating the archive. Stuff would then still sit in the ffbuild subdir.

Yep, I saw that, just that Ctrl+C isn't the greatest for an automated cronjob 😜.

> Adding an option for the script to bail early should be easy enough.

What would be your prefered way to add an option though?

**Comment by BtbN** [comment]
Just provide FFBUILD_OUTPUT_DIR as environment variable to the build script, and what normally ends up in the archive gets written there.

**Comment by NicholasFlamy** [comment]
Dude, you're amazing! Didn't think you would do that so quick. Will test!
