### ISSUE TITLE
Disable svt-av1 lto?

### ISSUE THREAD

**Issue by Uranite** [BtbN/FFmpeg-Builds#439]
svt-av1 has thinlto enabled by [default](https://gitlab.com/AOMediaCodec/SVT-AV1/-/commit/13a54d08f161bd1ff21a6259b8ed54b279691d6e)
should we disable it even if its not causing any issue?

**Comment by Uranite** [comment]
> The builds here only use gcc, thinlto is a clang option.

ah yeah but it seems that lto is still enabled by default for gcc
i'm just asking since in the past lto was [disabled](https://github.com/BtbN/FFmpeg-Builds/commit/fcc613624831574945eb720d757f8acb53b69cd1) for vvc

**Comment by BtbN** [comment]
It actively caused issues for vvc (ICE during linking even), but as long as it works for svt-av1, I see no reason to disable it.
