### ISSUE TITLE
could you enable AVS3 decoder,thanks

### ISSUE THREAD

**Issue by 617778859** [BtbN/FFmpeg-Builds#47]
AVS3 decoder is now used in China currently, just as "https://ffmpeg.org/ffmpeg-codecs.html#libuavs3d" sayed.
libuavs3d need to explicitly configure the build with --enable-libuavs3d.
Thank you, very much!

**Comment by BtbN** [comment]
It already is:
https://github.com/BtbN/FFmpeg-Builds/blob/master/scripts.d/50-uavs3d.sh

**Comment by 617778859** [comment]
> It already is:
> https://github.com/BtbN/FFmpeg-Builds/blob/master/scripts.d/50-uavs3d.sh

OK
thanks, I got it ,thanks
