### ISSUE TITLE
Symbol builds

### ISSUE THREAD

**Issue by SkyLined** [BtbN/FFmpeg-Builds#48]
I stumbled across an issue in ffmpeg and would like to debug it so I can file a bug report. For this I need a debug build with symbols, to get an accurate stack and determine where in the code the issue is.

Would it be possible to create and host builds of ffmpeg with debug symbols here?

Thanks!

**Comment by BtbN** [comment]
Unfortunately the debug symbols are way too large and blow through the asset file size limit.
You can manually make an unstripped build by enabling the debug addin.

**Comment by SkyLined** [comment]
I am sure it's quite easy to do given experience building ffmpeg. But assuming that I have never done that, could you be a little more descriptive please?

The source code in this repository offers no instructions on how to build it on Windows (I see no Visual Studio projects or other obvious Windows build things - just bash scripts) and I have no idea where to find this "debug addin" that I need to enable.

**Comment by BtbN** [comment]
You need Linux and Docker (Ubuntu in WSL2 with Docker for Windows also works), and then just run the build script and specify the debug addin.
You can look at the PR building workflow for the exact commands, but it shouldn't be more than makeimage.sh win64-gpl + build.sh win64-gpl debug
