### ISSUE TITLE
Windows is blocking the DLLs 

### ISSUE THREAD

**Issue by eu2021** [BtbN/FFmpeg-Builds#49]
Hi,

I'm trying to use a software called Reaper to edit videos. In order to use ffmpeg, I need to put your dll files (the ones that are inside the bin folder) inside a user plugins folder. I tried this in another machine (running windows 8.1) and it works fine. The procedure is simple and is described [here](https://wiki.cockos.com/wiki/index.php/Video_Support). But in my Windows 10 machine Reaper simply doesn`t load those dll files. I noticed that the dll files were blocked in the properties, so I unblocked then. They seem to be unblocked now in properties, but I used all those different methods anyway:
https://www.tenforums.com/tutorials/5357-unblock-file-windows-10-a.html
https://www.tenforums.com/tutorials/124092-use-applocker-allow-block-dll-files-running-windows-10-a.html
https://www.tenforums.com/tutorials/85418-how-disable-downloaded-files-being-blocked-windows.html

Things I tried:
-If I put another dll files there (for other plugins) they (the other plugins) work fine.
-I already downloaded the ffmpeg from 4 different sources and also different versions.
-I tried the same thing with a portable version of Reaper, that uses a different user plugin folder, but it also didn`t work.
-I added the user plugins folder path as exceptions on Windows security and Malwarebytes.
-I tried running Reaper with Windows security and Malwarebytes disabled.
-In Reaper community, nobody seems to have this problem

Someone told me that I should register the DLLs. I tried the procedure of using the command FOR %1 IN (*.DLL) DO REGSVR32 %1, but it gives me the error that says the dll is read but the DLLRegistryServer entry point is not found.
I also tried :
-register using RegDIIView and it gives me the error "Failed to register. Error 127. The specified procedure could not be found". About that error, I read somewhere else that (about an unrelated dll called comdlg32) "Certain DLLs won't register if they are not ActiveX DLLs. comdlg32 is not an ActiveX DLL, that's why you're getting that error."
-right click one of the DLLs > open with > C:\Windows\SysWOW64\regsvr32.exe, and it also gives me the error that says the dll is read but the DLLRegistryServer entry point is not found.

Somehow Windows is preventing Reaper from loading those dll files. What can I do?

Thanks,

What I have:
ffmpeg-n4.3.1-30-g666d2fc6e2-win64-gpl-shared-4.3
Windows 10 Pro
Version 20H2 19042.746
Windows Feature Experience Pack 120.2212.551.0

**Comment by BtbN** [comment]
FFmpeg libraries are not COM libraries you register via regsvr32, no idea where you found that, but it's nonsense and, as you saw, plain doesn't work.
You don't register DLLs in general, you just put them in the correct place where the dynamic linker can pick them up, or the program expects them.

Not sure what you mean by "Windows blocks the DLLs". Do you mean your Antivirus-Software is detecting them or something?

**Comment by pzhlkj6612** [comment]
> Not sure what you mean by "Windows blocks the DLLs".

I guess he meant this:

*This file came from another computer and might be blocked to help protect this computer.*

**Comment by BtbN** [comment]
I don't think there's anything I can do about that. Just click accept or turn that nonsense off.
But I've never heard of that happening for libraries loaded by other applications.

**Comment by eu2021** [comment]
Ok, I will investigate further. If I find something interesting for you I report back. Thanks,
