### ISSUE TITLE
is it possible to also build some win32 versions?

### ISSUE THREAD

**Issue by wstein** [BtbN/FFmpeg-Builds#5]
I am currently working on the Scoop project for an update of the FFmpeg bucket refresh: [#1454](https://github.com/ScoopInstaller/Main/pull/1454)

I am using your build and may ask if you could also build these win32 variants:

- ffmpeg-n4.3.1-20-g8a2acdc6da-win64-gpl-4.3.zip
- ffmpeg-n4.3.1-20-g8a2acdc6da-win64-gpl-shared-4.3.zip

**Comment by BtbN** [comment]
There is no asset space left for additional builds, it's already cutting it very close.
The scripts are setup for 32 bit builds if you really want them, but I don't see the need for 32 bit builds in 2020, so I'd rather use the available space for more useful builds.

**Comment by wstein** [comment]
Ok, You are right. This shouldn't be necessary anymore.

**Comment by camjac251** [comment]
For me, I sometimes need to use the 32-bit version of ffmpeg for AviSynth scripts.
