### ISSUE TITLE
ffmpeg No such filter: 'scale_app'

### ISSUE THREAD

**Issue by luofengda** [BtbN/FFmpeg-Builds#50]
ffmpeg -hwaccel cuvid -c:v h264_cuvid -i a.mp4 -c:v h264_nvenc -b:v 2048k -vf scale_app=1280:-1 -y sdafas.mp4

Need to support ffmpeg scale_app , need to download which file
![QQ图片20210131032834](https://user-images.githubusercontent.com/10395174/106366061-6e21d800-6374-11eb-84ae-be9e0e587043.png)

**Comment by BtbN** [comment]
There is no filter called scale_app. Do you mean scale_npp?
If so, that filter depends on a nonfree nvidia library and such cannot be enabled in a redistributable build.
