### ISSUE TITLE
LV2 support?

### ISSUE THREAD

**Issue by eduard93** [BtbN/FFmpeg-Builds#52]
LV2 (LADSPA Version 2) is a set of royalty-free open standards for plug-ins and matching host applications. LV2 is an extensible framework, allowing a program to load a plugin to do some processing. 

To enable compilation of this filter ffmpeg needs to be configured with `--enable-lv2` ([docs](https://ffmpeg.org/ffmpeg-filters.html#lv2)).

Is it possible to add LV2 support to ffmpeg builds?

**Comment by BtbN** [comment]
Does that refer to this lib: https://lv2plug.in/ ?

**Comment by eduard93** [comment]
Yes.

**Comment by BtbN** [comment]
It has a surprisingly long list of dependencies, so I will have to re-investigate if it can be added.
Right now I'm looking at lilv->{lv2,serd,sord,sratom}. I have not checked if those dependencies have more dependencies of their own.
If that's the case, I probably can't reasonably add it.
