### ISSUE TITLE
Does the latest version support target win32?

### ISSUE THREAD

**Issue by codeofmagic** [BtbN/FFmpeg-Builds#53]
I try to compile for target win32 and get the following error. It looks like the package named ‘win32-gpl’ does not exist. How can I solve this problem? Thank you.

CM@DESKTOP-DGMS1HK MINGW64 /e/FFmpeg-Builds-autobuild-2021-03-02-12-32
$ **./build.sh win32 gpl**
++ dirname ./build.sh
+ cd .
+ source util/vars.sh
++ [[ 2 -lt 2 ]]
++ TARGET=win32
++ VARIANT=gpl
++ shift 2
++ [[ -f variants/win32-gpl.sh ]]
++ ADDINS=()
++ ADDINS_STR=
++ [[ 0 -gt 0 ]]
++ REPO=btbn/ffmpeg-builds
++ REPO=btbn/ffmpeg-builds
++ REGISTRY=docker.pkg.github.com
++ BASE_IMAGE=docker.pkg.github.com/btbn/ffmpeg-builds/base:latest
++ TARGET_IMAGE=docker.pkg.github.com/btbn/ffmpeg-builds/base-win32:latest
++ IMAGE=docker.pkg.github.com/btbn/ffmpeg-builds/win32-gpl:latest
+ source variants/win32-gpl.sh
+++ dirname variants/win32-gpl.sh
++ source variants/default-install.sh
+++ dirname variants/win32-gpl.sh
++ source variants/defaults-gpl.sh
+++ FF_CONFIGURE='--enable-gpl --enable-version3 --disable-debug'
+++ FF_CFLAGS=
+++ FF_CXXFLAGS=
+++ FF_LDFLAGS=
+++ GIT_BRANCH=master
++ docker run --rm docker.pkg.github.com/btbn/ffmpeg-builds/win32-gpl:latest bash -c 'echo $FFBUILD_PREFIX'
Unable to find image 'docker.pkg.github.com/btbn/ffmpeg-builds/win32-gpl:latest' locally
**docker: Error response from daemon: repository docker.pkg.github.com/btbn/ffmpeg-builds/win32-gpl not found: name unknown: docker package "win32-gpl" does not exist under owner "btbn/ffmpeg-builds".**
See 'docker run --help'.

**Comment by BtbN** [comment]
You need to build the image first, no 32 bit builds are done on Github.
Just run the respective script first, with the same arguments.

**Comment by codeofmagic** [comment]
Thank you for your guidance. I will try it right away.

**Comment by codeofmagic** [comment]
Hi BtbN, I successfully built the image, but the compilation still failed. The error message is as follows. The error message shows that my computer is missing the file ‘C:/Program Files/Git/usr/bin/touch’. I checked and found that this file does not exist. There is only a file named ‘c:\Program Files\Git\usr\bin\touch.exe’ under my system. I'm not familiar with Linux and Docker, and I don't know exactly what went wrong. According to the error message, I guess that the build.sh script should be run under Linux system, and I run it on Windows 10 X64. Is my guess correct? Or how can I fix it? Thank you again for your enthusiastic answer.

Error message output：
+ docker run --rm -v /e/FFmpeg-Builds-autobuild-2021-03-02-12-32:/uidtestdir docker.pkg.github.com/btbn/ffmpeg-builds/win32-gpl-shared:latest /usr/bin/touch /uidtestdir/uidtestfile
**docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "C:/Program Files/Git/usr/bin/touch": stat C:/Program Files/Git/usr/bin/touch: no such file or directory: unknown.**

**Comment by BtbN** [comment]
That does seem like your environment is not properly set up.
touch is a very basic tool of every shell environment, and I'd expect it to work on bash for Windows.

Though I have never tested this outside of WSL on Windows, so I can't make any promises it actually works.

**Comment by sudo-nautilus** [comment]
Hi,
I just forked this nice repository and modified the workflow files. It's working and successfully released 32 bit FFmpeg binaries.

The repo : https://github.com/sudo-nautilus/FFmpeg-Builds-Win32

Anyone please test it.

**Comment by sudo-nautilus** [comment]
Hmm,
It's working for me

**Comment by sudo-nautilus** [comment]
> Hi,
> I just forked this nice repository and modified the workflow files. It's working and successfully released 32 bit FFmpeg binaries.
> 
> The repo : https://github.com/sudo-nautilus/FFmpeg-Builds-Win32
> 
> Anyone please test it.

@BtbN please check it

**Comment by BtbN** [comment]
win32 builds are supported by these scripts, yes.
They are just not on auto-build because 32bit is dead and I'd rather use the limited asset space for more variants.

**Comment by sudo-nautilus** [comment]
> win32 builds are supported by these scripts, yes.
> They are just not on auto-build because 32bit is dead and I'd rather use the limited asset space for more variants.

Hmm,
That's why I attempted to do it.

**Comment by sudo-nautilus** [comment]
> Hi,
> I just forked this nice repository and modified the workflow files. It's working and successfully released 32 bit FFmpeg binaries.
> 
> The repo : https://github.com/sudo-nautilus/FFmpeg-Builds-Win32
> 
> Anyone please test it.

@codeofmagic u can use this for getting FFmpeg for your system.

**Comment by codeofmagic** [comment]
> That does seem like your environment is not properly set up.
> touch is a very basic tool of every shell environment, and I'd expect it to work on bash for Windows.
> 
> Though I have never tested this outside of WSL on Windows, so I can't make any promises it actually works.

Thank you BtbN. It is true that my environment is not configured correctly, resulting in no successful build.

**Comment by codeofmagic** [comment]
> > Hi,
> > I just forked this nice repository and modified the workflow files. It's working and successfully released 32 bit FFmpeg binaries.
> > The repo : https://github.com/sudo-nautilus/FFmpeg-Builds-Win32
> > Anyone please test it.
> 
> @codeofmagic u can use this for getting FFmpeg for your system.

Great! This's what I'm looking for. You really solved my problem. thank you very much.

**Comment by sudo-nautilus** [comment]
> > > Hi,
> > > I just forked this nice repository and modified the workflow files. It's working and successfully released 32 bit FFmpeg binaries.
> > > The repo : https://github.com/sudo-nautilus/FFmpeg-Builds-Win32
> > > Anyone please test it.
> > 
> > 
> > @codeofmagic u can use this for getting FFmpeg for your system.
> 
> Great! This's what I'm looking for. You really solved my problem. thank you very much.
Great to hear.
