### ISSUE TITLE
7z

### ISSUE THREAD

**Issue by 89z** [BtbN/FFmpeg-Builds#54]
Have you considered using 7z archives? Seems the size can drop dramatically. For example here:

~~~
https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip (74MB)
https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.7z (22MB)
~~~

https://www.gyan.dev/ffmpeg/builds

**Comment by BtbN** [comment]
Yes, but I opted for zip simply because Windows can extract it without any external tools.

**Comment by 89z** [comment]
Windows does have builtin support for Tar.Gz also, but thats actually worse than Zip

**Comment by BtbN** [comment]
It does not compress notably better, even though it has the advantage of compressing one solid file.
Also, a lot tools have integrated the archives built here into their build toolchains now, so changing to anything else than zip would break things there.

Initially these builds were using 7z archives, but for the pure sake of compatibility with bare Windows, it's going to stay as it is.
Windows doesn't even support zip archived with lzma compression. It can list the archive contents, but fails at actually extracting anything.

So for the sake of consistency, compatibility and accessibility by users without 7zip/winrar/..., it's going to stay as it is.
