### ISSUE TITLE
SVT-VP9 support

### ISSUE THREAD

**Issue by SnGmng** [BtbN/FFmpeg-Builds#56]
I would love to have [SVT-VP9](https://github.com/OpenVisualCloud/SVT-VP9/tree/master/ffmpeg_plugin) ffmpeg encoder enabled!
It requires a small patch and then you can use `--enable-libsvtvp9` to enable it

**Comment by BtbN** [comment]
I will not be adding external patches to the build.

**Comment by rokibhasansagar** [comment]
So, we'll have to wait till ffmpeg includes svt-vp9 by default then... 😞
