### ISSUE TITLE
Question : Can I use this to build a custom FFMPEG Source? 

### ISSUE THREAD

**Issue by Offline-R503B** [BtbN/FFmpeg-Builds#58]
Title, 

I've been trying to follow these "tutorials" on their official webpage and after 4 hours I just hit a wall again and again.

So I hope the question in the title is doable, thnx in advance.

**Comment by BtbN** [comment]
Just change the git clone in build.sh at whatever repo you want to build.

**Comment by Offline-R503B** [comment]
Awesome thanks a lot for the info !  Closing this :D
