### ISSUE TITLE
Readme Enchantment

### ISSUE THREAD

**Issue by sudo-nautilus** [BtbN/FFmpeg-Builds#59]
I don't know how to make an introduction so, I'm saying the things directly.

I saw so many people who wants **32 bit** FFmpeg for their system. That's the exact reason why I made this repo - github.com/sudo-nautilus/FFmpeg-Builds-Win32
Could you please add the repo link in `readme.md`. It will be helpful for those who want 32 bit builds,
That's it

**Comment by BtbN** [comment]
I can't really guarantee that you keep the same level of maintenance to those builds. As in, porting over new library versions, security upgrades, etc.
So I'm not too keen on advertising something I can't give any guarantees about.

The scripts in this repo are perfectly capable of building 32 bit executables, there just is no asset space left to do so in the auto-builds without sacrificing more useful other build variants.
So if someone for some reason still needs a 32 bit variant, building that manually is possible relatively easily.

Overall the need for 32 bit builds seems very low though. 64 bit Windows systems are the norm for over a decade at this point.

**Comment by sudo-nautilus** [comment]
> I can't really guarantee that you keep the same level of maintenance to those builds. As in, porting over new library versions, security upgrades, etc.
> So I'm not too keen on advertising something I can't give any guarantees about.
> 
> The scripts in this repo are perfectly capable of building 32 bit executables, there just is no asset space left to do so in the auto-builds without sacrificing more useful other build variants.
> So if someone for some reason still needs a 32 bit variant, building that manually is possible relatively easily.
> 
> Overall the need for 32 bit builds seems very low though. 64 bit Windows systems are the norm for over a decade at this point.

But anyway people including me use that,
I'm currently writing a script to sync the fork

**Comment by sudo-nautilus** [comment]
Ok synced fork

**Comment by sudo-nautilus** [comment]
> I can't really guarantee that you keep the same level of maintenance to those builds. As in, porting over new library versions, security upgrades, etc.
> So I'm not too keen on advertising something I can't give any guarantees about.
> 
> The scripts in this repo are perfectly capable of building 32 bit executables, there just is no asset space left to do so in the auto-builds without sacrificing more useful other build variants.
> So if someone for some reason still needs a 32 bit variant, building that manually is possible relatively easily.
> 
> Overall the need for 32 bit builds seems very low though. 64 bit Windows systems are the norm for over a decade at this point.

you can do that, sure. It will be maintained at the same level of your repo. There' s also 32 bit guys nowadays. The scripts require Docker in order to Build the desired variant.  Docker is not supported on 32 bit windows. And that's why We* cant build FFmpeg. Even though the need of 32 bit builds seems low, there are some guys who actually need em.

* One day I tried to build FFmpeg. There were a long list of errors. And I searched each of them in the internet and saw that there are so many people just like me. In your repo I went through the issues and understood there are people who needs 32 bit builds. These people and me are referred here as 'we'.

**Comment by sudo-nautilus** [comment]
https://github.com/BtbN/FFmpeg-Builds/issues/61#issuecomment-813067664
