### ISSUE TITLE
Can no longer encode to libaom-av1 as it always raises error 

### ISSUE THREAD

**Issue by cdgriffith** [BtbN/FFmpeg-Builds#64]
```
 ffmpeg -i .\720p_test.mkv -c:v libaom-av1 out.mkv
  ...
 
libvmaf WARNING could not read model from path: "/usr/local/share/model/vmaf_v0.6.1.json"
Fatal error: Failed to load VMAF model.
 ```

Went back through the releases and the error starts with this one https://github.com/BtbN/FFmpeg-Builds/releases/tag/autobuild-2021-04-04-12-39.    

Last working version: https://github.com/BtbN/FFmpeg-Builds/releases/tag/autobuild-2021-04-03-16-28

**Comment by BtbN** [comment]
https://github.com/Netflix/vmaf/blob/master/resource/doc/ffmpeg.md#note-about-the-model-path-on-windows seems like you will have to manually specify its path, since Windows has no sane default (and it's obviously not part of a static ffmpeg binary)

**Comment by cdgriffith** [comment]
This is not using VMAF at all though to my knowledge. Unless the `libaom-av1` internals changed to use them by default recently.

**Comment by BtbN** [comment]
libaom does internall use vmaf for _something_, but I'm not able to make sense of their code.
I've switched the builds to bake in the vmaf model, so this might go away with tomorrows build.

**Comment by BtbN** [comment]
Looking at https://aomedia.googlesource.com/aom/+/refs/heads/master/aom_dsp/vmaf.c#39, it seems to have just a hardcoded default path, with an option to change the path, but no option whatsoever to use a built in model.
So enabling the built in models might not fix it.
libaom on Windows might just be plain broken. I don't see how this could ever work.
FFmpegs libaom wrapper has no way to pass in the model path, so you can't even manually download the model and pass its path.

**Comment by Thomasedv** [comment]
I made an issue on aom tracker for this exact thing, when aomenc is compiled with support for tune=vmaf. So far no reaction on the issue. If you disable tune vmaf support in aom during compile, then aomenc can be used without specifying a valid  vmaf model path.  

https://bugs.chromium.org/p/aomedia/issues/detail?id=3021 (Well, the owner of it seems to have been away for almost 2 
months)

**Comment by Thomasedv** [comment]
I think a possible patch would be to fix this line:
https://aomedia.googlesource.com/aom/+/e97422c41b2f186c36401fdb3eb332455377c39b/av1/av1_cx_iface.c#2436
to have a check for tune vmaf being selected, a similar check is done elsewhere in the script if aomenc was not compiled with vamf support, so if anyone is smarter than me and can edit and make a patch, i'd just add this condition and see if that does the trick:

```
if (extra_cfg->tuning >= AOM_TUNE_VMAF_WITH_PREPROCESSING &&
      extra_cfg->tuning <= AOM_TUNE_VMAF_NEG_MAX_GAIN)
```

**Comment by BtbN** [comment]
I included a patch into these builds yesterday to implement a fallback to the built in models:
https://github.com/BtbN/FFmpeg-Builds/blob/master/patches/aom/0001-Fall-back-to-built-in-vmaf-model-on-load-failure.patch

**Comment by BtbN** [comment]
xxd was still missing, and vmafs build system just silently does not include the built in models in that case.
Actually working now in tomorrows build.

aom even trying to initialize vmaf when not using it is definitely a bit weird though.

**Comment by nanake** [comment]
> https://bugs.chromium.org/p/aomedia/issues/detail?id=3021


fixed in https://aomedia.googlesource.com/aom/+/c848f899781b764c7baa516a8aebc10b73802e4d





> I included a patch into these builds yesterday to implement a fallback to the built in models:
> https://github.com/BtbN/FFmpeg-Builds/blob/master/patches/aom/0001-Fall-back-to-built-in-vmaf-model-on-load-failure.patch

Is the patch still needed/relevant? as per above commit.☝️

**Comment by BtbN** [comment]
Yes, it is. Doesn't look like they added support for built-in models whatsoever.
