### ISSUE TITLE
Open Discussions

### ISSUE THREAD

**Issue by sudo-nautilus** [BtbN/FFmpeg-Builds#65]
Title says it all here.
Open the discussions  by going to settings > Features and checking 'Discussions'

>Discussions is the space for your community to have conversations, ask questions and post answers without opening issues.
>                                                     - GitHub

**Comment by BtbN** [comment]
I don't think this is the right place for such a discussion forum.
I'd have to moderate that, answer questions and generally add a lot of housekeeping work. And I'm already relatively short on time.

These are also just builds of FFmpeg, not FFmpeg itself. For any kind of discussions regarding usage of FFmpeg itself, you are much better off using the regular user support channels of FFmpeg, or even asking on Stackoverflow.

**Comment by sudo-nautilus** [comment]
Ok, Got that. I too am running on a short time
