### ISSUE TITLE
Silent video renders from REAPER daw

### ISSUE THREAD

**Issue by reaperblog** [BtbN/FFmpeg-Builds#66]
Hey there
The REAPER community has been having trouble finding a working shared ffmpeg build since the Zeranoe site shut down.

The last version that worked for us was 4.3.1. Later builds export without audio tracks.

Maybe you have some idea what changed in FFMPEG or what made the Zeranoe build special.

Here's an image with render settings, [ffmpeg 4.4 ](https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2021-04-20-14-14/ffmpeg-n4.4-5-ge3fb0f0c88-win64-gpl-shared-4.4.zip) exported video properties, and ffmpeg 4.3.1 exported.

Really hope you can help
Thanks
~Jon~

**Comment by BtbN** [comment]
I'm not sure what to tell you without any further insight really.

I'd highly suspect that you aren't using the ffmpeg APIs correctly, since a lot of other applications are able to get audio working just fine, but that's something you better ask on for example the ffmpeg-users mailing list than here.

**Comment by reaperblog** [comment]
sorry forgot the image https://imgur.com/a/4zayTO9

**Comment by BtbN** [comment]
Yeah, there's really nothing all that helpful I could tell you there.
I don't know the software or its code, so all I can tell you is again that I think you are not using the ffmpeg APIs correctly.
There was no ABI or API break between 4.3 and 4.4, so it breaking seems unlikely though.

**Comment by sudo-nautilus** [comment]
![image](https://i.imgur.com/PXvKfip.png)

This is the image. I did this just to preview the image within this page

**Comment by sudo-nautilus** [comment]
I saw issues with soundless rendering in REAPER Daw.
The following forums may help you :
- https://forum.cockos.com/showthread.php?t=243052
- https://forum.cockos.com/showthread.php?t=242358
- https://forum.cockos.com/showthread.php?t=242951

**Comment by MD-78** [comment]
Latest working version is FFmpeg 4.3.2 here. Version 4.4 fails.
