### ISSUE TITLE
I can't include dll files in my C# project references

### ISSUE THREAD

**Issue by Peace569** [BtbN/FFmpeg-Builds#70]
Hello.
I can't include these DLL files in my .net core 5.0 project's references.
As you said, I put it in "build output" folders, so there is not build error.
But it is not working.
There is a Bad image exception error when I am building.
Sorry, but would you help me?
Regards.

**Comment by BtbN** [comment]
Do the ffmpeg executables packaged along with the libraries work?
If so, the DLLs are in good condition, and you have to look for the issue somewhere on your/the C#/.NET side of things.
BadImage makes me thing that you are building a 32bit application and are trying to load 64 bit DLLs.

**Comment by Peace569** [comment]
ffmpeg exe file is not working on my PC.
And my app is 64 bit.
Would you teach me what is the reason ?

**Comment by BtbN** [comment]
I don't know what the reason is then, but you need to ask that to the appropriate supports channels.

**Comment by Peace569** [comment]
appropriate supports channels?
Where can I find it?

**Comment by BtbN** [comment]
I don't know that either, I don't work with .NET usually.
But I really can't help you, and if the ffmpeg binaries work, your issue is not this build, but somewhere in your code or in the stuff surrounding it.

**Comment by Peace569** [comment]
Ok, thanks for your reply.
I will try again.
