### ISSUE TITLE
When will SVT-AV1 be updated?

### ISSUE THREAD

**Issue by n00mkrad** [BtbN/FFmpeg-Builds#72]
SVT-AV1 has been updated to 0.8.7 around a week ago.

However, in the builds here, version `v0.8.6-83-g0a253a1c` is included.

Should it not compile the latest, that being 0.8.7?

**Comment by BtbN** [comment]
Whenever I do another round of updates, or someone sends a PR to update it.
The packages do not get updated automatically, that would break the build every other week.
Usually I do updates about once a month, or whenever something comes up to warrant a spontaneous update.

**Comment by n00mkrad** [comment]
> Whenever I do another round of updates, or someone sends a PR to update it.
> The packages do not get updated automatically, that would break the build every other week.
> Usually I do updates about once a month, or whenever something comes up to warrant a spontaneous update.

Thanks for the info.

I created this PR, if I understand correctly this is all that's needed to change the version it compiles.

https://github.com/BtbN/FFmpeg-Builds/pull/73

**Comment by BtbN** [comment]
Version is updated to latest release now.
