### ISSUE TITLE
Is it support dvb-teletext?

### ISSUE THREAD

**Issue by DorisGM** [BtbN/FFmpeg-Builds#78]
I want to transform a ts to m3u8  with this cmd.

like:
ffmepg  -reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1 -reconnect_delay_max 0  -i test.ts -c copy -f hls -hls_flags append_list -hls_list_size 0 -hls_segment_filename output-%03d.ts output.m3u8

The test.ts include dvb-teletext. and the cmd failed. report below message.

[error](https://note.youdao.com/yws/api/personal/file/B1CA241B9043497698EA029BFEC9A958?method=download&shareKey=0caf01bd60665e97d0ffa2309d2dcc71)

So, i want to know , is it support dvb-teletext when i transform  to m3u8 like above cmd

**Comment by DorisGM** [comment]
And  i see the configuration of ffmpeg . it already open enable zvbi .   I checkout the official ffmpeg build to test it, and it configuration like below picture:

[ffmpeg configuration](https://note.youdao.com/yws/api/personal/file/267587CDCF5141A6A55727D87BABAA3D?method=download&shareKey=436158ad1089d275416ab0af697d5427)

**Comment by sudo-nautilus** [comment]
- ![Error Report](https://note.youdao.com/yws/api/personal/file/B1CA241B9043497698EA029BFEC9A958?method=download&shareKey=0caf01bd60665e97d0ffa2309d2dcc71)

- ![ffmpeg config](https://note.youdao.com/yws/api/personal/file/267587CDCF5141A6A55727D87BABAA3D?method=download&shareKey=436158ad1089d275416ab0af697d5427)

If you send like this it will be easy to see the image without going to a new tab 😂

**Comment by sudo-nautilus** [comment]
Is the 'official' one working for you ?

**Comment by sudo-nautilus** [comment]
You may refer to this question on Stackoverflow:
https://stackoverflow.com/questions/15005436/errors-when-decode-h-264-frames-using-ffmpeg

**Comment by DorisGM** [comment]
> Is the 'official' one working for you ?

No. 'Official' don't working either.  The above errors are the result of the official one execution.

**Comment by DorisGM** [comment]
> * ![Error Report](https://camo.githubusercontent.com/0b6a5baa5530b93e16fcd7741126eb81e77e3c5663f8bc42923f3fee35cedf8a/68747470733a2f2f6e6f74652e796f7564616f2e636f6d2f7977732f6170692f706572736f6e616c2f66696c652f42314341323431423930343334393736393845413032394246454339413935383f6d6574686f643d646f776e6c6f61642673686172654b65793d3063616630316264363036363565393764306666613233303964326463633731)
> * ![ffmpeg config](https://camo.githubusercontent.com/a64153c4b3bc2136f23980238671b744d61117eda016ac6e2471f78cbd7f2cd8/68747470733a2f2f6e6f74652e796f7564616f2e636f6d2f7977732f6170692f706572736f6e616c2f66696c652f32363735383743444346353134314136413535373237443837424142414133443f6d6574686f643d646f776e6c6f61642673686172654b65793d3433363135386164313038396432373534313661623061663639376435343237)
> 
> If you send like this it will be easy to see the image without going to a new tab

sorry, i will fix it  next time.

**Comment by sudo-nautilus** [comment]
> > * ![Error Report](https://camo.githubusercontent.com/0b6a5baa5530b93e16fcd7741126eb81e77e3c5663f8bc42923f3fee35cedf8a/68747470733a2f2f6e6f74652e796f7564616f2e636f6d2f7977732f6170692f706572736f6e616c2f66696c652f42314341323431423930343334393736393845413032394246454339413935383f6d6574686f643d646f776e6c6f61642673686172654b65793d3063616630316264363036363565393764306666613233303964326463633731)
> > * ![ffmpeg config](https://camo.githubusercontent.com/a64153c4b3bc2136f23980238671b744d61117eda016ac6e2471f78cbd7f2cd8/68747470733a2f2f6e6f74652e796f7564616f2e636f6d2f7977732f6170692f706572736f6e616c2f66696c652f32363735383743444346353134314136413535373237443837424142414133443f6d6574686f643d646f776e6c6f61642673686172654b65793d3433363135386164313038396432373534313661623061663639376435343237)
> > 
> > If you send like this it will be easy to see the image without going to a new tab
> 
> sorry, i will fix it next time.

:)

**Comment by sudo-nautilus** [comment]
> > Is the 'official' one working for you ?
> 
> No. 'Official' don't working either. The above errors are the result of the official one execution.


This may help you : 


>That just means that ffmpeg has not seen a keyframe yet, which carries SPS and PPS information. SPS and PPS are crucial in decoding an incoming frame/slice. Keyframes are sent periodically(i.e. every 5-10 seconds or more); so if turns out that you joined a stream before the keyframe arrived; you will see this warning for every frame until a keyframe shows up.

> As soon as the keyframe shows up from the wire, ffmpeg will have enough information to decode that frame(and any subsequent frames until the next keyframe), so those warnings will go away.    - `Aki` on Stackoverflow

**Comment by DorisGM** [comment]
> > > Is the 'official' one working for you ?
> > 
> > 
> > No. 'Official' don't working either. The above errors are the result of the official one execution.
> 
> This may help you :
> 
> > That just means that ffmpeg has not seen a keyframe yet, which carries SPS and PPS information. SPS and PPS are crucial in decoding an incoming frame/slice. Keyframes are sent periodically(i.e. every 5-10 seconds or more); so if turns out that you joined a stream before the keyframe arrived; you will see this warning for every frame until a keyframe shows up.
> 
> > As soon as the keyframe shows up from the wire, ffmpeg will have enough information to decode that frame(and any subsequent frames until the next keyframe), so those warnings will go away.    - `Aki` on Stackoverflow

I'll try to fix it first . 
And i think most likely because it contains dvb_teletext, the second error shows that writing to the vtt file failed. If I pull a stream containing dvb_subtitle not dvb teletext and convert it to m3u8 .it's works.  So  i doubt whether this cmd support dvb-teletext.

**Comment by sudo-nautilus** [comment]
Hmm

**Comment by BtbN** [comment]
Closing this here.
It does not seem to be an issue with these builds specifically.
If you think it is, please elaborate and re-open.

**Comment by ValZapod** [comment]
> It does not seem to be an issue with these builds specifically.

It is. gyan builds have --enable-libzvbi for this. See https://trac.ffmpeg.org/ticket/4782

**Comment by BtbN** [comment]
I added that library, hopefully.
Its build system is a hot mess and it barely still holds together.

Please report if it works.

**Comment by ValZapod** [comment]
> Please report if it works.

It does work. I used ffplay -i "20131121_2345 Espinete en Torres y Reyes.ts" -txt_page 888

where sample is from https://trac.ffmpeg.org/ticket/5846

**Comment by BtbN** [comment]
Great, thanks!
