### ISSUE TITLE
Why is there a vulkan version and a normal verion at the same time?

### ISSUE THREAD

**Issue by SekiBetu** [BtbN/FFmpeg-Builds#8]
ffmpeg-N-99481-g1e97fbb3b6-win64-gpl-vulkan.zip
ffmpeg-N-99481-g1e97fbb3b6-win64-gpl.zip

I didn't see any vulkan branch from https://github.com/FFmpeg/FFmpeg
What's the difference between them?
Does the vulkan version contains the nromal version?

**Comment by BtbN** [comment]
Because the vulkan one depends on vulkan, and will not even start on a PC without a working vulkan driver.

**Comment by SekiBetu** [comment]
got it

**Comment by BtbN** [comment]
It's a bit of an odd situation really. Vulkan has a dynamic loader, but you cannot statically link it, but instead load it from the driver.
So either your binaries only run on systems which have working Vulkan (Or fail to launch with a missing .dll error), or you have to write a literal loader for the loader....
