### ISSUE TITLE
EXR layers/channel

### ISSUE THREAD

**Issue by ElizzaRg** [BtbN/FFmpeg-Builds#81]
I noticed that your version supports EXR to EXR conversion.
But I couldn't get the layers and channels to work. Can you tell me how to do this
I try using this code 
3 layers: FinalImageObjects, FinalImageGround, FinalImageDefaultLayer
but not working all layers and not saved.
My code 
ffmpeg.exe -layer "FinalImageObjects" -i C:/Image1.exr -layer "FinalImageObjects" -i C:/Image2.exr -filter_complex "[0][1] hstack=inputs=2" C:/ImageOutput.exr

error Channel doesn't match layer : FinalImageGround.A, FinalImageGround.B .... and FinalImageDefaultLayer.A, FinalImageDefaultLayer.B

**Comment by BtbN** [comment]
I have no experience with EXR, you'll probably have more luck on IRC or on the ffmpeg-users mailing list.

**Comment by ElizzaRg** [comment]
Thank you for giving a quick answer, I'll do it then
