### ISSUE TITLE
nvenc not work after changes in "sei"

### ISSUE THREAD

**Issue by moob158** [BtbN/FFmpeg-Builds#82]
@BtbN  with your last three changes in "sei" at 4 of June   ffmpeg nvenc not working anymore.

I have notebook graphics card  Geforce GTX 1650, nvenc stopped working after the changes in sei

**Comment by BtbN** [comment]
This is not the place to bring up issues with FFmpeg itself.
Please open a ticket on trac about ffmpeg issues, and be more descriptive than "doesn't work".
Nvenc works fine for me right now, and when I tested those patches.

**Comment by moob158** [comment]
oki, sorry (:

But it doesn't give me any error, ffmpeg just opens and closes.

I solved it by reverting your sei code to the previous state and it works now. So I'm not going to open any ticket on trac.

**Comment by BtbN** [comment]
That's a terrible reason not to open a ticket.
Please open a ticket with how to reproduce it, a backtrace of the likely crash is also helpful.

**Comment by moob158** [comment]
I have been testing and this only happens with **mp4** files.

With **mkv** files work fine. I don't have an account at ffmpeg trac

this is what happens, if I don't pause the batch it closes ffmpeg

![Capturar](https://user-images.githubusercontent.com/60049180/120907374-af92fe80-c658-11eb-91f8-a9d72a087edd.PNG)

**Comment by ValZapod** [comment]
Oogh, this is your issue then?? https://trac.ffmpeg.org/ticket/9351#comment:28

@BtbN It does look real, but I cannot reproduce besides the fact that it is also requiring -bf 0 or -extra_hw_frames 4, but that is a different issue. You changing the default really managed to find all kinds of stuff.
