### ISSUE TITLE
4.4-19 filter set exposure, get frame delay serious

### ISSUE THREAD

**Issue by Caprey** [BtbN/FFmpeg-Builds#85]
`const AVFilter *exposureFilter = avfilter_get_by_name("exposure");
    ret = avfilter_graph_create_filter(&m_exposureFilterCtx, exposureFilter, "exposure", "exposure=-0.95" , NULL, m_filterGraph);
    if (ret < 0) {
        av_log(NULL, AV_LOG_ERROR, "Fail to create exposure filter:%d\n", ret);
        return -1;
    }`

found show frame delay serious, when annotation exposure code, show frame is normal

**Comment by BtbN** [comment]
Not sure what you mean, can you elaborate?

Keep in mind that issues here are only about the builds specifically, not general ffmpeg issues or questions.
For those, you are much better of asking on the ffmpeg-user list or opening a ticket on trac for issues.

**Comment by BtbN** [comment]
Closing this.
Feel free to re-open if you think this is an issue with these builds specifically.
