### ISSUE TITLE
Can you enable vanc support?

### ISSUE THREAD

**Issue by MycroBeat** [BtbN/FFmpeg-Builds#86]
Hi. 

Recently, i saw that ffmpeg supports vanc encoding and decoding over SDI (and over libx264 if i understand correctly from some patches).

All details about what vanc library does is here: [libklvanc](https://github.com/stoth68000/libklvanc).
The enablement for vanc in ffmpeg is `--enable-libklvanc`.

It is possible to add vanc support to ffmpeg builds?

Thank you for all your efforts.

**Comment by sudo-nautilus** [comment]
Sounds cool

**Comment by BtbN** [comment]
Not sure I fully understand that library.
It decodes SDI, but it does not seem to interface with any actual hardware that can do SDI?
In any case, it does not seem to have any dependencies, so adding it should not be a big issue.

**Comment by BtbN** [comment]
Just checked, it is indeed only used in the Decklink in/outdev.
And given that Decklink is nonfree and thus missing from these builds, adding libklvanc would do literally nothing.
Or am I missing something else it does?

**Comment by BtbN** [comment]
Closing this here. I don't have an issue with adding that library, but for all I can see in the code and configure script, it would do absolutely nothing unless I'd also add Decklink support. Which I can't due to it being nonfree.
