### ISSUE TITLE
[feature request]enable fdk-aac in lgpl release

### ISSUE THREAD

**Issue by fuchanghao** [BtbN/FFmpeg-Builds#9]
In my knowledge something like "openssl" and "fdk-aac" which can not be open in GPL build but works with lgpl build.

**Comment by BtbN** [comment]
I am not sure about the legal side of things there, and since fdk-aac has a weird license, I'd rather be on the side of caution.

**Comment by megapro17** [comment]
who cares? it will be very useful. if you afraid for yourself do not, nobody will do anything to you

**Comment by Boscop** [comment]
There is no legal issue, this repo also includes fdk-aac:
https://github.com/marierose147/ffmpeg_windows_exe_with_fdk_aac/releases

**Comment by w10dd** [comment]
amazing, thx for link

**Comment by AnimMouse** [comment]
My repo [ffmpeg-autobuild](https://github.com/AnimMouse/ffmpeg-autobuild) also includes fdk-aac.

**Comment by BtbN** [comment]
Please don't advertise potentially legally problematic things here.
