### ISSUE TITLE
makeimage fails for windows

### ISSUE THREAD

**Issue by Ben8823** [BtbN/FFmpeg-Builds#90]
Hi,

I'm trying to build ffmpeg for windows:
`./makeimage.sh win64 gpl`

Unfortunately I'm getting the following error. Any ideas what could be wrong?
```
#6 [layer-10-mingw 1/1] RUN --mount=src=scripts.d/10-mingw.sh,dst=/stage.sh --mount=src=patches/mingw,dst=/patches run_stage /stage.sh
#6 sha256:995c2822c3ec2cab865ff4ed6682d4cadbd2bbaae3bd3a9fb99b4ff686980924
#6 0.186 /bin/sh: 1: run_stage: not found
#6 ERROR: executor failed running [/bin/sh -c run_stage /stage.sh]: exit code: 127
------
 > [layer-10-mingw 1/1] RUN --mount=src=scripts.d/10-mingw.sh,dst=/stage.sh --mount=src=patches/mingw,dst=/patches run_stage /stage.sh:
------
executor failed running [/bin/sh -c run_stage /stage.sh]: exit code: 127
```

**Comment by BtbN** [comment]
That's weird.
I've literally just built an image locally, doing nothing more but that command. And the builds on Github Actions are also working fine.
Did you modify something, or did some files accidentally got lost?

**Comment by sudo-nautilus** [comment]
@Ben8823 you can use the autobuilds found at releases

**Comment by Ben8823** [comment]
Yes, i'm on latest master without any modifications.
I'm using git bash for windows to execute the script, maybe there are some incompatibilities there. What bash are you using?

@sudo-nautilus  Unfortunately no, as i want to make some modifcation in the ffmpeg code.

**Comment by BtbN** [comment]
The shell should be mostly irrelevant, since most of it is run inside of the container.
This seems to me like your docker setup is misbehaving, not copying/executing anything as it should.

Things work fine for me in WSL2.

**Comment by Ben8823** [comment]
Ok then i have no clue what's wrong. I did reset docker to factory defaults. wsl 2 is working fine:
```
 NAME                   STATE           VERSION
* docker-desktop         Running         2
  docker-desktop-data    Running         2
```  
I still get the same error though.
Where is the run_stage script supposed to end up in the container? At which point should it get copied over?

**Comment by BtbN** [comment]
It's this script: https://github.com/BtbN/FFmpeg-Builds/blob/master/images/base/run_stage.sh ending up at /usr/bin/run_stage via https://github.com/BtbN/FFmpeg-Builds/blob/master/images/base/Dockerfile#L17.

My primary suspicion with doing this from an mingw/msys shell would be that the executable bit on the scripts got lost, because Windows-Git is funky.

**Comment by Ben8823** [comment]
Thanks for that hint. The file got copied correctly with executable bit set, but it had windows line endings.
I've changed my git line ending handling to unix style, and now it's working fine.

**Comment by garoto** [comment]
> changed my git line ending handling to unix style 

Is this something done via `git config`?

**Comment by green-kartik** [comment]
> Thanks for that hint. The file got copied correctly with executable bit set, but it had windows line endings.
> I've changed my git line ending handling to unix style, and now it's working fine.

Can you show what you did exactly, I am running into the same problem. 
Please!!!

**Comment by Ben8823** [comment]
There are different ways to achieve this. I've created a ```.gitattributes``` file in the root folder with the following content:
````
* binary
````

**Comment by green-kartik** [comment]
Ty @Ben8823, Ultimately I resolved this problem by building it in ubuntu VM. Thank you for your help!
