### ISSUE TITLE
Frei0r

### ISSUE THREAD

**Issue by audas** [BtbN/FFmpeg-Builds#91]
Hi - I was wondering if you have any ideas on enabling frei0r with these builds ?

**Comment by BtbN** [comment]
I remember it not playing well with static linking or something.
Been a while since I looked at it, but there was some issue with it that made me ignore it so far.

**Comment by audas** [comment]
Thanks.

**Comment by Leif-W** [comment]
The gyan.dev project over at https://github.com/GyanD/media-autobuild_suite seems to be building fei0r statically.  Perhaps there are some clues there?

**Comment by sudo-nautilus** [comment]
```bat
if %PROCESSOR_ARCHITECTURE%==x86 if NOT DEFINED PROCESSOR_ARCHITEW6432 (
    echo ----------------------------------------------------------------------
    echo. 32-bit host machine and OS are no longer supported by the suite
    echo. nor upstream for building.
    echo. Please consider either moving to a 64-bit machine and OS or use
    echo. a 64-bit machine to compile the binaries you need.
    pause
    exit
)
```


Hmm...

**Comment by Leif-W** [comment]
@sudo-nautilus Where's this from, and what is the relation to static build/link of frei0r?  Is it related to the way the Docker file is set up?

**Comment by sudo-nautilus** [comment]
> @sudo-nautilus Where's this from

This is from the repo that you just sent before,
That is, from line [34](https://github.com/GyanD/media-autobuild_suite/blob/05070f3f3151140a5c644ccd175c824cbf3513c9/media-autobuild_suite.bat#L34) to line [42](https://github.com/GyanD/media-autobuild_suite/blob/05070f3f3151140a5c644ccd175c824cbf3513c9/media-autobuild_suite.bat#L42)

**Comment by BtbN** [comment]
It's far from impossible to add freior. I just haven't had any time to look into it yet.

**Comment by BtbN** [comment]
Added it, though the ffmpeg code for it is ancient, and I had to add a dlopen wrapper library just for that (ffmpeg has one bundled in, but the frei0r code does not use it...).

Please let me know if it works, since I'm not really set up to test it.

**Comment by audas** [comment]
Will take a look - thanks for this. Amazing.
