### ISSUE TITLE
where to get config.h?

### ISSUE THREAD

**Issue by HppZ** [BtbN/FFmpeg-Builds#92]

**Comment by sudo-nautilus** [comment]
![umwhat](https://user-images.githubusercontent.com/78522210/126762818-3ebc91f5-ebb2-4409-b4a3-5274abd59682.png)

**Comment by HppZ** [comment]
[config.h.txt](https://github.com/BtbN/FFmpeg-Builds/files/6867793/config.h.txt)
fftools\ffmpeg.c included this 'config.h'

**Comment by BtbN** [comment]
config.h is not a public header, so you won't find it in the shared archives.

**Comment by HppZ** [comment]
is it ok to make them (files like config.h) public to us?

**Comment by BtbN** [comment]
What do you mean? It's an internal header, used to configure the build of ffmpeg itself. You don't need it to utilize the API.
If you want it to be a public one for whatever reason, you will need to discuss that on ffmpeg-devel.

Closing this one here, since it's not an issue with the builds.

**Comment by HppZ** [comment]
I want to build ffmpeg.exe, and fftools\ffmpeg.c need header files like 'config.h'.

**Comment by BtbN** [comment]
While building ffmpeg itself, config.h is available. So I'm not sure I understand what you're doing.

**Comment by HppZ** [comment]
I just want to build fftools, but not ffmpeg itself. so I need thoese headers.

**Comment by BtbN** [comment]
That makes no sense. ffmpeg.c cannot be built independently.
If you just want an ffmpeg binary, you can grab it from the static builds here. That's exactly what they're for.

**Comment by HppZ** [comment]
I want to build my own fftools, so I download ffmpeg public binary and headers from BtbN, and I still need those non-public headers like 'config.h'.

**Comment by BtbN** [comment]
You cannot build the fftools indepentendly of the rest of ffmpeg.
If you want to build them yourself, you got to build the entire rest of ffmpeg alongside as well.

**Comment by HppZ** [comment]
Got you, really thank you.

________________________________
发件人: BtbN ***@***.***>
发送时间: Sunday, July 25, 2021 7:49:51 PM
收件人: BtbN/FFmpeg-Builds ***@***.***>
抄送: HppZ ***@***.***>; Author ***@***.***>
主题: Re: [BtbN/FFmpeg-Builds] where to get config.h? (#92)


You cannot build the fftools indepentendly of the rest of ffmpeg.
If you want to build them yourself, you got to build the entire rest of ffmpeg alongside as well.

―
