### ISSUE TITLE
I tried to build 32bit version, but it raised an error below, please help me.

### ISSUE THREAD

**Issue by ledunguit** [BtbN/FFmpeg-Builds#93]
Unable to find image 'ghcr.io/btbn/ffmpeg-builds/win32-gpl-shared:latest' locally
docker: Error response from daemon: Head https://ghcr.io/v2/btbn/ffmpeg-builds/win32-gpl-shared/manifests/latest: denied.

**Comment by BtbN** [comment]
You need to make the image first. There are no pre-built 32bit images.
Use the respective script right next to the build script.

**Comment by sudo-nautilus** [comment]
@ledunguit great attempt,
BtbN is literally correct, you need to make the image first,

But if you want the build (x86) you can check [my repo](https://github.com/sudo-nautilus/FFmpeg-Builds-Win32)
