### ISSUE TITLE
Difference between ffmpeg-N-* and ffmpeg-n4.4-*?

### ISSUE THREAD

**Issue by Leif-W** [BtbN/FFmpeg-Builds#94]
Looking at the assets page, the file names, the file contents, the README.md, and skimming the rest of the repo source, I can't seem to find any information about the difference between these builds, apart from different hash in filenames, and the ffmpeg-N-* builds seem to use newer shared library versions.  Could you drop a note in the README to explain the difference?

**Comment by sudo-nautilus** [comment]
That is quite simple,
`ffmpeg-n4.4-*` is built from the 4.4 release branch instead of master. While the other one you mentioned (`ffmpeg-N-*`) is built from the master branch

**Comment by Leif-W** [comment]
@sudo-nautilus I understand the difference between a tagged release and master (HEAD), and suspected this.  Thank you for the explanation.  The explanation is simple, but the naming convention is not at all clear or simple.  Why not `ffmpeg-release-4.4-*` and `ffmpeg-master-*`?  Then the file name would be self-documenting.  That would be truly simple.  ;-)  Or at least, a quick note in the README.

**Comment by sudo-nautilus** [comment]
That's a great idea but, I assume that `N` or `n` means `Nightly Builds` here

**Comment by BtbN** [comment]
N is literally what upstream ffmpeg calls the builds, I'm not making those version names. No idea what it actually stands for.

**Comment by Leif-W** [comment]
Thank you both for the clarifications!

**Comment by sudo-nautilus** [comment]
> N is literally what upstream ffmpeg calls the builds, I'm not making those version names. No idea what it actually stands for.

Hmm

**Comment by sudo-nautilus** [comment]
> Thank you both for the clarifications!

You are welcome

**Comment by ValZapod** [comment]
> Why not `ffmpeg-release-4.4-*`

Because it is not release. Commits from 4.5 are right now being backported into 4.4. See: https://github.com/FFmpeg/FFmpeg/commits/release/4.4

Release is the 4.4 tag...

**Comment by Leif-W** [comment]
> > Why not `ffmpeg-release-4.4-*`
> 
> See: https://github.com/FFmpeg/FFmpeg/commits/release/4.4

The URL literally has "release" followed by "4.4", hence my question remains valid as far as self documenting file names.

I understand that the various "release" n<major>.<minor> tags are moving targets, each with back ports from HEAD, which is tagged 4.5-dev.  This seems a departure from previous major.minor.patch tagged releases.  It's part of a trend over the past 15+ years in software development to move away from versions to various degrees.

The ffmpeg project chose a very peculiar versioning system.  I've never seen any version numbers or tags start with 'n', in projects over nearly 30 years.  The additional 'N' was also a cryptic choice, possibly for "nightly", but who knows.  I could probably find a discussion in an old email list or forum thread announcing the choice and explaining the rationale.

Again, none of these choices come from BtbN, but rather are merely inherited from FFmpeg.  The point is moot.  Dubious or not, the choices are legacy now, and the FFmpeg project is not likely to ever change in that regard, so I just accept it and move on.

Thanks for all the explanations and sorry for the line noise.

**Comment by BtbN** [comment]
I'm not building any tags.
It's building the release branch. The number after the tag is the number of commits sitting on top of it. When 4.4.1 will be tagged it will start counting up from that again.

I just don't see any point in building specific releases. All that means it intentionally missing out on backported bugfixes until someone tags a new release from them.
