### ISSUE TITLE
Latest build can't stream youtube videos

### ISSUE THREAD

**Issue by Telmesomething** [BtbN/FFmpeg-Builds#99]
Command used to try and stream the [Kabul airport bombing](https://www.youtube.com/watch?v=Plt3Vihi3Z8) on youtube results in the error shown in the screenshot. This also applies to the previous build downloaded 17 August this year. 

![ffplay_error_invalid-input](https://user-images.githubusercontent.com/33827636/131120721-08360ea7-90f7-4783-aba7-7551b5123862.PNG)

My system is Windows 8.0 installed in 2013 and upgraded to Windows 8.1 in February, 2014. Latest security patches have been installed. 

I tried to output the data in the screenshot to a text file which is why >**C:\FFmpeg-invalid-data.txt** appears appended to the command line. Although a file with that name was created it was empty which is why I uploaded a screenshot instead. 

The file won't play in VLC media player either, but will play in other open source media players such as SMplayer and KMplayer (both tested this morning).

**Comment by Telmesomething** [comment]
> 
> 
> ffmpeg isn't youtube-dl. It can't extract media links from html+js.

OK, thanks for tip. I'm a bit confused by the fact that FFplay doesn't have a problem playing a video on Vimeo namely [this one](ffplay.exe -i "https://player.vimeo.com/external/475047109.m3u8?s=1ab00313856707c6a306757c52d05dee9d4278aa")

**Comment by Telmesomething** [comment]
> 
> 
> [ytdl-org/youtube-dl](https://github.com/ytdl-org/youtube-dl/) or [soimort/you-get](https://github.com/soimort/you-get) is your friend.

Yes, I'm aware of that, but I merely want to watch youtube videos, not download every one to my own machine. VLC can stream yt vids, but Google is using their "Consent" requirement again which needs a new youtube.luac file to address the problem, but nobody wants to log a ticket to code.videolan at Github now because it requires 2FA. So I thought FFmpeg would be a good alternative. 

I'll take a look at soimort/you-get though. Haven't heard of that one before. Thanks for the tip.

**Comment by TimoRoth** [comment]
Ask youtube-dl for the video url then, and pass that to ffmpeg.
That vimeo link is a direct link to the video, so ffmpeg can play it. There is no functionality in ffmpeg to deal with the moving target that is YouTube, or any other website that needs extensive scraping.

**Comment by garoto** [comment]
`mpv` seems to be able to play YT content just fine currently when paired with `youtube-dl`. Can't see no issues from EU folks regarding "yt-dl+mpv" breakage anywhere.

**Comment by TimoRoth** [comment]
mpv just does exactly what I just described automatically if you pass it a Web-URL it has no clue how to handle.
FFmpeg does not have such magic built in. But you can trivially do it yourself, if you really want to watch videos via ffplay for some reason, or want to use it as ffmpeg input.

**Comment by garoto** [comment]
Yes, I read what you wrote and I know how the integration between yt-dl+mpv works. I'm replying to OP who mentions VLC and whatnot in his comment just above yours.

**Comment by Telmesomething** [comment]
> Ask youtube-dl for the video url then, and pass that to ffmpeg.
> That vimeo link is a direct link to the video, so ffmpeg can play it. There is no functionality in ffmpeg to deal with the moving target that is YouTube, or any other website that needs extensive scraping.

OK, understand. Thanks for clearing up the confusion. I'll try what you suggested and see what happens.

**Comment by ValZapod** [comment]
> bit confused by the fact that FFplay doesn't have a problem playing a video on Vimeo namely [this one]

This is not html. This is a file. m3u8 playlist that is supported by ffplay, no problem.

**Comment by sudo-nautilus** [comment]
> [ytdl-org/youtube-dl](https://github.com/ytdl-org/youtube-dl/) or [soimort/you-get](https://github.com/soimort/you-get) is your friend.

Literally yes. FFmpeg isn't a youtube client actually, and I think this isn't the perfect place to discuss encoding errors or something.
